'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanAppMemory=ui;})(typeof window==='undefined'?null:window,function(){
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const size=value=>typeof value==='number'&&Number.isFinite(value)?(value/1024**3).toLocaleString('de-DE',{maximumFractionDigits:2})+' GiB':'—';
 let active=null;
 function render(result){const plan=result.plan;return `<strong>${result.allowed?'RAM-Prüfung bestanden':'Mehr verfügbarer RAM erforderlich'}</strong><dl class="package-ram-values"><div><dt>Jetzt verfügbar</dt><dd>${size(result.available_bytes)}</dd></div><div><dt>Für Installation mit Reserve nötig</dt><dd>${size(result.required_available_bytes)}</dd></div><div><dt>Container-Obergrenzen</dt><dd>${size(plan.startup_limit_bytes)}</dd></div></dl><p>${Number(plan.container_count)} Dienste · ${escape(plan.profile_label)}${plan.office_enabled?' · mit Euro-Office':''}</p><p class="hint">Die Obergrenzen sind kein gemessener Verbrauch. Titan berücksichtigt laufende Container, die NAS-Reserve und zusätzlichen Platz während der Installation.</p>${result.allowed?'':`<p>${escape(result.health?.level==='critical'?'Der Kernel meldet einen RAM-Engpass.':plan.office_enabled?'Office abwählen, andere Dienste stoppen oder mehr RAM zuweisen.':'Andere Dienste stoppen, ein kleineres Profil wählen oder mehr RAM zuweisen.')}</p>`}${result.demo?'<p class="hint">Demo: simuliertes NAS mit 8 GiB RAM.</p>':''}`;}
 function fields(){return '<section class="notice package-ram-plan" data-app-memory aria-live="polite"><strong>Verfügbarer RAM wird geprüft …</strong></section>';}
 function mount(body,app,{api}){
  dispose();const form=body.querySelector('form'),panel=body.querySelector('[data-app-memory]'),submit=form?.querySelector('button[type="submit"]');if(!form||!panel||!submit)return;
  const state={body,app,api,alive:true,request:0,busy:false,progressLoading:false};active=state;
  async function refresh(){if(!state.alive||state.busy)return;const request=++state.request;submit.disabled=true;panel.classList.remove('warning');panel.textContent='Verfügbarer RAM wird geprüft …';
   const options={};for(const key of ['resource_profile','office_mode']){const value=form.elements['option-'+key]?.value;if(value)options[key]=value;}for(const input of form.querySelectorAll?.('[name^="option-stack_port_eurooffice_"]')||[])input.closest('.field').hidden=options.office_mode==='disabled';
   try{const result=await api('/api/apps/memory-plan',{app:app.id,options});if(!state.alive||request!==state.request)return;if(!result.plan||typeof result.allowed!=='boolean')throw Error('Die RAM-Prüfung hat kein gültiges Ergebnis geliefert.');panel.innerHTML=render(result);panel.classList.toggle('warning',!result.allowed);submit.disabled=!result.allowed;}
   catch(error){if(state.alive&&request===state.request){panel.innerHTML=`<strong>RAM-Prüfung nicht verfügbar</strong><p>${escape(error.message)}</p><button type="button" class="button small" data-ram-retry>Erneut prüfen</button>`;panel.classList.add('warning');submit.disabled=true;}}
  }
  const change=event=>{if(['option-resource_profile','option-office_mode'].includes(event.target.name))void refresh();};
  const retry=event=>{if(event.target.closest('[data-ram-retry]'))void refresh();};form.addEventListener('change',change);panel.addEventListener('click',retry);
  state.dispose=()=>{form.removeEventListener('change',change);panel.removeEventListener('click',retry);};void refresh();return state;
 }
 function progress(job){if(!active?.alive)return;const state=active;state.busy=true;const panel=state.body.querySelector('[data-app-memory]');panel.classList.remove('warning');panel.innerHTML=`<strong>${job.status==='queued'?'Installation wartet':'Installation läuft'}</strong><p>${escape(job.progress?.message||job.result?.message||job.message||'Images laden und Paketdienste einrichten. Du kannst währenddessen andere Bereiche öffnen.')}</p>`;if(job.status==='running'&&state.app.titan_package&&!state.progressLoading){state.progressLoading=true;state.api('/api/package-details?'+new URLSearchParams({app:state.app.id})).then(data=>{if(!state.alive||active!==state)return;const services=data.services||[],ready=services.filter(item=>item.ready).length;const phase={preparing:'Konfiguration einrichten',pulling:'Container-Images herunterladen',starting:'Dienste starten',ready:'Dienste bereit',failed:'Paket benötigt Prüfung'}[data.phase]||'Paketdienste einrichten';panel.innerHTML=`<strong>${escape(phase)}</strong><p>${ready} von ${services.length} Diensten bereit</p>${services.length?`<ul>${services.map(service=>`<li>${escape(service.name||service.id)} · ${service.ready?'Bereit':escape(service.state||'Wartet')}</li>`).join('')}</ul>`:''}`;}).catch(()=>{}).finally(()=>{state.progressLoading=false;});}}
 function failed(){if(active?.alive)active.busy=false;}
 function dispose(){if(active){active.alive=false;active.request++;active.dispose?.();active=null;}}
 return {fields,render,mount,progress,failed,dispose};
});
