'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanShortcuts=ui;})(typeof window==='undefined'?null:window,function(){
 const validKey=key=>typeof key==='string'&&/^(tool|app):[a-zA-Z0-9_-]{1,64}$/.test(key);
 const idOf=row=>typeof row==='string'?row:row.id;
 const defaults=['tool:files','tool:docker','tool:vms','tool:photos','tool:settings','tool:storage'];
 function normalize(value={},allowed=[]){
  const seen=new Set(),folders=new Set(),tools=new Set(allowed),hidden=new Set(value.hidden||[]);
  const take=key=>validKey(key)&&!seen.has(key)&&(key.startsWith('app:')||tools.has(key))&&!hidden.has(key)?(seen.add(key),true):false;
  const input=value.version===2||value.items?.length?value.items:defaults;
  const items=[];for(const row of Array.isArray(input)?input:[]){if(typeof row==='string'){if(take(row))items.push(row);}else if(row&&/^folder-[a-z0-9-]{1,40}$/.test(row.id)&&!folders.has(row.id)){folders.add(row.id);items.push({id:row.id,name:String(row.name||'Ordner').slice(0,40),items:(Array.isArray(row.items)?row.items:[]).filter(take)});}}
  const positions={},mobile_positions={};for(const [name,target]of [['positions',positions],['mobile_positions',mobile_positions]])for(const row of items){const key=idOf(row),p=value[name]?.[key];if(p&&Number.isInteger(p.x)&&Number.isInteger(p.y)&&p.x>=0&&p.y>=0&&p.x<32&&p.y<128)target[key]={x:p.x,y:p.y};}
  if(!value.docker_added&&items.length&&tools.has('tool:docker')&&!has(items,'tool:docker')&&!hidden.has('tool:docker'))items.push('tool:docker');
  return {version:2,items,positions,mobile_positions,docker_added:true,icon_size:['small','medium','large'].includes(value.icon_size)?value.icon_size:'medium',widgets:value.widgets||{visible:true,collapsed:false,items:['cpu','ram','health']}};
 }
 function place(items,positions,columns,rows,rowMajor=false){const used=new Set(),out={};columns=Math.max(1,columns);rows=Math.max(1,rows);for(const item of items){const key=idOf(item),preferred=positions[key];let x=preferred?Math.min(columns-1,preferred.x):0,y=preferred?Math.min(rows-1,preferred.y):0;while(used.has(x+','+y)){if(rowMajor){x++;if(x>=columns){x=0;y++;}}else{y++;if(y>=rows){y=0;x++;}if(x>=columns){x=0;rows++;y=rows-1;}}}used.add(x+','+y);out[key]={x,y};}return out;}
 function remove(items,key){return items.filter(row=>idOf(row)!==key).map(row=>typeof row==='string'?row:{...row,items:row.items.filter(id=>id!==key)});}
 function group(items,source,target){if(source===target||!validKey(source))return items;const next=remove(items,source),dest=next.find(row=>idOf(row)===target);if(!dest)return items;if(typeof dest==='object')dest.items.push(source);else next.splice(next.indexOf(dest),1,{id:'folder-'+Date.now().toString(36),name:'Ordner',items:[dest,source]});return next;}
 const has=(items,key)=>items.some(row=>row===key||typeof row==='object'&&row.items.includes(key));
 function safeUrl(value){try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?url.href:'';}catch{return '';}}
 async function mount(surface,{tools,user,icon,esc,api,toast,open,menu,action,confirm}){
  const doc=surface.ownerDocument,win=doc.defaultView;let alive=true,opened=null,contextKey=null,gesture=null,blockClick=0,revision=0,saving=false,failed=false,readonly=false,apps=[],layout;const pendingApps=new Map();const actionController=new AbortController();
  const entries=new Map(tools.map(([id,name,detail])=>['tool:'+id,{name,detail,glyph:id,href:'#'+id}]));
  const requests=await Promise.allSettled([api('/api/launcher-layout'),(user.role==='admin'||user.permissions?.apps?.allowed)?api('/api/apps'):Promise.resolve({installed:[]})]);
  layout=normalize(requests[0].status==='fulfilled'?requests[0].value:{},tools.map(t=>'tool:'+t[0]));
  if(requests[0].status==='rejected'){readonly=true;toast('Desktop-Einstellungen konnten nicht geladen werden. Änderungen werden erst nach erneutem Laden gespeichert.',true);}
  function updateApps(data){for(const key of entries.keys())if(key.startsWith('app:'))entries.delete(key);apps=data?.installed||[];for(const app of apps){const key='app:'+app.id;if(!validKey(key))continue;const endpoint=(app.container?.endpoints||app.endpoints||[]).find(e=>e.scope==='lan'&&safeUrl(e.url));const primary=app.container?.state||app.web_state||app.state,running=primary==='running'||app.web_available===true;entries.set(key,{name:app.name||app.id,detail:running?'Im neuen Tab öffnen':app.status||'App ist gestoppt',glyph:'apps',app:app.id,url:running?safeUrl(endpoint?.url):'',state:primary});}}
  if(requests[1].status==='fulfilled')updateApps(requests[1].value);
  if(user.role!=='admin'&&!user.permissions?.apps?.allowed)layout.items=layout.items.flatMap(row=>typeof row==='string'?(row.startsWith('tool:')&&entries.has(row)?[row]:[]):[{...row,items:row.items.filter(key=>key.startsWith('tool:')&&entries.has(key))}]).filter(row=>typeof row==='string'||row.items.length);
  const context=doc.createElement('div');context.className='shortcut-context';context.setAttribute('role','menu');context.hidden=true;doc.body.append(context);
  const folderDialog=doc.createElement('dialog');folderDialog.className='desktop-folder-dialog';folderDialog.setAttribute('aria-label','Desktop-Ordner');doc.body.append(folderDialog);
  surface.setAttribute('tabindex','0');
  const entry=key=>entries.get(key)||{name:key.replace(/^app:/,''),detail:'App nicht verfügbar',glyph:'apps'};
  function image(key){const item=entry(key);return item.app&&win.TitanArtwork?win.TitanArtwork.render(item.app):win.TitanArtwork?.tool(item.glyph)||icon(item.glyph);}
  function card(row){const folder=typeof row==='object',key=idOf(row),item=folder?{name:row.name}:entry(key),tag=item.app&&item.url?'a':'button',link=tag==='a'?` href="${esc(item.url)}" target="_blank" rel="noopener noreferrer" draggable="false"`:'';return `<div class="desktop-shortcut" data-shortcut="${esc(key)}" ${item.app&&pendingApps.has(item.app)?'aria-busy="true"':''}><${tag}${link} class="shortcut-open" data-shortcut-open="${esc(key)}" aria-label="${esc(item.name)}" title="${esc(folder?'Ordner öffnen':item.detail||item.name)}"><span class="${folder?'shortcut-folder-icon':'desktop-app-icon'}" data-app="${esc(item.glyph||'files')}">${folder?row.items.slice(0,4).map(id=>'<span>'+image(id)+'</span>').join(''):image(key)}</span><span class="shortcut-label">${esc(item.name)}</span></${tag}><button class="shortcut-more" data-shortcut-more="${esc(key)}" aria-label="${esc(item.name)}: Verknüpfung bearbeiten" title="Verknüpfung bearbeiten">⋯</button></div>`;}
  let displayed={};
  const mobile=()=>win.innerWidth<=760;
  const positionMap=()=>mobile()?layout.mobile_positions:layout.positions;
  const cell=()=>({small:92,medium:108,large:128}[layout.icon_size]||108);
  function position(){if(!alive)return;surface.dataset.iconSize=layout.icon_size;const size=cell(),cols=Math.max(1,Math.floor(surface.clientWidth/size)),rows=Math.max(1,Math.floor(surface.clientHeight/size));displayed=place(layout.items,positionMap(),cols,rows,mobile());surface.querySelectorAll('[data-shortcut]').forEach(node=>{const p=displayed[node.dataset.shortcut];node.style.left=p.x*size+'px';node.style.top=p.y*size+'px';});}
  function render(){if(!alive)return;const focused=surface.contains(doc.activeElement)?doc.activeElement:null,focusKey=focused?.closest('[data-shortcut]')?.dataset.shortcut,more=focused?.hasAttribute('data-shortcut-more');surface.innerHTML=layout.items.map(card).join('')+`<div class="desktop-save-state" role="status">${readonly?'Einstellungen nicht geladen':failed?'Änderungen noch nicht gespeichert':''}${failed?'<button type="button" data-desktop-retry>Erneut speichern</button>':''}</div><span class="desktop-watermark">Titan</span>`;position();if(opened)renderFolder();if(focusKey)surface.querySelector(`[data-shortcut-${more?'more':'open'}="${focusKey}"]`)?.focus({preventScroll:true});}
  async function persist(){if(readonly)return;if(saving)return;saving=true;let savedRevision;try{do{savedRevision=revision;const value=JSON.parse(JSON.stringify(layout));await api('/api/launcher-layout',value);}while(alive&&savedRevision!==revision);failed=false;}catch(error){failed=true;if(alive)toast(error.message||'Desktop konnte nicht gespeichert werden.',true);}finally{saving=false;if(alive){const status=surface.querySelector('.desktop-save-state');if(status)status.innerHTML=failed?'Änderungen noch nicht gespeichert <button type="button" data-desktop-retry>Erneut speichern</button>':'';}}}
  function change(){const roots=new Set(layout.items.map(idOf));for(const map of [layout.positions,layout.mobile_positions])for(const key of Object.keys(map))if(!roots.has(key))delete map[key];revision++;render();void persist();}
  function add(key){if(readonly||!entries.has(key)||has(layout.items,key))return false;layout.items.push(key);change();return true;}
  function erase(key){if(readonly)return;layout.items=remove(layout.items,key);delete layout.positions[key];delete layout.mobile_positions[key];change();}
  function renderFolder(){const folder=layout.items.find(row=>row.id===opened);if(!folder){folderDialog.close();opened=null;return;}folderDialog.innerHTML=`<header><h2>${esc(folder.name)}</h2><button type="button" class="button" data-folder-close>Schließen</button></header><div class="folder-shortcuts">${folder.items.map(card).join('')||'<p>Dieser Ordner ist leer. Ziehe eine Verknüpfung auf ihn.</p>'}</div><form data-folder-name><label>Ordnername<input name="name" value="${esc(folder.name)}" maxlength="40" required></label><button class="button" type="submit">Umbenennen</button></form>`;}
  function openItem(key){if(Date.now()<blockClick)return;const folder=layout.items.find(row=>row.id===key);if(folder){opened=key;renderFolder();folderDialog.showModal();return;}const item=entry(key);if(item.app){if(item.url)win.open(item.url,'_blank','noopener,noreferrer');else toast(item.state==='running'?'Diese App hat keinen erreichbaren Webzugang. Öffne ihre Verwaltung.':'Die App ist gestoppt oder nicht verfügbar. Öffne ihre Verwaltung.',true);}else if(item.href)open(item.href);}
  function showContext(key,x,y){contextKey=key;(folderDialog.open?folderDialog:doc.body).append(context);const folder=layout.items.find(row=>row.id===key),item=key?entry(key):null;context.innerHTML=key?`<button role="menuitem" data-context="open">Öffnen</button>${item?.app?`<button role="menuitem" data-context="manage">App verwalten</button><button role="menuitem" data-context="app-${item.state==='running'?'stop':'start'}" ${pendingApps.has(item.app)?'disabled':''}>${item.state==='running'?'App stoppen':'App starten'}</button><button role="menuitem" data-context="app-remove" class="danger" ${pendingApps.has(item.app)?'disabled':''}>App deinstallieren</button>`:''}${folder?'<button role="menuitem" data-context="rename">Ordner umbenennen</button><button role="menuitem" data-context="dissolve">Ordner auflösen</button>':`<button role="menuitem" data-context="move">Auf Desktop verschieben</button>${layout.items.filter(row=>typeof row==='object'&&row.id!==opened).map(row=>`<button role="menuitem" data-context="into" data-folder-target="${esc(row.id)}">In Ordner: ${esc(row.name)}</button>`).join('')}<button role="menuitem" data-context="remove">Vom Desktop entfernen</button>`}`:'<button role="menuitem" data-context="add">Verknüpfung hinzufügen</button><button role="menuitem" data-context="folder">Neuer Ordner</button><button role="menuitem" data-context="appearance">Hintergrund ändern</button>'+['small','medium','large'].map((size,index)=>`<button role="menuitemradio" aria-checked="${layout.icon_size===size}" data-context="size" data-icon-size="${size}">Symbole: ${['Klein','Mittel','Groß'][index]}</button>`).join('');
   context.hidden=false;context.style.left=Math.max(8,Math.min(x,win.innerWidth-240))+'px';context.style.top=Math.max(8,Math.min(y,win.innerHeight-context.offsetHeight-8))+'px';context.querySelector('button')?.focus();}
  async function click(event){const button=event.target.closest('button');if(!button)return;const key=button.dataset.shortcutOpen;if(key){openItem(key);return;}if(button.dataset.shortcutMore){const r=button.getBoundingClientRect();showContext(button.dataset.shortcutMore,r.left,r.bottom);return;}if(button.hasAttribute('data-desktop-retry'))void persist();if(button.hasAttribute('data-folder-close'))folderDialog.close();const cmd=button.dataset.context;if(!cmd)return;context.hidden=true;if(cmd==='size'){if(readonly)return;layout.icon_size=button.dataset.iconSize;change();return;}if(cmd.startsWith('app-')){await appCommand(contextKey,cmd.slice(4));return;}if(['add','appearance'].includes(cmd)){menu();return;}if(cmd==='open'||cmd==='rename'){openItem(contextKey);return;}if(cmd==='manage'){if(folderDialog.open)folderDialog.close();open('#docker?app='+encodeURIComponent(entry(contextKey).app));return;}if(readonly)return;if(cmd==='remove')erase(contextKey);if(cmd==='into'){layout.items=group(layout.items,contextKey,button.dataset.folderTarget);delete layout.positions[contextKey];change();}if(cmd==='move'){layout.items=remove(layout.items,contextKey);layout.items.push(contextKey);change();}if(cmd==='folder'){const folder={id:'folder-'+Date.now().toString(36),name:'Neuer Ordner',items:[]};layout.items.push(folder);opened=folder.id;change();folderDialog.showModal();}if(cmd==='dissolve'){const folder=layout.items.find(row=>row.id===contextKey);layout.items=layout.items.flatMap(row=>row===folder?folder.items:[row]);delete layout.positions[contextKey];change();}}
  async function appCommand(key,command){const item=entry(key);if(!item.app||pendingApps.has(item.app)||!action)return;if(command==='remove'&&!await confirm('Diese App stoppen und deinstallieren? Konfiguration und Nutzdaten bleiben erhalten.'))return;if(folderDialog.open)folderDialog.close();pendingApps.set(item.app,true);render();toast(command==='remove'?'App wird deinstalliert …':command==='stop'?'App wird gestoppt …':'App wird gestartet …');try{await action('app_action',{app:item.app,action:command},{wait:true,signal:actionController.signal});if(!alive)return;if(command==='remove')erase(key);updateApps(await api('/api/apps'));render();toast(command==='remove'?'App deinstalliert. Deine Daten bleiben erhalten.':command==='stop'?'App gestoppt.':'App gestartet.');}catch(error){if(alive&&error.name!=='AbortError')toast(error.message,true);}finally{pendingApps.delete(item.app);if(alive)render();}}
  function contextmenu(event){if(!surface.contains(event.target)&&!folderDialog.contains(event.target))return;event.preventDefault();showContext(event.target.closest('[data-shortcut]')?.dataset.shortcut||null,event.clientX,event.clientY);}
  function outside(event){if(!context.hidden&&!context.contains(event.target)&&!event.target.closest('[data-shortcut-more]'))context.hidden=true;}
  function down(event){if(readonly||event.button!==0||event.target.closest('[data-shortcut-more]'))return;const node=event.target.closest('[data-shortcut]');if(!node||!surface.contains(node))return;gesture={key:node.dataset.shortcut,x:event.clientX,y:event.clientY,id:event.pointerId,node,dragging:false,group:null,groupAt:0};}
  function move(event){if(!gesture||gesture.id!==event.pointerId)return;const g=gesture;if(!g.dragging&&Math.hypot(event.clientX-g.x,event.clientY-g.y)<7)return;event.preventDefault();if(!g.dragging){g.dragging=true;g.preview=doc.createElement('div');g.preview.className='desktop-drop-preview';g.preview.setAttribute('aria-hidden','true');surface.append(g.preview);g.node.classList.add('shortcut-dragging');surface.setPointerCapture?.(event.pointerId);}
   g.node.style.transform=`translate3d(${event.clientX-g.x}px,${event.clientY-g.y}px,0)`;const area=surface.getBoundingClientRect(),cols=Math.max(1,Math.floor(surface.clientWidth/cell())),rows=Math.max(1,Math.floor(surface.clientHeight/cell()));g.preview.style.left=Math.max(0,Math.min(cols-1,Math.floor((event.clientX-area.left+surface.scrollLeft)/cell())))*cell()+'px';g.preview.style.top=Math.max(0,Math.min(rows-1,Math.floor((event.clientY-area.top+surface.scrollTop)/cell())))*cell()+'px';
   g.node.style.pointerEvents='none';const target=doc.elementFromPoint(event.clientX,event.clientY)?.closest('[data-shortcut]');g.node.style.pointerEvents='';let groupKey=null;if(target&&target!==g.node&&validKey(g.key)){const r=target.getBoundingClientRect();if(event.clientX>r.left+r.width*.2&&event.clientX<r.right-r.width*.2&&event.clientY>r.top+8&&event.clientY<r.bottom-15)groupKey=target.dataset.shortcut;}
   if(g.group!==groupKey){surface.querySelectorAll('.shortcut-group-target').forEach(n=>n.classList.remove('shortcut-group-target'));g.group=groupKey;g.groupAt=Date.now();}
   if(groupKey&&Date.now()-g.groupAt>=500)target.classList.add('shortcut-group-target');}
  function end(event){if(!gesture||gesture.id!==event.pointerId)return;const g=gesture;gesture=null;g.preview?.remove();if(!g.dragging)return;blockClick=Date.now()+400;if(event.type==='pointercancel'){render();return;}if(g.group&&Date.now()-g.groupAt>=500){const next=group(layout.items,g.key,g.group);const old=displayed[g.group];layout.items=next;const folder=next.find(row=>typeof row==='object'&&row.items.includes(g.key));if(folder&&old)positionMap()[folder.id]=old;delete layout.positions[g.key];}else{const r=surface.getBoundingClientRect(),cols=Math.max(1,Math.floor(surface.clientWidth/cell())),rows=Math.max(1,Math.floor(surface.clientHeight/cell()));const target={x:Math.max(0,Math.min(cols-1,Math.floor((event.clientX-r.left+surface.scrollLeft)/cell()))),y:Math.max(0,Math.min(rows-1,Math.floor((event.clientY-r.top+surface.scrollTop)/cell())))};const other=Object.keys(displayed).find(key=>key!==g.key&&displayed[key].x===target.x&&displayed[key].y===target.y);if(other)positionMap()[other]=displayed[g.key];positionMap()[g.key]=target;}change();}
  function keydown(event){if(event.key==='Escape'){context.hidden=true;return;}const node=event.target.closest('[data-shortcut]');if(node&&event.key==='Delete'){event.preventDefault();erase(node.dataset.shortcut);}if(node&&(event.key==='ContextMenu'||event.shiftKey&&event.key==='F10')){event.preventDefault();const r=node.getBoundingClientRect();showContext(node.dataset.shortcut,r.left,r.bottom);}if(node&&event.altKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)&&!readonly){event.preventDefault();const key=node.dataset.shortcut,p=displayed[key];positionMap()[key]={x:Math.max(0,Math.min(31,p.x+(event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:0))),y:Math.max(0,Math.min(127,p.y+(event.key==='ArrowDown'?1:event.key==='ArrowUp'?-1:0)))};change();surface.querySelector(`[data-shortcut-open="${key}"]`)?.focus();}}
  function submit(event){if(!event.target.matches('[data-folder-name]'))return;event.preventDefault();if(readonly)return;const name=event.target.elements.name.value.trim();if(!name)return;layout.items.find(row=>row.id===opened).name=name;change();}
  const preventDrag=event=>event.preventDefault();
  const listeners=[[surface,'dragstart',preventDrag],[surface,'click',click],[folderDialog,'click',click],[context,'click',click],[folderDialog,'submit',submit],[doc,'contextmenu',contextmenu],[doc,'pointerdown',outside],[surface,'pointerdown',down],[doc,'pointermove',move],[doc,'pointerup',end],[doc,'pointercancel',end],[doc,'keydown',keydown]];
  listeners.forEach(([node,event,fn])=>node.addEventListener(event,fn));folderDialog.addEventListener('close',()=>{opened=null;context.hidden=true;doc.body.append(context);});const observer=new win.ResizeObserver(position);observer.observe(surface);render();
  const liveTimer=setInterval(()=>{if(alive&&!gesture&&!doc.hidden&&context.hidden&&!pendingApps.size)void refreshApps();},15000);
  async function refreshApps(){if(user.role!=='admin'&&!user.permissions?.apps?.allowed)return;try{const result=await api('/api/apps');if(alive){updateApps(result);if(!gesture&&!folderDialog.open&&context.hidden)render();}}catch{}}
  return {add,contains:key=>has(layout.items,key),entries:()=>[...entries.entries()],open:openItem,refreshApps,widgets:()=>layout.widgets,setWidgets:value=>{layout.widgets=value;change();},destroy(){alive=false;actionController.abort();clearInterval(liveTimer);gesture?.preview?.remove();observer.disconnect();listeners.forEach(([node,event,fn])=>node.removeEventListener(event,fn));context.remove();folderDialog.remove();}};
 }
 return {normalize,place,remove,group,safeUrl,mount};
});
