'use strict';
(function(root,factory){const api=factory(root);if(root)root.TitanDockerEditor=api;if(typeof module==='object'&&module.exports)module.exports=api;})(typeof window==='undefined'?null:window,function(root){
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const field=(label,key,value,min)=>`<label class="field">${esc(label)}<input name="${key}" type="number" value="${Number(value)}" min="${min}" required></label>`;
 const choice=(label,key,values,value)=>`<label class="field">${esc(label)}<select name="${key}">${values.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
 const end='<div class="form-actions"><button type="button" class="button" data-action="close">Abbrechen</button><button type="submit" class="button primary">Einstellungen speichern</button></div>';
 function manualFields(settings,networks=[]){
  const modes=[['bridge','Bridge · Standard'],['host','Host · NAS-Netz'],['none','Ohne Netzwerk'],...networks.filter(row=>!['bridge','host','none'].includes(row.Name)).map(row=>[row.Name,row.Name])];
  if(!modes.some(([id])=>id===settings.network))modes.push([settings.network,settings.network+' · aktuell']);
  return `<form><p class="notice">Der Container muss gestoppt sein. Titan erstellt eine Kopie mit deinen Einstellungen und startet sie. Der bisherige Container bleibt als gestoppte Sicherung erhalten; Daten und Gerätezuordnung bleiben erhalten.</p><div class="form-grid">${choice('Netzwerk','network',modes,settings.network)}${choice('Automatisch neu starten','restart',[['unless-stopped','Sofern nicht manuell gestoppt'],['always','Immer'],['on-failure','Bei Fehler'],['no','Nicht automatisch']],settings.restart)}${field('RAM-Limit (MiB)','memory_mb',settings.memory_mb,64)}${field('CPU-Limit','cpus',settings.cpus,1)}</div><label class="field">Ports · eine Zuordnung je Zeile<textarea name="ports" rows="4" placeholder="8080:80/tcp" spellcheck="false">${esc((settings.ports||[]).map(port=>`${port.published}:${port.target}/${port.protocol}`).join('\n'))}</textarea></label><p class="hint">Bei Host/Ohne Netzwerk das Portfeld leer lassen. NAS-Ports ab 1024 sind verfügbar; Titan prüft reservierte und bereits belegte Ports.</p><label class="field">Umgebung · NAME=Wert je Zeile<textarea name="environment" rows="6" autocomplete="off" spellcheck="false">${esc(Object.entries(settings.environment||{}).map(([key,value])=>key+'='+value).join('\n'))}</textarea></label><p class="hint">Werte ersetzen oder ergänzen. Mit NAME= einen Wert leeren. Bestehende Variablen bleiben erhalten, wenn du sie nicht angibst. Geheime Variablen werden hier nicht angezeigt und bleiben erhalten.</p>${settings.preserved_secret_keys?.length?`<p class="hint">Geschützte Variablen: ${settings.preserved_secret_keys.map(esc).join(', ')}.</p>`:''}${end}</form>`;
 }
 function manualArguments(data,parsers){return {network:String(data.get('network')),restart:String(data.get('restart')),memory_mb:Number(data.get('memory_mb')),cpus:Number(data.get('cpus')),ports:parsers.parsePorts(data.get('ports')),environment:parsers.parseEnv(data.get('environment'))};}
 async function manual(id,{api,action,dialog,networks=[],parsePorts,parseEnv}){
  const data=await api('/api/docker-container?container='+encodeURIComponent(id));
  if(!data.settings)throw Error(data.settings_unavailable||'Container zuerst stoppen. Diese Einstellungen sind nur für eigene Titan-Container verfügbar.');
  dialog('Container-Einstellungen',manualFields(data.settings,networks),form=>action('docker_container_settings',{container:id,settings:manualArguments(form,{parsePorts,parseEnv})},{wait:true}));
 }
 function editableRecipe(recipe,settings){return {...recipe,install_schema:(settings||[]).filter(field=>field.editable!==false&&field.type!=='password').map(field=>({...field,default:field.value??field.default,display_default:field.value??field.display_default,enabled_by_default:field.optional===true?field.type==='boolean'?field.value===true:field.value!==null&&field.value!==undefined:field.enabled_by_default}))};}
 function templateArguments(id,recipe,data){return {app:id,port:Number(data.get('port')),options:root.TitanTemplateFields.argumentsFor(recipe,data),...(Number(recipe.containers||1)===1?{network:root.TitanNetworks?.installArguments(recipe,data).network||{mode:'default'}}:{})};}
 async function template(id,{api,action,dialog,catalogApp,dialogBody,toast}){
  const [data,recipe,networks]=await Promise.all([api('/api/app-details?'+new URLSearchParams({app:id,tail:'1'})),catalogApp(id),api('/api/app-networks')]);
  if(!recipe.docker_template)throw Error('Diese Einstellungen sind nur für Docker-Vorlagen verfügbar.');
  if(['running','paused','restarting'].includes(data.app.state)||(data.services||[]).some(service=>['running','paused','restarting'].includes(service.state)))throw Error('Alle Dienste dieses App-Pakets zuerst stoppen.');
  const editable=editableRecipe(recipe,data.settings),network=data.app.network||{mode:'default'};
  editable.default_network=network.name?'network:'+network.name:network.mode||'default';
  dialog(recipe.name+' · Einstellungen',`<form><p class="notice">Alle Dienste müssen gestoppt sein. Beim Speichern legt Titan sie mit den neuen Einstellungen erneut an. Nutzdaten und gespeicherte Geheimnisse bleiben erhalten. Danach kannst du das Paket starten.</p><label class="field">Port für die Weboberfläche<input name="port" type="number" value="${Number(data.app.port)}" min="${recipe.docker_template||network.mode==='host'?1:1024}" max="65535" required></label>${root.TitanTemplateFields.fields(editable)}${root.TitanTemplateFields.summary(recipe)}${Number(recipe.containers||1)===1?root.TitanNetworks?.installFields(editable,networks)||'':'<p class="hint">Dieses Paket verbindet seine Dienste automatisch in einem eigenen internen Netzwerk.</p>'}<p class="hint">Passwörter und interne Verbindungen bleiben erhalten. Die Vorlage und ihre Dokumentation geben an, ob weitere Einrichtung in der App erforderlich ist.</p>${end}</form>`,async form=>{const result=await action('app_settings',templateArguments(id,editable,form),{wait:true});toast?.(result.message||'Einstellungen gespeichert. Das Paket bleibt gestoppt.');return result;});
  const body=dialogBody();
  if(Number(recipe.containers||1)===1&&root.TitanNetworks){root.TitanNetworks.mountInstall(body,editable,networks,{api});const input=body.querySelector('[data-network-ip]');if(input)input.value=network.ipv4_address||'';}
  root.TitanTemplateFields.bind(body,{app:editable});
 }
 return {manual,manualFields,manualArguments,template,templateArguments,editableRecipe};
});
