'use strict';
(function(root){let current=null,selectView=null;
 const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function ports(value){return Object.entries(value||{}).map(([target,bindings])=>bindings?.map(b=>`${b.HostIp||'NAS'}:${b.HostPort} → ${target}`).join(' · ')||target+' intern').join(' · ');}
 function parsePorts(text){return String(text).split(/\r?\n/).map(v=>v.trim()).filter(Boolean).map(v=>{const m=v.match(/^(\d{1,5}):(\d{1,5})(?:\/(tcp|udp))?$/);if(!m)throw Error('Ports zeilenweise als 8080:80/tcp eingeben.');return {published:Number(m[1]),target:Number(m[2]),protocol:m[3]||'tcp'};});}
 function parseEnv(text){const result={};for(const row of String(text).split(/\r?\n/).filter(v=>v.trim())){const i=row.indexOf('=');if(i<1||!/^[A-Za-z_][A-Za-z0-9_]{0,63}$/.test(row.slice(0,i)))throw Error('Umgebung zeilenweise als NAME=Wert eingeben.');const key=row.slice(0,i);if(Object.hasOwn(result,key))throw Error('Umgebungsvariable doppelt: '+key);Object.defineProperty(result,key,{value:row.slice(i+1),enumerable:true,writable:true,configurable:true});}return result;}
 const valid=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
 function metric(m,bytes){return `<span>CPU <strong>${valid(m?.cpu_percent)?m.cpu_percent.toLocaleString('de-DE',{maximumFractionDigits:1})+' %':'—'}</strong></span><span>RAM gesamt <strong>${valid(m?.memory_bytes)?safe(bytes(m.memory_bytes)):'—'}</strong></span>`;}
 function filtered(rows,query='',state='all',sort='az'){return rows.filter(c=>(state==='all'||(state==='running'?['running','paused'].includes(c.state):state==='stopped'? !['running','paused'].includes(c.state):c.health==='unhealthy'))&&[c.name,c.image,c.project,...(c.networks||[]).map(n=>n.name)].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='az'?a.name.localeCompare(b.name,'de'):sort==='za'?b.name.localeCompare(a.name,'de'):String(b.created).localeCompare(String(a.created)));}
 function stacks(rows){const groups=new Map();for(const row of rows){const key=row.project;if(!key)continue;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}return [...groups].sort((a,b)=>a[0].localeCompare(b[0],'de'));}
 function totals(rows,metrics){let memory=0,unknown=false;for(const row of rows){if(!['running','paused'].includes(row.state))continue;const value=metrics[row.id]?.memory_bytes;if(valid(value))memory+=value;else unknown=true;}return {total:rows.length,running:rows.filter(c=>c.state==='running').length,stopped:rows.filter(c=>!['running','paused'].includes(c.state)).length,unhealthy:rows.filter(c=>c.health==='unhealthy').length,memory:unknown?null:memory};}
 function urlHost(hostname){const bare=String(hostname).replace(/^\[([^\]]+)\]$/,'$1');return bare.includes(':')?'['+bare+']':bare;}
 function webLink(c,hostname){if(c.state!=='running')return '';const host=urlHost(hostname);const url=(target,port)=>(c.scheme==='https'||target==='443/tcp'?'https':'http')+'://'+host+':'+port;const web=Number(c.web_port);if(c.managed_app&&(!Number.isInteger(web)||web<1||web>65535))return '';if(c.managed_app&&c.network_mode==='host'&&Number.isInteger(web)&&web>=1&&web<=65535)return url(web+'/tcp',web);const entries=Object.entries(c.ports||{}).filter(([target])=>!c.web_port||target===web+'/tcp');for(const [target,bindings]of entries){if(!target.endsWith('/tcp'))continue;const b=(bindings||[]).find(b=>!['127.0.0.1','::1'].includes(b.HostIp));const port=Number(b?.HostPort);if(Number.isInteger(port)&&port>=1&&port<=65535)return url(target,port);}return '';}
 const icons={overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',stacks:'m3 7 9-4 9 4-9 4zM3 12l9 4 9-4M3 17l9 4 9-4',containers:'M4 4h16v16H4zM4 10h16M10 10v10M15 4v6',images:'M4 3h16v18H4zM7 16l4-5 3 3 2-2 3 5M8 7h1',networks:'M8 3h8v5H8zM12 8v5M5 13h14M5 13v3M19 13v3M2 16h6v5H2zM16 16h6v5h-6z',volumes:'M4 5h16v14H4zM4 14h16M16 17h1',templates:'M4 4h7v7H4zM14 4h7v7h-7zM4 14h7v7H4zM14 14h7v7h-7z'};
 const icon=id=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[id]||icons.containers}"/></svg>`;
 function dispose(){current?.();current=null;selectView=null;}
 function containerStorageConfig(value){if(!value)return {};if(value.startsWith('@docker-volume:'))return {volume:value.slice(15)};if(/^(system|(?:volume|pool):[a-z][a-z0-9_-]{0,30})$/.test(value))return {storage_id:value};throw Error('Wähle einen gültigen Speicherbereich.');}
 async function mount(container,{api,action,dialog,askYesNo,toast,bytes,installTemplate,role}){dispose();if(!container)return;let alive=true,busy=false,data={containers:[],images:[],volumes:[],networks:[]},networkData={available:true,networks:[]},networkId=null,view=typeof URLSearchParams!=='undefined'&&new URLSearchParams((location.hash||'').split('?')[1]||'').get('section')==='templates'?'templates':'overview',query='',sort='az',state='all',metrics={},refreshing=false,selected=new Set(),detailId=null,objectJobs=new Map(),closedGroups=new Set(),lastResult=null,templateBrowser=null;const templateState={},isAdmin=role==='admin';
  const button=(label,op,id='',kind='')=>`<button type="button" class="button small ${kind}" data-engine-action="${op}" data-engine-id="${safe(id)}" ${busy||(data.available===false&&op!=='refresh')?'disabled':''}>${label}</button>`;
  const status=c=>`<span class="pill ${c.health==='unhealthy'?'red':c.state==='running'?'':'gray'}">${safe(c.state==='running'?'Läuft':c.state==='exited'?'Gestoppt':c.state==='paused'?'Pausiert':c.state)}${c.health?' · '+safe(c.health):''}</span>`;
  const backup=c=>c.manual&&String(c.name).startsWith('titan-previous-');
  const resource=c=>['running','paused'].includes(c.state)?metrics[c.id]:{cpu_percent:0,memory_bytes:0};
  const controls=(c,showDetails=true)=>`${backup(c)?'':button(['running','paused'].includes(c.state)?'Stoppen':'Starten',['running','paused'].includes(c.state)?'stop':'start',c.id)}${!backup(c)&&['running','paused'].includes(c.state)?button('Neustarten','restart',c.id):''}${showDetails?button('Details','select',c.id):''}${button('Entfernen','remove',c.id,'danger')}`;
  const progress=id=>{const job=objectJobs.get(id);return job?`<div class="engine-object-status ${job.status==='failed'?'is-error':job.status==='completed'?'is-complete':''}" role="status" data-engine-object-status="${safe(id)}">${safe(job.message||jobLabel(job))}</div>`:'';};
  const jobLabel=job=>job.status==='queued'?'Aktion wartet …':job.status==='running'?'Aktion wird ausgeführt …':job.status==='failed'?'Aktion fehlgeschlagen.':'Aktion abgeschlossen.';
  const resultStatus=result=>{const failures=result?.failed||[];return failures.length?`${(result.completed||[]).length} erfolgreich; ${failures.map(row=>(data.containers.find(c=>c.id===row.container)?.name||row.container)+': '+row.error).join(' · ')}`:result?.message||'Aktion erfolgreich abgeschlossen.';};
  const runningJob=(ids,job)=>{for(const id of ids)objectJobs.set(id,{status:job.status,message:job.result?.error||job.result?.message||jobLabel(job)});render();};
  async function execute(operation,args,ids=[]){
   busy=true;lastResult=null;for(const id of ids)objectJobs.set(id,{status:'queued',message:'Aktion wartet …'});render();
   try{const result=await action(operation,args,{wait:true,onProgress:job=>{if(alive)runningJob(ids,job);}});if(!alive)return result;
    for(const id of ids){const failed=(result.failed||[]).find(row=>row.container===id);objectJobs.set(id,{status:failed?'failed':'completed',message:failed?.error||result.message||'Aktion abgeschlossen.'});}
    lastResult={status:result.ok===false||result.failed?.length?'failed':'completed',message:resultStatus(result)};await refresh(true);return result;
   }catch(error){if(alive){const partial=error.result;for(const id of ids){const failed=partial?.failed?.find(row=>row.container===id),completed=partial?.completed?.includes(id);objectJobs.set(id,{status:completed?'completed':'failed',message:completed?'Aktion abgeschlossen.':failed?.error||error.message});}lastResult={status:'failed',message:partial?.failed?.length?resultStatus(partial):error.message};await refresh(true);}throw error;
   }finally{busy=false;if(alive)render();}
  }
  const selection=c=>`<input type="checkbox" data-engine-select="${safe(c.id)}" aria-label="${safe(c.name)} auswählen" ${backup(c)?'disabled title="Gestoppte Sicherung"':''} ${selected.has(c.id)?'checked':''}>`;
  function summary(){const counts=totals(data.containers||[],metrics);return [['Container',counts.total],['Läuft',counts.running],['Gestoppt',counts.stopped],['Fehlerhaft',counts.unhealthy],['RAM gesamt',valid(counts.memory)?bytes(counts.memory):'—']].map(([label,value])=>`<article><small>${label}</small><strong>${safe(value)}</strong></article>`).join('');}
  const appLink=c=>webLink(c,location.hostname);
  const artwork=c=>window.TitanArtwork?.render(c.managed_app,c.image)||'';
  let inspectorLogs='',inspectorCommand='',inspectorCommandOutput='',inspectorCommandStatus='',inspectorCommandFailed=false;
  function drawer(){const c=data.containers.find(c=>c.id===detailId);if(!c)return '';const link=appLink(c);return `<aside class="engine-inspector" aria-label="Containerdetails"><div class="engine-inspector-header"><div class="engine-container-heading">${artwork(c)}<h3>${safe(c.name)}</h3></div>${button('Zurück','drawer-close')}</div><div class="engine-inspector-scroll">${status(c)}<p class="hint">${safe(c.image)}</p><p class="engine-scope-label">Einzelner Dienst${c.managed_app?' · Teil eines Titan-App-Pakets':''}</p>${backup(c)?'<p class="notice">Gestoppte Sicherung eines früheren Containers. Sie bewahrt den Zustand vor einer Änderung; dein aktueller Container läuft separat. Entfernen löscht nur die Sicherung, keine gespeicherten Daten.</p>':''}<div class="app-live-grid" data-engine-metric="${safe(c.id)}">${metric(resource(c),bytes)}</div>${progress(c.id)}<div class="engine-inspector-actions">${link?`<a class="button primary" href="${safe(link)}" target="_blank" rel="noopener">App öffnen ↗</a>`:''}${controls(c,false)}${c.managed_app?`<button class="button" data-action="app-manage" data-id="${safe(c.managed_app)}">Gesamtes App-Paket verwalten</button>`:c.manual&&!backup(c)?(isAdmin?button('Einstellungen','settings',c.id):'')+button('Geräte bearbeiten','hardware',c.id):''}</div><dl class="engine-details"><dt>Netzwerk</dt><dd>${safe((c.networks||[]).map(n=>n.name+' · '+(n.ipv4||n.ipv6||'—')).join(' / ')||'—')}</dd><dt>Ports</dt><dd>${safe(ports(c.ports)||'—')}</dd></dl>${isAdmin&&!backup(c)&&['running'].includes(c.state)&&(c.manual||c.managed_app)?`<section class="engine-console"><h3>Befehlskonsole</h3><p class="hint">Befehle im Container ausführen · bis 30 Sekunden. Das Image benötigt eine Shell und das Werkzeug timeout.</p><form data-engine-command-form data-engine-container="${safe(c.id)}"><label class="field">Befehl<input name="command" data-engine-command value="${safe(inspectorCommand)}" maxlength="4096" placeholder="z. B. ls -la /data" autocomplete="off" spellcheck="false" required ${busy?'disabled':''}></label><button type="submit" class="button small primary" ${busy?'disabled':''}>Ausführen</button></form><p class="hint ${inspectorCommandFailed?'is-error':''}" role="status">${safe(inspectorCommandStatus)}</p>${inspectorCommandOutput?`<pre class="engine-log" tabindex="0" aria-label="Befehlsausgabe">${safe(inspectorCommandOutput)}</pre>`:''}</section>`:''}<h3>Protokoll</h3>${button('Logs laden','logs',c.id)}<pre class="engine-log" tabindex="0">${safe(inspectorLogs||'Logs laden, um die letzten Meldungen anzuzeigen.')}</pre></div></aside>`;}
  function serviceRow(c){return `<article class="engine-service-row" data-engine-row="${safe(c.id)}"><div class="engine-service-name">${selection(c)}<button class="engine-name" data-engine-action="select" data-engine-id="${safe(c.id)}">${artwork(c)}<span><strong>${safe(c.service||c.name)}</strong><small>${safe(c.image)}</small></span></button></div>${status(c)}<div class="engine-resource-metric" data-engine-metric="${safe(c.id)}">${metric(resource(c),bytes)}</div><div class="engine-service-network"><small>${safe((c.networks||[]).map(n=>n.ipv4||n.ipv6||n.name).join(' · ')||'Kein Netzwerk')}</small><small>${safe(ports(c.ports)||'Keine veröffentlichten Ports')}</small></div><div class="engine-actions">${backup(c)?'<span class="hint">Sicherung</span>':button(['running','paused'].includes(c.state)?'Stoppen':'Starten',['running','paused'].includes(c.state)?'stop':'start',c.id)}${button('Details','select',c.id)}</div>${progress(c.id)}</article>`;}
  function render(){if(!alive)return;
   window.TitanNetworks?.disposeWithin(container);templateBrowser?.destroy();templateBrowser=null;
   const scrolls=[...container.querySelectorAll('.engine-content,.engine-inspector-scroll')].map(node=>({className:node.className,top:node.scrollTop}));
   const active=container.ownerDocument.activeElement,focusKey=container.contains(active)?active?.matches?.('[data-engine-search]')?'search':active?.matches?.('[data-engine-state]')?'state':active?.matches?.('[data-engine-sort]')?'sort':active?.matches?.('[data-engine-select]')?'select':null:null,focusId=active?.dataset?.engineSelect,position=active?.selectionStart;

   const rows=filtered(data.containers||[],view==='overview'?'':query,view==='overview'?'all':state,sort);
   const groups=stacks(data.containers||[]);const tabs=[['overview','Übersicht'],['stacks','Projekte'],['containers','Container'],['images','Images'],['networks','Netzwerke'],['volumes','Volumes'],['templates','Vorlagen']];
   let content='';
   if(view==='overview')content=`<section class="engine-overview"><div class="engine-overview-heading"><h2>Container Manager</h2><p>Apps, ihre Dienste und Verbindungen verwalten.</p></div><div class="engine-summary" data-engine-summary>${summary()}</div><div class="engine-overview-links"><button type="button" data-engine-tab="stacks">${icon('stacks')}<span><strong>Projekte</strong><small>${groups.length} gruppierte App-Pakete und Stacks</small></span><span aria-hidden="true">›</span></button><button type="button" data-engine-tab="networks">${icon('networks')}<span><strong>Netzwerke</strong><small>Eigene Verbindungen erstellen und verwalten</small></span><span aria-hidden="true">›</span></button><button type="button" data-engine-tab="templates">${icon('templates')}<span><strong>Docker-Vorlagen</strong><small>Vorausgefüllte Container und Stacks einrichten</small></span><span aria-hidden="true">›</span></button></div><h3>Containerstatus</h3><div class="engine-flat-list">${rows.slice(0,8).map(serviceRow).join('')||'<div class="engine-empty-state">'+icon('containers')+'<strong>Noch keine Container</strong><p>Installiere ein App-Paket oder erstelle einen eigenen Container.</p><button type="button" class="button primary" data-engine-tab="templates">Vorlagen öffnen</button></div>'}</div>${rows.length>8?'<button class="button small" data-engine-tab="containers">Alle Container anzeigen</button>':''}</section>`;
   if(view==='containers')content=`<div class="engine-filter"><input type="search" data-engine-search placeholder="Container suchen" aria-label="Container suchen" value="${safe(query)}"><select data-engine-state aria-label="Containerstatus filtern">${[['all','Alle Status'],['running','Aktiv'],['stopped','Gestoppt'],['unhealthy','Fehlerhaft']].map(([id,label])=>`<option value="${id}" ${state===id?'selected':''}>${label}</option>`).join('')}</select><select data-engine-sort aria-label="Container sortieren"><option value="az" ${sort==='az'?'selected':''}>Name A–Z</option><option value="za" ${sort==='za'?'selected':''}>Name Z–A</option><option value="new" ${sort==='new'?'selected':''}>Neueste zuerst</option></select></div>${selected.size?`<div class="engine-batch"><span>${selected.size} Dienste ausgewählt</span>${button('Starten','batch-start')}${button('Stoppen','batch-stop')}${button('Neustarten','batch-restart')}${button('Auswahl aufheben','clear')}</div>`:''}<div class="engine-flat-list">${rows.map(serviceRow).join('')||'<p class="empty">Keine passenden Container.</p>'}</div>`;
   if(view==='stacks'){
    const groups=stacks(rows).sort((a,b)=>(sort==='za'?-1:1)*a[0].localeCompare(b[0],'de')),singles=rows.filter(c=>!c.project);
    content=`<div class="engine-filter"><input type="search" data-engine-search placeholder="App, Stack oder Dienst suchen" aria-label="Container suchen" value="${safe(query)}"><select data-engine-state aria-label="Containerstatus filtern">${[['all','Alle Status'],['running','Aktiv'],['stopped','Gestoppt'],['unhealthy','Fehlerhaft']].map(([id,label])=>`<option value="${id}" ${state===id?'selected':''}>${label}</option>`).join('')}</select><select data-engine-sort aria-label="Container sortieren"><option value="az" ${sort==='az'?'selected':''}>Name A–Z</option><option value="za" ${sort==='za'?'selected':''}>Name Z–A</option></select></div>${selected.size?`<div class="engine-batch"><span>${selected.size} Dienste ausgewählt</span>${button('Starten','batch-start')}${button('Stoppen','batch-stop')}${button('Neustarten','batch-restart')}${button('Auswahl aufheben','clear')}</div>`:''}<div class="engine-group-list">${groups.map(([project,containers])=>{const managed=containers.find(c=>c.managed_app)?.managed_app;return `<details class="engine-group" data-engine-group="${safe(project)}" ${closedGroups.has(project)?'':'open'}><summary><span class="engine-group-chevron" aria-hidden="true">⌄</span><strong>${safe(project)}</strong><span>${containers.filter(c=>c.state==='running').length} / ${containers.length} Dienste aktiv</span></summary><div class="engine-group-toolbar"><span class="engine-scope-label">${managed?'Titan-App-Paket · Aktionen hier steuern das gesamte Paket':'Compose-Stack · Aktionen hier steuern alle Dienste'}</span><div class="engine-actions">${button(managed?'Paket starten':'Stack starten',managed?'package-start':'stack-start',managed||project)}${button(managed?'Paket stoppen':'Stack stoppen',managed?'package-stop':'stack-stop',managed||project)}${button('Neustarten',managed?'package-restart':'stack-restart',managed||project)}${managed?button('Deinstallieren','package-remove',managed,'danger'):''}</div>${progress(managed||'stack:'+project)}</div>${containers.map(serviceRow).join('')}</details>`;}).join('')}${singles.length?`<section class="engine-group"><h3 class="engine-standalone-title">Einzelne Container</h3>${singles.map(serviceRow).join('')}</section>`:''}</div>${!rows.length?'<p class="empty">Keine passenden Container.</p>':''}`;
   }
   if(view==='images')content=`<div class="engine-resource-list">${data.images.map(row=>`<article><div><strong>${safe(row.Repository)}:${safe(row.Tag)}</strong><small>${safe(row.Size)} · ${safe(row.CreatedSince)}</small></div>${button('Entfernen','image-remove',row.ID,'danger')}</article>`).join('')||'<p class="empty">Noch keine Images geladen.</p>'}</div>`;
   if(view==='volumes')content=`<p class="hint">Volumes bewahren Daten auch nach dem Entfernen eines Containers. Benutzte Volumes können nicht entfernt werden.</p><div class="engine-resource-list">${data.volumes.map(row=>`<article><div><strong>${safe(row.Name)}</strong><small>Treiber: ${safe(row.Driver)}</small></div>${button('Entfernen','volume-remove',row.Name,'danger')}</article>`).join('')||'<p class="empty">Noch keine Volumes angelegt.</p>'}</div>`;
   if(view==='networks')content=window.TitanNetworks?.inventoryPanel(networkData,{toolbar:false,selected:networkId})||'<p>Netzwerkverwaltung ist nicht geladen. Seite neu laden.</p>';
   if(view==='templates')content='<div data-template-browser></div>';
   const createLabel=view==='images'?'Image laden':view==='volumes'?'Volume erstellen':view==='networks'?'Netzwerk erstellen':'Container erstellen',createOp=view==='images'?'pull':view==='volumes'?'volume-create':view==='networks'?'network-create':'create';
   const description=view==='networks'?'Systemnetze und verwendete Netzwerke bleiben geschützt.':view==='volumes'?'Volumes bewahren Containerdaten. Benutzte Volumes bleiben geschützt.':view==='images'?'Lokal heruntergeladene Container-Images.':view==='templates'?'Ports, Speicher und weitere Optionen sind vor der Installation anpassbar.':view==='stacks'?'Ein Projekt gruppiert alle Dienste eines App-Pakets oder Compose-Stacks.':'Wähle einen Container für Details und weitere Aktionen.';
   container.innerHTML=`<section class="engine-workbench ${detailId?'has-inspector':''}"><aside class="engine-navigation"><div class="engine-nav-heading">${icon('containers')}<strong>Container Manager</strong></div><div role="tablist" aria-label="Docker-Bereiche">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${view===id}" data-engine-tab="${id}" class="button small ${view===id?'primary':''}">${icon(id)}<span>${label}</span>${['overview','templates'].includes(id)?'':`<small>${id==='stacks'?groups.length:id==='networks'?networkData.networks.length||data.networks?.length||0:data[id]?.length||0}</small>`}</button>`).join('')}</div></aside><div class="engine-main"><div class="engine-toolbar"><h2>${safe(tabs.find(([id])=>id===view)?.[1]||'Container')}</h2><div class="engine-toolbar-actions">${button(createLabel,createOp,'','primary')}${button('Aktualisieren','refresh')}</div></div><p class="engine-feedback ${lastResult?.status==='failed'?'is-error':''}" role="status" data-engine-status>${lastResult?safe(lastResult.message):busy?'Aktion läuft …':data.available===false?safe(data.error||'Docker nicht erreichbar.'):safe(description)}</p><div class="engine-content">${content}</div><footer class="engine-footer"><span class="engine-footer-dot ${data.available===false?'is-error':''}"></span>${data.available===false?'Docker nicht erreichbar':'Docker bereit'}<span>${view==='networks'?networkData.networks.length+' Netzwerke':data.containers.length+' Container'}</span></footer></div>${drawer()}</section>`;
   if(view==='templates'&&window.TitanTemplateBrowser)templateBrowser=window.TitanTemplateBrowser.mount(container.querySelector('[data-template-browser]'),{api,action,install:installTemplate,toast,artwork:window.TitanArtwork?.render,state:templateState});
   if(view==='networks'&&window.TitanNetworks)window.TitanNetworks.mountInventory(container,networkData,{api,action:(operation,args)=>execute(operation,args,['network:'+args.name]),dialog,askYesNo,toast},{toolbar:false,selected:networkId,onSelect:name=>{networkId=name;}});
   for(const saved of scrolls){const node=container.querySelector('.'+saved.className.split(' ')[0]);if(node)node.scrollTop=saved.top;}
   if(focusKey){const inputs=[...container.querySelectorAll(`[data-engine-${focusKey}]`)];const input=inputs.find(node=>(focusKey!=='select'||node.dataset.engineSelect===focusId)&&node.getClientRects().length);input?.focus();if(focusKey==='search'&&typeof position==='number')input?.setSelectionRange?.(position,position);}
  }
  async function refresh(force=false){if(refreshing||!alive||container.ownerDocument.hidden)return;refreshing=true;try{const next=await api('/api/docker-engine');if(!alive)return;let networkChanged=false;if(view==='networks'){try{const fresh=await api('/api/app-networks');if(!alive)return;networkChanged=JSON.stringify(fresh)!==JSON.stringify(networkData);networkData=fresh;}catch(error){networkData={available:false,networks:[],warnings:[error.message]};networkChanged=true;}if(networkId&&!networkData.networks?.some(row=>row.name===networkId))networkId=null;}const changed=JSON.stringify(next)!==JSON.stringify(data);data=next;selected=new Set([...selected].filter(id=>data.containers.some(c=>c.id===id&&!backup(c))));if(detailId&&!data.containers.some(c=>c.id===detailId))detailId=null;if(force||(changed&&view!=='templates')||networkChanged)render();const values=await api('/api/docker-metrics');if(!alive)return;metrics=values.containers||{};container.querySelectorAll('[data-engine-metric]').forEach(node=>{const c=data.containers.find(c=>c.id===node.dataset.engineMetric);if(c)node.innerHTML=metric(resource(c),bytes);});const overview=container.querySelector('[data-engine-summary]');if(overview)overview.innerHTML=summary();}catch(error){if(alive){const status=container.querySelector('[data-engine-status]');if(status)status.textContent=error.message;}}finally{refreshing=false;}}
  const field=(label,name,type='text',value='',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${safe(value)}" ${extra}></label>`;
  const end=text=>`<div class="form-actions"><button type="button" class="button" data-action="close">Abbrechen</button><button type="submit" class="button primary">${text}</button></div>`;
  const select=(label,key,values)=>`<label class="field">${label}<select name="${key}">${values.map(([id,text])=>`<option value="${safe(id)}">${safe(text)}</option>`).join('')}</select></label>`;
  async function create(){const locations=await api('/api/storage-locations');if(!alive)return;const resources=window.TitanLocations.resources(locations,'apps'),preferred=window.TitanLocations.preferred(locations,'apps'),choices=[[preferred?.id||'',''+(preferred?window.TitanLocations.label(preferred):'Kein Speicher verfügbar')],...resources.filter(item=>item.id!==preferred?.id).map(item=>[item.id,window.TitanLocations.label(item)]),...data.volumes.map(item=>['@docker-volume:'+item.Name,'Docker-Volume · '+item.Name])];const storage=`<label class="field">Speicher für Containerdaten<select name="data_storage" required>${choices.map(([id,label],index)=>`<option value="${safe(id)}" ${index===0?'selected':''} ${resources.some(item=>item.id===id&&item.available===false)||id===preferred?.id&&preferred?.available===false?'disabled':''}>${safe(label)}</option>`).join('')}</select></label>`;dialog('Container erstellen',`<form><div class="form-grid">${field('Name','name','text','','required maxlength="48"')}${field('Docker-Image','image','text','','required placeholder="nginx:stable"')}${select('Netzwerk','network',[['bridge','Bridge (Standard)'],['host','Host'],['none','Ohne Netzwerk'],...data.networks.filter(v=>!['bridge','host','none'].includes(v.Name)).map(v=>[v.Name,v.Name])])}${select('Neustartregel','restart',[['unless-stopped','Sofern nicht manuell gestoppt'],['always','Immer'],['on-failure','Bei Fehler'],['no','Nicht automatisch']])}${field('RAM-Limit (MiB)','memory_mb','number','1024','min="64" required')}${field('CPU-Limit','cpus','number','2','min="1" required')}${storage}${field('Datenziel im Container','target','text','/data')}</div><p class="hint">Titan legt ein eigenes Datenverzeichnis im gewählten Speicher an. Alternativ kannst du ein vorhandenes Docker-Volume wählen. Der technische Hostpfad muss nicht eingegeben werden.</p><label class="field">Ports · eine Zuordnung je Zeile<textarea name="ports" rows="3" placeholder="8080:80/tcp"></textarea></label><p class="hint">Bei Host/Ohne Netzwerk das Portfeld leer lassen. Ein fehlendes Image wird beim Erstellen geladen.</p><label class="field">Umgebung · NAME=Wert je Zeile<textarea name="environment" rows="4" autocomplete="off" spellcheck="false" placeholder="TZ=Europe/Berlin"></textarea></label><details><summary>USB / GPU durchreichen</summary><div class="tile-picker-options">${window.TitanDevices.fields(data.devices||[])}</div></details>${end('Erstellen & starten')}</form>`,async form=>{const config=Object.fromEntries(form);Object.assign(config,containerStorageConfig(config.data_storage));delete config.data_storage;config.devices=form.getAll("devices");config.ports=parsePorts(config.ports);config.environment=parseEnv(config.environment);config.memory_mb=Number(config.memory_mb);config.cpus=Number(config.cpus);await execute('docker_container_create',{config});});}
  async function click(event){const tab=event.target.closest('[data-engine-tab]');if(tab&&container.contains(tab)){view=tab.dataset.engineTab;detailId=null;render();if(view==='networks')await refresh(true);return;}const control=event.target.closest('[data-engine-action]');if(!control||busy)return;const op=control.dataset.engineAction,id=control.dataset.engineId;
   try{if(op==='select'){detailId=id;inspectorLogs='';inspectorCommand='';inspectorCommandOutput='';inspectorCommandStatus='';inspectorCommandFailed=false;render();return;}if(op==='drawer-close'){detailId=null;render();return;}if(op==='settings'){if(!isAdmin)throw Error('Administratorrechte erforderlich.');if(!window.TitanDockerEditor)throw Error('Einstellungen sind nicht geladen. Seite neu laden.');await window.TitanDockerEditor.manual(id,{api,dialog,action:(operation,args)=>execute(operation,args,[id]),networks:data.networks,parsePorts,parseEnv});return;}if(op==='hardware'){const c=data.containers.find(c=>c.id===id);if(!c)throw Error('Container nicht gefunden.');if(['running','paused'].includes(c.state))throw Error('Container zuerst stoppen.');dialog('Container-Geräte',`<form><p class="notice">Titan bewahrt den aktuellen Container als gestoppte Sicherung auf und erstellt eine Kopie mit den gewählten Geräten. Datenvolume, Ports und gespeicherte Dateien bleiben erhalten. Die Kopie wird gestartet.</p>${window.TitanDevices.fields(data.devices||[],c.hardware||[])}${end('Geräte übernehmen')}</form>`,form=>execute('docker_container_hardware',{container:id,devices:form.getAll('devices')},[id]));return;}if(op==='select-visible'){for(const c of filtered(data.containers,query,state,sort)){if(selected.size>=64)break;if(!backup(c))selected.add(c.id);}render();return;}if(op==='clear'){selected.clear();render();return;}
    if(op.startsWith('package-')){const verb=op.slice(8),confirmed=verb==='start'||await askYesNo(verb==='remove'?'Dieses App-Paket stoppen und deinstallieren? Konfiguration, Datenbank und Nutzdaten bleiben erhalten.':`Das gesamte App-Paket ${verb==='stop'?'stoppen':'neu starten'}?`);if(!confirmed)return;await execute('app_action',{app:id,action:verb},[id,...data.containers.filter(c=>c.managed_app===id).map(c=>c.id)]);return;}
    if(op.startsWith('batch-')||op.startsWith('stack-')){const containers=op.startsWith('stack-')?(stacks(data.containers).find(([key])=>key===id)?.[1]||[]).map(c=>c.id):[...selected];if(!containers.length)throw Error('Container auswählen.');const verb=op.split('-')[1];if(verb!=='start'&&!await askYesNo(`${containers.length} Dienste ${verb==='stop'?'stoppen':'neu starten'}?`))return;await execute('docker_container_batch',{containers,action:verb},[...containers,...(op.startsWith('stack-')?['stack:'+id]:[])]);selected.clear();render();return;}
    if(op==='refresh'){if(view==='templates')await templateBrowser?.refresh();else await refresh(true);return;}if(op==='network-create'){if(!window.TitanNetworks)throw Error('Netzwerkverwaltung ist nicht geladen. Seite neu laden.');window.TitanNetworks.createDialog({dialog,action:(operation,args)=>execute(operation,args,['network:'+args.name])},result=>{networkId=result.network?.name||null;render();});return;}if(op==='create'){await create();return;}if(op==='pull'){dialog('Docker-Image laden',`<form>${field('Image mit Tag','image','text','','required placeholder="nginx:stable"')}${end('Laden')}</form>`,async form=>execute('docker_image_pull',{image:form.get('image')}));return;}if(op==='volume-create'){dialog('Datenvolume erstellen',`<form>${field('Volume-Name','resource','text','','required')}${end('Erstellen')}</form>`,async form=>execute('docker_resource',{kind:'volume',action:'create',resource:form.get('resource')}));return;}
    if(op==='logs'||op==='details'){const result=await api('/api/docker-container?container='+encodeURIComponent(id));if(!alive)return;detailId=id;inspectorLogs=result.logs||'Keine Logs vorhanden.';render();return;}
    if(['remove','image-remove','volume-remove'].includes(op)&&!await askYesNo(op==='volume-remove'?'Volume und seine Daten unwiderruflich löschen?':op==='image-remove'?'Dieses unbenutzte Image entfernen?':'Diesen einzelnen Container stoppen und entfernen? Volumes und Nutzdaten bleiben erhalten. Die übrigen Dienste des Pakets bleiben unverändert.'))return;
    if(op==='stop'&&!await askYesNo('Diesen einzelnen Dienst stoppen? Andere Dienste des Pakets laufen weiter.'))return;
    if(op==='image-remove'||op==='volume-remove')await execute('docker_resource',{kind:op==='image-remove'?'image':'volume',action:'remove',resource:id},[id]);else await execute('docker_container_action',{container:id,action:op,...(op==='remove'?{stop_before_remove:true}:{})},[id]);
   }catch(error){toast(error.message,true);}finally{control.disabled=false;}
  }
  function input(event){if(event.target.matches('[data-engine-command]')){inspectorCommand=event.target.value;return;}if(event.target.matches('[data-engine-search]')){query=event.target.value;render();}if(event.target.matches('[data-engine-sort]')){sort=event.target.value;render();}if(event.target.matches('[data-engine-state]')){state=event.target.value;render();}if(event.target.matches('[data-engine-select]')){const id=event.target.dataset.engineSelect;if(event.target.checked){if(selected.size>=64){event.target.checked=false;toast('Maximal 64 Container auswählen.',true);return;}selected.add(id);}else selected.delete(id);render();}}
  async function command(event){const form=event.target;if(!form.matches?.('[data-engine-command-form]')||!container.contains(form))return;event.preventDefault();if(busy||!isAdmin)return;const id=form.dataset.engineContainer,input=form.querySelector('[name=command]'),value=String(input?.value||'').trim();if(!value)return;inspectorCommand=value;inspectorCommandOutput='';inspectorCommandStatus='Befehl wird ausgeführt …';inspectorCommandFailed=false;try{const result=await execute('docker_container_exec',{container:id,command:value},[id]);if(!alive||detailId!==id)return;inspectorCommandOutput=String(result.output||'(Keine Ausgabe)');inspectorCommandStatus=`Exit-Code ${result.exit_code}${result.timed_out?' · Zeitlimit erreicht':''}${result.truncated?' · Ausgabe auf 64 KiB begrenzt':''}`;inspectorCommandFailed=Number(result.exit_code)!==0||result.timed_out===true;lastResult={status:inspectorCommandFailed?'failed':'completed',message:inspectorCommandStatus};objectJobs.set(id,{status:lastResult.status,message:inspectorCommandStatus});}catch(error){if(alive&&detailId===id){inspectorCommandStatus=error.message;inspectorCommandFailed=true;}toast(error.message,true);}finally{if(alive)render();}}
  // Dialog buttons live outside the workbench. One delegated listener supports
  // log refresh and is always removed on navigation/logout.
  function toggle(event){const group=event.target.closest?.('[data-engine-group]');if(group){if(group.open)closedGroups.delete(group.dataset.engineGroup);else closedGroups.add(group.dataset.engineGroup);}}
  selectView=id=>{if(!['overview','stacks','containers','images','networks','volumes','templates'].includes(id))return;view=id;detailId=null;render();if(id==='networks')void refresh(true);};
  const doc=container.ownerDocument;doc.addEventListener('click',click);container.addEventListener('input',input);container.addEventListener('change',input);container.addEventListener('toggle',toggle,true);container.addEventListener('submit',command);render();const timer=setInterval(()=>refresh(),5000);current=()=>{alive=false;templateBrowser?.destroy();clearInterval(timer);window.TitanNetworks?.disposeWithin(container);doc.removeEventListener('click',click);container.removeEventListener('input',input);container.removeEventListener('change',input);container.removeEventListener('toggle',toggle,true);container.removeEventListener('submit',command);};await refresh(true);
 }
 const api={mount,dispose,selectView:id=>selectView?.(id),containerStorageConfig,ports,parsePorts,parseEnv,metric,filtered,stacks,totals,webLink};if(root)root.TitanDocker=api;if(typeof module==='object')module.exports=api;
})(typeof window==='undefined'?null:window);
