'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanFileTypes=ui;})(typeof window==='undefined'?null:window,function(){
 const types=[['txt','Textdatei','TXT','text'],['docx','Word-Dokument','W','word'],['xlsx','Excel-Tabelle','X','sheet'],['odt','OpenDocument-Text','ODT','word'],['ods','OpenDocument-Tabelle','ODS','sheet'],['md','Markdown','MD','text'],['py','Python','PY','code'],['sh','Shell-Skript','SH','code'],['json','JSON','{}','code'],['yaml','YAML','YML','code'],['csv','CSV-Tabelle','CSV','sheet'],['html','HTML','<>','code'],['css','CSS','CSS','code'],['js','JavaScript','JS','code'],['xml','XML','XML','code'],['conf','Konfiguration','CFG','text'],['','Ohne Dateiendung','TXT','text'],['custom','Eigene Dateiendung','…','text']].map(([extension,label,symbol,category])=>({extension,label,symbol,category,document:['docx','xlsx','odt','ods'].includes(extension)}));
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function info(extension){const ext=String(extension||'').replace(/^\./,'').toLowerCase(),known=types.find(row=>row.extension===ext);if(known)return known;const office={doc:['Word-Dokument','W','word'],docm:['Word-Dokument','W','word'],rtf:['Rich-Text-Dokument','RTF','word'],xls:['Excel-Tabelle','X','sheet'],xlsm:['Excel-Tabelle','X','sheet'],ppt:['Präsentation','P','slide'],pptx:['Präsentation','P','slide'],odp:['OpenDocument-Präsentation','P','slide'],pdf:['PDF-Dokument','PDF','pdf']};if(Object.hasOwn(office,ext)){const[label,symbol,category]=office[ext];return {extension:ext,label,symbol,category,document:false};}return {extension:ext,label:ext?ext.toUpperCase()+'-Datei':'Datei',symbol:ext.slice(0,4).toUpperCase()||'TXT',category:'text',document:false};}
 function icon(extension){const row=info(extension);return `<span class="file-type-icon file-type-${row.category}" role="img" aria-label="${escape(row.label)}"><svg viewBox="0 0 32 36" aria-hidden="true"><path d="M4 1h16l8 8v25H4z"/><path d="M20 1v8h8"/></svg><span aria-hidden="true">${escape(row.symbol)}</span></span>`;}
 function filename(base,type,custom=''){const leaf=String(base||'').trim(),ext=(type==='custom'?custom:type).trim().replace(/^\.+/,'');if(!leaf||leaf==='.'||leaf==='..'||/[\\/\0]/.test(leaf))throw Error('Bitte einen Dateinamen ohne Pfad angeben.');if(ext&&!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,31}$/.test(ext))throw Error('Bitte eine gültige Dateiendung angeben.');const name=ext&& !leaf.toLowerCase().endsWith('.'+ext.toLowerCase())?leaf+'.'+ext:leaf;if(new TextEncoder().encode(name).length>255)throw Error('Der Dateiname ist zu lang.');return {name,extension:ext.toLowerCase(),document:info(ext).document};}
 function fields(){return `<div class="two-columns"><label class="field">Dateiname<input name="name" value="Neue Datei" required maxlength="220" autocomplete="off"></label><label class="field">Dateityp<select name="file_type">${types.map(row=>`<option value="${escape(row.extension)}">${escape(row.label+(row.extension&&row.extension!=='custom'?' (.'+row.extension+')':''))}</option>`).join('')}</select></label></div><label class="field" data-file-custom hidden>Eigene Endung<input name="extension" maxlength="32" placeholder="z. B. log"></label><div class="file-create-preview" aria-live="polite" data-file-create-preview></div><label class="field" data-file-text-content>Inhalt (optional)<textarea name="content" class="file-editor" rows="7" spellcheck="false"></textarea></label><p class="hint" data-file-create-note></p>`;}
 function mount(body){const form=body.querySelector('form');if(!form)return;function update(){let chosen;try{chosen=filename(form.elements.name.value,form.elements.file_type.value,form.elements.extension.value);}catch(error){chosen={name:error.message,extension:form.elements.file_type.value};}const row=info(chosen.extension);body.querySelector('[data-file-custom]').hidden=form.elements.file_type.value!=='custom';body.querySelector('[data-file-text-content]').hidden=Boolean(row.document);body.querySelector('[data-file-create-preview]').innerHTML=icon(chosen.extension)+`<strong>${escape(chosen.name)}</strong>`;body.querySelector('[data-file-create-note]').textContent=row.document?'Ein gültiges leeres Dokument wird erstellt. Du kannst es herunterladen oder mit eingerichtetem Euro-Office bearbeiten.':'Eine UTF-8-Textdatei wird erstellt (maximal 1 MiB). Vorhandene Dateien bleiben erhalten.';}
 form.addEventListener('input',update);form.addEventListener('change',update);update();}
 return {types,info,icon,filename,fields,mount};
});
