'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.TitanFilePlaces=api;})(typeof window==='undefined'?null:window,function(){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const key=owner=>'titan-file-favorites:'+encodeURIComponent(owner||'');
 const symbols={folder:'<path d="M3 7V6a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/>',share:'<path d="M3 7V6a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v5M3 7v12a2 2 0 0 0 2 2h6"/><path d="M16 14v3m-4 4v-4h8v4m-5-7h2"/>',system:'<rect x="4" y="3" width="16" height="7" rx="2"/><rect x="4" y="14" width="16" height="7" rx="2"/><path d="M7 7h.01M7 18h.01m5-11h5m-5 11h5"/>',drive:'<rect x="4" y="3" width="16" height="18" rx="2"/><circle cx="12" cy="10" r="4"/><path d="m12 10 5 6m-10 2h.01"/>',home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V10Z"/><path d="M9 21v-8h6v8"/>',apps:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="M14 17h7m-3.5-3.5v7"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16"/><rect x="7" y="4" width="3" height="4" rx="1"/><rect x="14" y="10" width="3" height="4" rx="1"/><rect x="8" y="16" width="3" height="4" rx="1"/>',logs:'<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9l-6-6Zm0 0v6h6M8 13h8m-8 4h5"/>',favorite:'<path d="m12 3 2.8 5.8 6.4.9-4.6 4.5 1.1 6.3-5.7-3-5.7 3 1.1-6.3-4.6-4.5 6.4-.9Z"/>',sidebar:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18M5.5 7h.01m-.01 5h.01m-.01 5h.01"/>'};
 function icon(kind='folder'){kind=Object.hasOwn(symbols,kind)?kind:'folder';return `<svg class="fb-place-icon fb-place-icon-${Object.hasOwn(symbols,kind)?kind:'folder'}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${symbols[kind]||symbols.folder}</svg>`;}
 function valid(item){return item&&typeof item.share==='string'&&item.share.length<=64&&typeof item.path==='string'&&item.path.length<=4096&&!item.path.startsWith('/')&&!item.path.split('/').includes('..')&&!item.path.includes('\0');}
 function localStorage(){try{return globalThis.localStorage;}catch{return null;}}
 function load(owner,storage=localStorage()){try{const rows=JSON.parse(storage?.getItem(key(owner))||'[]');return Array.isArray(rows)?rows.filter(valid).slice(0,40):[];}catch{return[];}}
 function toggle(owner,item,storage=localStorage()){if(!valid(item))throw Error('Ungültiger Favorit.');const rows=load(owner,storage),found=rows.findIndex(row=>row.share===item.share&&row.path===item.path);if(found>=0)rows.splice(found,1);else{if(rows.length>=40)throw Error('Maximal 40 Favoriten.');rows.push({share:item.share,path:item.path,label:String(item.label||item.path.split('/').pop()||item.share).slice(0,96)});}storage?.setItem(key(owner),JSON.stringify(rows));return rows;}
 function render(ctx){const rows=load(ctx.owner).filter(row=>(ctx.shares||[]).some(share=>share.name===row.share&&!share.blocked)&&(row.share!=='@system'||!ctx.storage||ctx.storage.some(item=>item.available!==false&&(row.path===item.path.slice(1)||row.path.startsWith(item.path.slice(1)+'/')))));return `<div class="fb-favorites"><h3>Favoriten</h3>${rows.map(row=>`<button type="button" class="fb-place" data-fb-share="${esc(row.share)}" data-fb-path="${esc(row.path)}">${icon("favorite")}<span>${esc(row.label)}</span></button>`).join('')||'<p class="hint">Ordner mit ☆ merken.</p>'}</div>`;}
 function tree(ctx){const folders=(ctx.entries||[]).filter(entry=>entry.directory&&!entry.symlink).slice(0,60);return `<details class="fb-folder-tree" open><summary>Ordner hier</summary>${folders.map(entry=>`<button type="button" class="fb-place" data-fb-share="${esc(ctx.share)}" data-fb-path="${esc(entry.path||[ctx.path,entry.name].filter(Boolean).join('/'))}">${icon("folder")}<span>${esc(entry.name)}</span></button>`).join('')||'<p class="hint">Keine Unterordner.</p>'}</details>`;}
 function mount(browser,ctx){const controller=new AbortController(),button=browser.querySelector('[data-fb-favorite]');if(!button)return ()=>{};function update(){const on=load(ctx.owner).some(row=>row.share===ctx.share&&row.path===ctx.path);button.setAttribute('aria-pressed',String(on));button.textContent=on?'★':'☆';button.title=on?'Ordner aus Favoriten entfernen':'Ordner als Favorit speichern';const area=browser.querySelector('.fb-favorites');if(area)area.outerHTML=render(ctx);}button.addEventListener('click',()=>{try{toggle(ctx.owner,{share:ctx.share,path:ctx.path,label:ctx.path?.split('/').pop()||ctx.share});update();}catch(error){ctx.toast?.(error.message,true);}},{signal:controller.signal});update();return()=>controller.abort();}
 return{load,toggle,render,tree,mount,valid,icon};
});
