/* Local groups, inherited permissions and supported quotas. */
(function(global){
 'use strict';
 const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 const editableShares=data=>data.shares.filter(share=>!Object.values(data.homes||{}).some(home=>home.share===share.name));
 const labels={files:'Dateimanager',apps:'Apps und Docker',vms:'Virtuelle Maschinen',backups:'Datensicherung'};
 const permissionOptions=value=>[['','Von Gruppen übernehmen'],['none','Kein Zugriff'],['read','Nur lesen'],['write','Lesen und Schreiben']].map(([id,label])=>`<option value="${id}" ${value===id?'selected':''}>${label}</option>`).join('');
 const appOptions=value=>[['','Von Gruppen / Standard übernehmen'],['allow','Erlauben'],['deny','Verweigern']].map(([id,label])=>`<option value="${id}" ${value===id?'selected':''}>${label}</option>`).join('');
 function panel(data,group=null){
  const item=group||{name:'',description:'',members:[],applications:{},shares:{}};
  return `<form data-identity-group><h3>${group?'Gruppe bearbeiten':'Neue Gruppe'}</h3><label>Gruppenname<input name="name" value="${escape(item.name)}" required pattern="[a-z][a-z0-9_-]{0,30}" ${group?'readonly':''}></label><label>Beschreibung<input name="description" maxlength="256" value="${escape(item.description)}"></label><fieldset><legend>Mitglieder</legend><div class="identity-checks">${data.users.map(user=>`<label><input type="checkbox" name="member" value="${escape(user.name)}" ${(item.members||[]).includes(user.name)?'checked':''}>${escape(user.display_name||user.name)}</label>`).join('')}</div></fieldset><fieldset><legend>Anwendungen</legend>${Object.entries(labels).map(([id,label])=>`<label>${label}<select data-group-app="${id}">${appOptions(id in item.applications?(item.applications[id]?'allow':'deny'):'')}</select></label>`).join('')}</fieldset><fieldset><legend>Freigaben</legend>${editableShares(data).map(share=>`<label>${escape(share.name)}<select data-group-share="${escape(share.name)}">${permissionOptions(item.shares[share.name]||'')}</select></label>`).join('')}</fieldset><p class="hint">Ein Verweigern in einer Gruppe hat Vorrang. Ein ausdrücklich gesetztes Benutzerrecht überschreibt die Gruppenregel. Persönliche Ordner bleiben privat.</p><div class="form-actions"><button class="button primary" type="submit">Speichern</button><button class="button" type="button" data-identity-cancel>Abbrechen</button></div><p data-identity-error role="alert" hidden></p></form>`;
 }
 function render(data){
  return `<section class="identity-center panel" data-identity-center><header><h2>Gruppen und Berechtigungen</h2><button class="button primary" type="button" data-identity-new>+ Gruppe</button></header><p class="hint">Gruppen bündeln Zugriffe für Familie, Teams oder Projekte. Änderungen gelten für Webanwendungen und SMB-Freigaben.</p><div class="identity-layout"><div data-identity-list>${data.policy.groups.length?data.policy.groups.map(group=>`<article class="identity-group"><div><h3>${escape(group.name)}</h3><p>${escape(group.description||'Keine Beschreibung')} · ${group.members.length} Mitglieder</p></div><div><button class="button" data-identity-edit="${escape(group.name)}">Bearbeiten</button><button class="button danger" data-identity-remove="${escape(group.name)}">Löschen</button></div></article>`).join(''):'<p>Noch keine Gruppen angelegt.</p>'}</div><div data-identity-editor></div></div><details><summary>Wirksame Rechte je Benutzer</summary>${data.users.map(user=>`<article class="identity-effective"><h3>${escape(user.display_name||user.name)}</h3><dl>${Object.entries(data.effective[user.name].applications).map(([id,right])=>`<dt>${labels[id]}</dt><dd>${right.allowed?'Erlaubt':'Kein Zugriff'} <small>· ${escape(right.source)}</small></dd>`).join('')}${Object.entries(data.effective[user.name].shares).map(([name,right])=>`<dt>${escape(name)}</dt><dd>${({none:'Kein Zugriff',read:'Nur Lesen',write:'Lesen und Schreiben'})[right.permission]} <small>· ${escape(right.source)}</small></dd>`).join('')}</dl></article>`).join('')}</details></section>`;
 }
 async function waitJob(api,id){
  const deadline=Date.now()+300000;
  while(Date.now()<deadline){const jobs=await api('/api/jobs'),job=jobs.find(item=>item.id===id);if(job?.status==='failed')throw new Error(job.result?.error||'Rechte konnten nicht gespeichert werden.');if(job?.status==='completed')return job.result;await new Promise(resolve=>setTimeout(resolve,750));}
  throw new Error('Auftrag läuft weiter. Prüfe den Status in den Aktivitäten.');
 }
 function mount(root,data,options){
  const center=root.querySelector('[data-identity-center]');if(!center)return;
  const save=async policy=>{const result=await options.api('/api/identity',policy);options.onJob?.(result.job);await waitJob(options.api,result.job);options.toast?.('Gruppenrechte gespeichert.');await options.refresh?.();};
  const open=group=>{
   const target=center.querySelector('[data-identity-editor]');target.innerHTML=panel(data,group);
   target.querySelector('[data-identity-cancel]').onclick=()=>{target.innerHTML='';};
   target.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]'),error=form.querySelector('[data-identity-error]');button.disabled=true;error.hidden=true;
    try{const values=new FormData(form),item={name:values.get('name'),description:values.get('description'),members:values.getAll('member'),applications:{},shares:{}};
     for(const select of form.querySelectorAll('[data-group-app]'))if(select.value)item.applications[select.dataset.groupApp]=select.value==='allow';
     for(const select of form.querySelectorAll('[data-group-share]'))if(select.value)item.shares[select.dataset.groupShare]=select.value;
     const latest=await options.api('/api/identity'),policy=structuredClone(latest.policy),index=policy.groups.findIndex(entry=>entry.name===item.name);policy.expected_revision=latest.revision;if(!group&&index>=0)throw new Error('Dieser Gruppenname existiert bereits.');if(index>=0)policy.groups[index]=item;else policy.groups.push(item);await save(policy);
    }catch(failure){error.textContent=failure.message;error.hidden=false;}finally{button.disabled=false;}
   };target.scrollIntoView({block:'nearest'});target.querySelector('input').focus();
  };
  center.querySelector('[data-identity-new]').onclick=()=>open(null);
  for(const button of center.querySelectorAll('[data-identity-edit]'))button.onclick=()=>open(data.policy.groups.find(group=>group.name===button.dataset.identityEdit));
  for(const button of center.querySelectorAll('[data-identity-remove]'))button.onclick=async()=>{if(!(await options.confirm?.(`Gruppe „${button.dataset.identityRemove}“ löschen?`)))return;button.disabled=true;try{const latest=await options.api('/api/identity');latest.policy.groups=latest.policy.groups.filter(group=>group.name!==button.dataset.identityRemove);latest.policy.expected_revision=latest.revision;await save(latest.policy);}catch(failure){options.toast?.(failure.message,true);button.disabled=false;}};
 }
 function userPanel(user,data){
  const item=data.policy.users[user.name]||{applications:{},shares:{}};
  return `<section data-user-identity="${escape(user.name)}"><h3>Anwendungsrechte</h3><form data-user-app-rights>${Object.entries(labels).map(([id,label])=>`<label>${label}<select data-user-app="${id}" ${user.role==='admin'?'disabled':''}>${appOptions(id in item.applications?(item.applications[id]?'allow':'deny'):'')}</select><small>${data.effective[user.name].applications[id].allowed?'Erlaubt':'Kein Zugriff'} · ${escape(data.effective[user.name].applications[id].source)}</small></label>`).join('')}<h3>Freigaberechte und Vererbung</h3>${editableShares(data).map(share=>`<label>${escape(share.name)}<select data-user-share="${escape(share.name)}">${permissionOptions(item.shares[share.name]||'')}</select><small>${({none:'Kein Zugriff',read:'Nur Lesen',write:'Lesen und Schreiben'})[data.effective[user.name].shares[share.name].permission]} · ${escape(data.effective[user.name].shares[share.name].source)}</small></label>`).join('')}<p class="hint">Apps und Docker sowie VM-Verwaltung gewähren umfassende Kontrolle über diese Bereiche. Administratoren haben vollständigen Zugriff.</p><button class="button primary" type="submit" ${user.role==='admin'?'disabled':''}>Benutzerrechte speichern</button><p role="alert" data-user-identity-error hidden></p></form><h3>Persönlicher Ordner</h3><p>Ein privater SMB-Ordner für diesen Benutzer. Andere Benutzer erhalten keinen Zugriff.</p><button class="button" data-user-home ${user.system_user==='titan-files'?'disabled':''}>Persönlichen Ordner einrichten</button><h3>Speicherlimit</h3><div data-user-quota>Unterstützte Speicherbereiche werden geprüft …</div></section>`;
 }
 function mountUser(root,user,data,options){
  const panel=root.querySelector('[data-user-identity]');if(!panel)return;
  const error=panel.querySelector('[data-user-identity-error]');
  panel.querySelector('[data-user-app-rights]').onsubmit=async event=>{event.preventDefault();const submit=event.currentTarget.querySelector('[type=submit]');submit.disabled=true;error.hidden=true;
   try{const latest=await options.api('/api/identity'),policy=latest.policy;policy.expected_revision=latest.revision;policy.users[user.name]=policy.users[user.name]||{applications:{},shares:{}};policy.users[user.name].applications={};policy.users[user.name].shares={};for(const select of panel.querySelectorAll('[data-user-share]'))if(select.value)policy.users[user.name].shares[select.dataset.userShare]=select.value;for(const select of panel.querySelectorAll('[data-user-app]'))if(select.value)policy.users[user.name].applications[select.dataset.userApp]=select.value==='allow';const result=await options.api('/api/identity',policy);await waitJob(options.api,result.job);options.toast?.('Benutzerrechte gespeichert.');options.refresh?.();}catch(failure){error.textContent=failure.message;error.hidden=false;}finally{submit.disabled=false;}};
  panel.querySelector('[data-user-home]').onclick=async event=>{event.target.disabled=true;try{const result=await options.api('/api/identity/home',{name:user.name});const home=await waitJob(options.api,result.job);options.toast?.(`Persönlicher Ordner eingerichtet: ${home.share}`);}catch(failure){options.toast?.(failure.message,true);}finally{event.target.disabled=false;}};
  const area=panel.querySelector('[data-user-quota]');
  if(user.system_user==='titan-files'){area.textContent='Zuerst persönlichen SMB-Zugang einrichten.';return;}
  options.api('/api/identity/quotas?name='+encodeURIComponent(user.name)).then(quotas=>{area.innerHTML=quotas.targets.length?`<form data-user-quota-form><label>Speicherbereich<select name="target">${quotas.targets.map(target=>`<option value="${escape(target.id)}" ${target.supported?'':'disabled'}>${escape(target.label)} · ${escape(target.id)}</option>`).join('')}</select></label><p data-quota-usage></p><label>Limit in GiB <small>0 = unbegrenzt</small><input name="gib" type="number" min="0" step="0.01" required></label><p class="hint">Die Quote zählt Dateien, die dieser Linux-Benutzer besitzt. Anwendungsdaten eines Dienstkontos zählen nicht dazu.</p><button class="button primary" type="submit">Limit speichern</button></form>`:`<p class="hint">${escape(quotas.notice)}</p>`;
   const form=area.querySelector('form');if(!form)return;const update=()=>{const target=quotas.targets.find(item=>item.id===form.elements.target.value);form.elements.gib.value=String(target.limit_bytes/1073741824);form.querySelector('[data-quota-usage]').textContent=`Belegt: ${(target.used_bytes/1073741824).toFixed(2)} GiB`;};form.elements.target.onchange=update;update();form.onsubmit=async event=>{event.preventDefault();try{const result=await options.api('/api/identity/quotas',{name:user.name,target:form.elements.target.value,limit_bytes:Math.round(Number(form.elements.gib.value)*1073741824)});await waitJob(options.api,result.job);options.toast?.('Speicherlimit bestätigt.');}catch(failure){options.toast?.(failure.message,true);}};
  }).catch(failure=>{area.textContent=failure.message;});
 }
 global.TitanIdentity={render,mount,userPanel,mountUser,waitJob};
})(window);
