'use strict';
(() => {
 const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 const number = value => Number.isFinite(Number(value)) && Number(value) >= 0 ? Number(value) : 0;
 const formatBytes = value => { const size=number(value), units=['B','KiB','MiB','GiB','TiB'], unit=size?Math.min(4,Math.floor(Math.log(size)/Math.log(1024))):0;return `${(size/1024**unit).toLocaleString('de-DE',{maximumFractionDigits:unit>2?1:0})} ${units[unit]}`; };
 const button = (text,action,attributes='',kind='') => `<button type="button" class="button ${kind}" data-action="${action}" ${attributes}>${text}</button>`;
 const pill = (text,kind='') => `<span class="pill ${kind}">${escape(text)}</span>`;
 const empty = text => `<div class="empty">${escape(text)}</div>`;
 const views = new Map();
 const preferences = new Map();
 const glyphs = {
  vm:'<rect x="2.5" y="3.5" width="19" height="13" rx="2"/><path d="M8 21h8M12 17v4m-5-12 3 3 3-3"/>',
  docker:'<rect x="3" y="8" width="5" height="5" rx="1"/><rect x="9" y="8" width="5" height="5" rx="1"/><rect x="9" y="2" width="5" height="5" rx="1"/><path d="M2 15h18c-1 5-4 7-9 7-4 0-7-2-9-7Zm17-5 3 2-3 2"/>',
  grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  list:'<rect x="3" y="4" width="18" height="6" rx="1.5"/><rect x="3" y="14" width="18" height="6" rx="1.5"/><path d="M7 7h.01M7 17h.01M11 7h6M11 17h6"/>',
  disc:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="2"/><path d="m16 5-2 4M8 19l2-4"/>',
  cpu:'<rect x="6" y="6" width="12" height="12" rx="2"/><rect x="9" y="9" width="6" height="6" rx="1"/><path d="M9 2v4M15 2v4M9 18v4M15 18v4M2 9h4M2 15h4M18 9h4M18 15h4"/>',
  backup:'<path d="M3 7h18v14H3zM3 7l3-4h12l3 4M8 12h8M12 12v5"/>',
  network:'<rect x="8" y="2" width="8" height="6" rx="1"/><rect x="2" y="16" width="7" height="6" rx="1"/><rect x="15" y="16" width="7" height="6" rx="1"/><path d="M12 8v4M5.5 16v-4h13v4"/>',
  store:'<path d="M3 8h18l-2-5H5L3 8Zm0 0v4h18V8M5 12v9h14v-9M9 21v-6h6v6"/>'
 };
 const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${glyphs[name]||glyphs.list}</svg>`;
 const helpers = options => ({esc:escape,bytes:formatBytes,button,pill,empty,...options});
 const allowed = (ctx,application) => !ctx.session?.user || ctx.session.user.role === 'admin' || Boolean((ctx.session.permissions||ctx.session.user.permissions)?.[application]?.allowed);
 const state = (value,failed=false) => failed?'Fehler':({'running':'Läuft','shut off':'Gestoppt','paused':'Pausiert','shutoff':'Gestoppt','exited':'Gestoppt','created':'Bereit','restarting':'Startet neu','installing':'Installation läuft','unavailable':'Nicht verfügbar'})[value]||value||'Unbekannt';
 function safeUrl(value) {try {const url=new URL(value);return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?url.href:'';}catch{return '';}}
 function hintList(messages,esc) {return (messages||[]).map(value=>`<p class="mv-warning">${esc(value)}</p>`).join('');}
 function stats(items,esc) {return `<div class="mv-stats">${items.map(item=>`<article class="mv-stat"><span class="mv-stat-label">${esc(item.label)}</span><strong ${item.live?`data-${item.live}`:''}>${esc(item.value)}</strong>${item.detail?`<small>${esc(item.detail)}</small>`:''}</article>`).join('')}</div>`;}
 function tab(key,id,label,symbol,active) {return `<button type="button" role="tab" id="mv-${key}-tab-${id}" aria-controls="mv-${key}-panel-${id}" aria-selected="${id===active}" tabindex="${id===active?'0':'-1'}" data-manager-tab="${id}"><span class="mv-nav-icon">${icon(symbol)}</span><span>${label}</span></button>`;}
 function panel(key,id,content,active) {return `<section class="mv-tab-panel" role="tabpanel" id="mv-${key}-panel-${id}" aria-labelledby="mv-${key}-tab-${id}" data-manager-panel="${id}" ${id===active?'':'hidden'}>${content}</section>`;}
 function shell(key,label,symbol,tabs,active,toolbar,content,sideActions='',foot='') {
  return `<section class="mv-manager" data-manager="${key}" aria-label="${label}"><aside class="mv-sidebar"><div class="mv-brand"><span class="mv-brand-icon mv-brand-${key}">${icon(symbol)}</span><strong>${label}</strong></div><div role="tablist" class="mv-tabs" aria-label="${label}: Ansichten" aria-orientation="vertical">${tabs.map(([id,title,glyph])=>tab(key,id,title,glyph,active)).join('')}</div>${sideActions?`<div class="mv-side-actions">${sideActions}</div>`:''}${foot?`<div class="mv-side-foot">${foot}</div>`:''}</aside><div class="mv-workspace"><div class="mv-toolbar">${toolbar}</div><div class="mv-content">${content}</div></div></section>`;
 }
 function diskSize(vm) {return number(vm.virtual_size)||number(vm.disk_gb)*1024**3;}
 function vmResourceSummary(vms) {return {cpus:vms.reduce((sum,vm)=>sum+number(vm.cpus),0),memory:vms.filter(vm=>['running','paused','blocked','in shutdown','pmsuspended'].includes(vm.state)).some(vm=>!Number.isFinite(vm.metrics?.memory_resident_bytes))?null:vms.filter(vm=>['running','paused','blocked','in shutdown','pmsuspended'].includes(vm.state)).reduce((sum,vm)=>sum+number(vm.metrics.memory_resident_bytes),0),disk:vms.reduce((sum,vm)=>sum+diskSize(vm),0),running:vms.filter(vm=>vm.state==='running').length};}
 function vmCommands(vm,ctx) {
  const {esc,button}=ctx,id=`data-id="${esc(vm.id)}"`,off=vm.state==='shut off',paused=vm.state==='paused',running=vm.state==='running',available=ctx.data.available!==false;
  const enable=condition=>condition&&available?'':'disabled';
  return `<div class="vm-row-actions">${running?button('Herunterfahren','vm-action',`${id} data-command="shutdown" ${enable(true)}`,'small'):button(paused?'Fortsetzen':'Starten','vm-action',`${id} data-command="${paused?'resume':'start'}" ${enable(off||paused)}`,'small')}${button('Konsole','vm-console',`${id} ${enable(running&&!ctx.session?.demo)}`,'small primary')}<details class="vm-row-more"><summary class="button small" aria-label="Weitere Aktionen für ${esc(vm.name)}">Aktionen <span aria-hidden="true">⌄</span></summary><div class="vm-row-menu">${button('Details öffnen','vm-extensions',id,'small')}${button('VM-Einstellungen','vm-edit',`${id} ${enable(off)}`,'small')}${button('Laufwerk erweitern','vm-disk-grow',`${id} ${enable(off)}`,'small')}${running?button('Pausieren','vm-action',`${id} data-command="suspend" ${enable(true)}`,'small'):''}${button('USB-Geräte','vm-usb',`${id} ${enable(off)}`,'small')}${button('Installationsmedium','vm-media',`${id} ${enable(off)}`,'small')}${button(vm.autostart?'Autostart aus':'Autostart an','vm-action',`${id} data-command="${vm.autostart?'disable-autostart':'autostart'}" ${enable(true)}`,'small')}${running?button('Neustarten','vm-action',`${id} data-command="reboot" ${enable(true)}`,'small'):''}${button('Sichern','vm-backup',`${id} ${enable(off)}`,'small')}${button('VM entfernen','vm-remove',`${id} ${enable(off)}`,'small danger')}${off?'':button('Ausschalten erzwingen','vm-force-off',`${id} ${enable(true)}`,'small danger')}</div></details></div>`;
 }
 function vmRow(vm,ctx) {
  const {esc,bytes,pill}=ctx,id=`data-id="${esc(vm.id)}"`,running=vm.state==='running',disk=diskSize(vm),cpuIds=Array.isArray(vm.cpu_ids)?vm.cpu_ids:[];
  const search=[vm.name,vm.state,vm.disk_path,vm.iso,...cpuIds.map(id=>'CPU '+id)].join(' ').toLocaleLowerCase('de-DE');
  return `<article class="vm-list-row" data-manager-item data-vm-row="${esc(vm.id)}" data-manager-search="${esc(search)}" data-manager-state="${running?'running':'stopped'}"><button type="button" class="vm-row-select" data-action="vm-extensions" ${id} data-tab="overview" aria-label="${esc(vm.name)}: Details öffnen"><span class="vm-row-icon">${icon('vm')}</span><span class="vm-row-name"><strong>${esc(vm.name)}</strong>${pill(state(vm.state),running?'':'gray')}</span></button><div class="vm-row-configuration"><span>${esc(vm.cpus??'—')} vCPU · ${number(vm.memory_mb)?bytes(number(vm.memory_mb)*1024**2):'—'} RAM</span><span>${disk?bytes(disk):'—'} Laufwerk · ${vm.firmware==='uefi'?'UEFI':'BIOS'}</span><span class="vm-row-path" title="${esc(vm.disk_path||'')}">${esc(vm.disk_path||'Laufwerk nicht ermittelt')}</span><span class="vm-row-pinning">${cpuIds.length?cpuIds.map(id=>'CPU '+esc(id)).join(', '):'Automatische CPU-Zuweisung'}</span></div><div class="vm-row-live" data-vm-live="${esc(vm.id)}" data-vm-state="${esc(vm.state)}">${typeof window!=="undefined"?window.TitanVMLive?.render(vm,{bytes,esc})||'':''}</div>${vmCommands(vm,ctx)}</article>`;
 }
 function filterBar(key,label) {return `<div class="mv-filter-bar"><label class="mv-search"><span aria-hidden="true">⌕</span><input type="search" data-manager-search-input placeholder="${label}" aria-label="${label}"></label><select data-manager-state-filter aria-label="Status filtern"><option value="">Alle Status</option><option value="running">Läuft</option><option value="stopped">Gestoppt / andere</option></select><span class="mv-filter-count" data-manager-count aria-live="polite"></span></div>`;}
 function renderVMs(options) {
  const ctx=helpers(options),{esc,bytes,button,pill,empty}=ctx;if(!allowed(ctx,'vms'))return empty('Die VM-Verwaltung ist für dieses Konto nicht freigegeben.');
  const data=ctx.data||{},vms=Array.isArray(data.vms)?data.vms:[],library=ctx.library||{},items=Array.isArray(library.items)?library.items:[],summary=vmResourceSummary(vms),status=ctx.status||{},vmOptions=ctx.options||{};
  ctx.data=data;const active='machines';
  const warnings=(data.available===false?`<div class="mv-notice warning"><strong>Virtualisierung prüfen</strong><p>${esc(data.error||'Virtualisierung ist derzeit nicht verfügbar.')}</p>${ctx.session?.user?.role==='user'?'':button('VM-Dienste reparieren','component-install','data-component="vms"','small')}</div>`:'')+hintList(data.warnings,esc);
  const overview=`<div class="mv-section-title"><div><h2>Virtualisierung im Überblick</h2><p>Zuordnung deiner virtuellen Maschinen auf diesem NAS.</p></div>${pill(data.available===false?'Prüfen':'Bereit',data.available===false?'gray':'')}</div>${stats([{label:'Virtuelle Maschinen',value:vms.length,detail:summary.running+' laufen gerade'},{label:'Zugewiesene CPUs',value:summary.cpus,detail:'Virtuelle Prozessoren'},{label:'RAM-Verbrauch der VMs',live:'vm-total-memory',value:summary.memory===null?'Nicht ermittelt':bytes(summary.memory),detail:'Gemessener Host-RAM laufender und pausierter VMs'},{label:'Virtuelle Laufwerke',value:bytes(summary.disk),detail:'Virtuelle Größe; keine Belegungsmessung'}],esc)}<section class="mv-section"><h3>Maschinen</h3>${vms.length?`<div class="mv-overview-list">${vms.map(vm=>`<div><span class="mv-mini-icon">${icon('vm')}</span><strong>${esc(vm.name)}</strong><span>${number(vm.cpus)} vCPU · ${bytes(number(vm.memory_mb)*1024**2)}</span>${pill(state(vm.state),vm.state==='running'?'':'gray')}</div>`).join('')}</div>`:empty('Noch keine virtuellen Maschinen angelegt.')}<button type="button" class="button small" data-manager-select="machines">Maschinen verwalten →</button></section><div class="mv-info">RAM zeigt den gemessenen Verbrauch auf dem NAS. Ausgeschaltete VMs verbrauchen 0 B. CPU-Zuweisung und Laufwerkskapazität sind Konfigurationswerte.</div>`;
  const machines=`<div class="vm-machine-workspace"><section class="vm-master-pane" aria-label="Virtuelle Maschinen">${filterBar('vms','Maschinen suchen …')}<div class="vm-list-heading" aria-hidden="true"><span>Virtuelle Maschine</span><span>Konfiguration</span><span>CPU · RAM · Laufwerk live</span><span>Aktionen</span></div><div class="vm-master-list">${vms.map(vm=>vmRow(vm,ctx)).join('')}</div>${vms.length?'':empty(data.available===false?'Beachte die Hinweise zum Virtualisierungsstatus.':'Noch keine virtuellen Maschinen. Erstelle eine VM mit Installations-ISO oder Laufwerksimage.')}<p class="mv-no-results" data-manager-no-results hidden>Keine passenden Maschinen. Ändere Suchbegriff oder Statusfilter.</p><p class="vm-master-hint">Eine Maschine auswählen, um Hardware, Netzwerke, Sicherungen und Konsole zu öffnen.</p></section><section class="vm-selected-pane" data-vm-detail-host aria-label="Ausgewählte virtuelle Maschine" hidden></section></div>`;
  const media=`<div class="mv-section-title"><div><h2>Installationsmedien</h2><p>Vollständig hochgeladene ISO-Dateien für deine virtuellen Maschinen.</p></div><label class="button small primary">ISO hochladen<input id="iso-upload" type="file" accept=".iso" hidden></label></div><div id="upload-status">${typeof ctx.uploadStatus==='function'?ctx.uploadStatus():ctx.uploadStatus||''}</div><div class="mv-media-list">${items.map(item=>{const used=Array.isArray(item.used_by)?item.used_by:[];return `<article class="mv-media-row"><span class="mv-media-icon">${icon('disc')}</span><div><strong>${esc(item.name)}</strong><small>${bytes(number(item.size))} · ${used.length?'Verwendet von '+esc(used.join(', ')):'Keiner Titan-VM zugewiesen'}</small></div>${button('Entfernen','iso-remove',`data-name="${esc(item.name)}" ${used.length?'disabled':''}`,'small danger')}</article>`;}).join('')||empty('Noch keine Installationsmedien vorhanden.')} </div><p class="mv-hint">QCOW2- und RAW-Laufwerksimages wählst du beim Erstellen einer VM aus deinen Dateien. Diese Bibliothek enthält ausschließlich ISO-Installationsmedien.</p>`;
  const cpus=(Array.isArray(vmOptions.cpu_topology?.cpus)?vmOptions.cpu_topology.cpus:[]).filter(cpu=>Number.isInteger(cpu.id)&&cpu.id>=0).sort((a,b)=>a.id-b.id),types={performance:'P-Kern',efficiency:'E-Kern',standard:'Standardkern',unknown:'Typ nicht gemeldet'};
  const host=`<div class="mv-section-title"><div><h2>Host und Hardware</h2><p>Vom NAS gemeldete Hardware und verfügbare VM-Speicherziele.</p></div></div>${stats([{label:'Logische Host-CPUs',value:cpus.length||number(status.cpus)||'Nicht gemeldet',detail:cpus.length?cpus.filter(cpu=>cpu.online!==false).length+' online':''},{label:'Arbeitsspeicher des NAS',value:number(status.memory_total)?bytes(number(status.memory_total)):'Nicht gemeldet',detail:'Gesamter physischer Arbeitsspeicher'},{label:'VM-Speicherziele',value:Array.isArray(vmOptions.storage)?vmOptions.storage.filter(item=>item.available).length:'Nicht gemeldet',detail:'Derzeit verfügbare Ziele'}],esc)}<section class="mv-section"><h3>CPU-Topologie</h3><div class="mv-cpu-list">${cpus.map(cpu=>{const type=Object.hasOwn(types,cpu.core_type)?cpu.core_type:'unknown';return `<article class="mv-cpu mv-cpu-${type} ${cpu.online===false?'mv-cpu-offline':''}"><strong>CPU ${cpu.id}</strong><small>${types[type]}${cpu.online===false?' · Offline':''}</small>${cpu.core_id===undefined||cpu.core_id===null?'':`<small>Kern ${esc(cpu.core_id)}</small>`}${Array.isArray(cpu.siblings)&&cpu.siblings.some(id=>id!==cpu.id)?`<small>SMT: ${cpu.siblings.filter(id=>Number.isInteger(id)&&id!==cpu.id).map(id=>'CPU '+id).join(', ')}</small>`:''}</article>`;}).join('')||'<p class="mv-hint">Keine CPU-Topologie gemeldet. Automatische CPU-Zuweisung bleibt in der VM-Erstellung verfügbar.</p>'}</div><p class="mv-hint">P- und E-Kerne erscheinen nur, wenn der Host deren Typ zuverlässig meldet. Logische CPUs und SMT-Geschwister sind keine exklusiv reservierten Kerne.</p>${hintList(vmOptions.cpu_topology?.warnings,esc)}</section><section class="mv-section"><h3>Speicherziele</h3><div class="mv-storage-list">${(vmOptions.storage||[]).map(item=>`<article><div><strong>${esc(item.label||item.id)}</strong><code>${esc(item.path||'')}</code></div><span>${item.available?bytes(number(item.free_bytes))+' frei':'Nicht verfügbar'}</span></article>`).join('')||'<p class="mv-hint">Keine Speicherziele gemeldet.</p>'}</div>${hintList(vmOptions.warnings,esc)}</section>`;
  return shell('vms','VM Manager','vm',[['overview','Übersicht','grid'],['machines','Maschinen','list'],['media','Medien','disc'],['host','Host und Hardware','cpu']],active,`<div class="mv-toolbar-title">${icon('vm')}<strong>VM Manager</strong><span>${vms.length} Maschinen</span></div><div class="mv-toolbar-actions">${button('Aktualisieren','refresh','','small')}${button('VM erstellen','vm-create',data.available===false?'disabled':'','small primary')}</div>`,warnings+panel('vms','overview',overview,active)+panel('vms','machines',machines,active)+panel('vms','media',media,active)+panel('vms','host',host,active),button(`${icon('backup')}<span>VM-Sicherungen</span>`,'vm-backups','','mv-side-button'),`<span class="mv-status-dot ${data.available===false?'mv-status-warning':''}"></span>${data.available===false?'Virtualisierung prüfen':'Virtualisierung bereit'}`);
 }
 function appRow(app,ctx) {
  const {esc,button,pill,bytes}=ctx,container=app.container||app,running=app.state==='running',failed=app.phase==='failed',id=`data-id="${esc(app.id)}"`,available=ctx.data.available!==false;
  const endpoint=safeUrl(typeof ctx.connection==='function'?ctx.connection(app):''),summary=typeof ctx.networkSummary==='function'?ctx.networkSummary(app):container.network_mode==='host'?'Host-Netz · NAS-Adressen':(container.networks||[]).flatMap(item=>[item.ipv4,item.ipv6].filter(Boolean)).join(' · ')||'Container-IP nicht gemeldet';
  const port=Number(app.port),validPort=Number.isInteger(port)&&port>0&&port<=65535,search=[app.name,app.id,app.status,app.state,summary].join(' ').toLocaleLowerCase('de-DE');
  return `<article class="mv-container" data-manager-item data-manager-search="${esc(search)}" data-manager-state="${running?'running':'stopped'}"><div class="mv-container-summary"><span class="mv-app-icon" aria-hidden="true">${esc(String(app.name||app.id||'A').slice(0,1).toLocaleUpperCase('de-DE'))}</span><div class="mv-container-title"><h3>${esc(app.name||app.id)}</h3>${pill(state(app.state,failed),failed?'red':running?'':'gray')}<small>${esc(app.status||'')}</small></div><div class="mv-container-network"><span>Container-Adresse</span><code>${esc(summary)}</code><small>${validPort?'Webport '+port:'Kein Webport gemeldet'}${container.network_mode?' · '+esc(container.network_mode):''}</small></div><div class="mv-primary-actions">${button('Details & Anmeldung','app-manage',id,'small')}${running&&!ctx.session?.demo&&endpoint?`<a class="button small primary" href="${esc(endpoint)}" target="_blank" rel="noopener">Öffnen ↗</a>`:button(failed?'Erneut versuchen':running?'Stoppen':'Starten','app-action',`${id} data-command="${failed?'start':running?'stop':'start'}" ${available?'':'disabled'}`,'small primary')}</div></div><div class="vm-live-panel" data-app-live="${esc(app.id)}">${typeof window!=='undefined'?window.TitanAppLive?.render(null,{bytes})||'':''}</div><details class="mv-machine-details"><summary>Weitere Aktionen <span aria-hidden="true">⌄</span></summary><div class="mv-machine-detail-body">${app.last_error?`<p class="mv-warning">${esc(app.last_error)}</p>`:''}<dl class="mv-detail-list"><div><dt>App</dt><dd><code>${esc(app.id)}</code></dd></div><div><dt>Container-Image</dt><dd><code>${esc(container.image||'Im App-Dialog verfügbar')}</code></dd></div><div><dt>Netzwerk</dt><dd>${esc(summary)}</dd></div></dl><div class="mv-actions">${button('Starten','app-action',`${id} data-command="start" ${(!running||failed)&&available?'':'disabled'}`,'small')}${button('Stoppen','app-action',`${id} data-command="stop" ${running&&available?'':'disabled'}`,'small')}${button('Neustarten','app-action',`${id} data-command="restart" ${running&&available?'':'disabled'}`,'small')}${button('Konfiguration sichern','app-action',`${id} data-command="backup" ${available?'':'disabled'}`,'small')}${button('App aktualisieren','app-action',`${id} data-command="update" ${available?'':'disabled'}`,'small')}${button('App entfernen','app-action',`${id} data-command="remove" ${available?'':'disabled'}`,'small danger')}</div><p class="mv-hint">Entfernen behält Konfiguration und Nutzdaten. Für Anmeldung, vollständige Netzwerkadressen und Protokolle öffne „Details & Anmeldung“.</p></div></details></article>`;
 }
 function renderApps(options) {
  const ctx=helpers(options),{esc,button,pill,empty}=ctx;if(!allowed(ctx,'apps'))return empty('Die App-Verwaltung ist für dieses Konto nicht freigegeben.');
  const data=ctx.data||{},apps=Array.isArray(data.installed)?data.installed:[],running=apps.filter(app=>app.state==='running').length,failed=apps.filter(app=>app.phase==='failed').length,active='containers';ctx.data=data;
  const warning=(data.available===false?`<div class="mv-notice warning"><strong>Docker prüfen</strong><p>${esc(data.error||'Docker ist derzeit nicht verfügbar.')}</p>${ctx.session?.user?.role==='user'?'':button('Docker-Dienste reparieren','component-install','data-component="docker"','small')}</div>`:'')+hintList(data.warnings,esc);
  const overview=`<div class="mv-section-title"><div><h2>Deine Container im Überblick</h2><p>Installierte Titan-Apps und ihr aktueller Betriebsstatus.</p></div>${pill(data.available===false?'Prüfen':'Bereit',data.available===false?'gray':'')}</div>${stats([{label:'Installierte Apps',value:apps.length},{label:'Laufende Apps',value:running},{label:'Gestoppt / andere',value:apps.length-running},{label:'Fehlgeschlagene Installationen',value:failed}],esc)}<section class="mv-section"><h3>Anwendungen installieren</h3><p class="mv-hint">Im App Store wählst du eine Vorlage aus. Port, Datenfreigabe und Docker-Netzwerk legst du vor der Installation fest.</p><a class="button small primary" href="#apps">App Store öffnen →</a><button type="button" class="button small" data-action="jobs">Aktivität öffnen →</button></section><section class="mv-section"><h3>Netzwerk und Zugang</h3><p class="mv-hint">Container-Adressen stehen bei den installierten Apps. „Details & Anmeldung“ zeigt NAS-Adressen, Ports, Protokolle und den beschriebenen ersten Login.</p>${button('Docker-Netzwerke öffnen','app-networks','','small')}</section>`;
  const containers=`<div class="mv-section-title"><div><h2>Installierte Container</h2><p>Deine Apps starten, verwalten und direkt öffnen.</p></div><button type="button" class="mv-text-link" data-action="jobs">Aktivität öffnen →</button></div>${filterBar('docker','Container suchen …')}<div class="mv-container-list">${apps.map(app=>appRow(app,ctx)).join('')}</div>${apps.length?'':empty('Noch keine Apps installiert. Entdecke Anwendungen im App Store.')}<p class="mv-no-results" data-manager-no-results hidden>Keine passenden Container. Ändere Suchbegriff oder Statusfilter.</p>`;
  return shell('docker','Docker Manager','docker',[['overview','Übersicht','grid'],['containers','Container','list']],active,`<div class="mv-toolbar-title">${icon('docker')}<strong>Docker Manager</strong><span>${apps.length} Apps</span></div><div class="mv-toolbar-actions">${button('Aktualisieren','refresh','','small')}<a class="button small primary" href="#apps">App installieren</a></div>`,warning+panel('docker','overview',overview,active)+panel('docker','containers',containers,active),button(`${icon('network')}<span>Netzwerke</span>`,'app-networks','','mv-side-button')+`<a class="mv-side-link" href="#apps">${icon('store')}<span>App Store</span></a>`,`<span class="mv-status-dot ${data.available===false?'mv-status-warning':''}"></span>${data.available===false?'Docker prüfen':'Docker bereit'}`);
 }
 function mount(root,ctx={}) {
  const manager=root?.querySelector?.('[data-manager]');if(!manager)return null;
  dispose();const key=manager.dataset.manager,owner=String(ctx.owner||''),preferenceKey=owner+'\0'+key,tabs=[...manager.querySelectorAll('[data-manager-tab]')],panels=[...manager.querySelectorAll('[data-manager-panel]')],items=[...manager.querySelectorAll('[data-manager-item]')],search=manager.querySelector('[data-manager-search-input]'),status=manager.querySelector('[data-manager-state-filter]'),count=manager.querySelector('[data-manager-count]'),noResults=manager.querySelector('[data-manager-no-results]');
  let disposed=false;
  function select(value,focus=false) {
   if(disposed||!tabs.some(tab=>tab.dataset.managerTab===value))return false;
   tabs.forEach(tab=>{const selected=tab.dataset.managerTab===value;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;if(selected&&focus)tab.focus?.({preventScroll:true});});
   panels.forEach(panel=>panel.hidden=panel.dataset.managerPanel!==value);
   if(key==='vms'&&value!=='machines'&&typeof window!=='undefined')window.TitanVMExtensions?.closeSelection?.(manager);
   manager.dataset.managerView=value;
   const previous=preferences.get(preferenceKey)||{};preferences.set(preferenceKey,{...previous,view:value});return true;
  }
  function filter() {
   if(disposed)return;
   const query=String(search?.value||'').toLocaleLowerCase('de-DE').trim(),words=query.split(/\s+/).filter(Boolean),selected=status?.value||'';let visible=0;
   items.forEach(item=>{item.hidden=!words.every(word=>String(item.dataset.managerSearch||'').includes(word))||Boolean(selected&&item.dataset.managerState!==selected);if(!item.hidden)visible++;});
   if(count)count.textContent=`${visible} von ${items.length}`;
   if(noResults)noResults.hidden=Boolean(visible)||!items.length;
   const previous=preferences.get(preferenceKey)||{};preferences.set(preferenceKey,{...previous,query:search?.value||'',status:selected});
  }
  const click=event=>{const tab=event.target.closest?.('[data-manager-tab]'),shortcut=event.target.closest?.('[data-manager-select]');if(tab&&manager.contains(tab)){event.preventDefault();select(tab.dataset.managerTab);}else if(shortcut&&manager.contains(shortcut)){event.preventDefault();select(shortcut.dataset.managerSelect,true);}};
  const keydown=event=>{const tab=event.target.closest?.('[data-manager-tab]');if(!tab||!manager.contains(tab)||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const index=tabs.indexOf(tab);let target=event.key==='Home'?0:event.key==='End'?tabs.length-1:((index+(['ArrowDown','ArrowRight'].includes(event.key)?1:-1)+tabs.length)%tabs.length);event.preventDefault();select(tabs[target].dataset.managerTab,true);};
  manager.addEventListener('click',click);manager.addEventListener('keydown',keydown);search?.addEventListener('input',filter);status?.addEventListener('change',filter);
  const preference=preferences.get(preferenceKey);if(preference){if(search)search.value=preference.query||'';if(status)status.value=['running','stopped'].includes(preference.status)?preference.status:'';}
  select(preference?.view||tabs.find(tab=>tab.getAttribute('aria-selected')==='true')?.dataset.managerTab||tabs[0]?.dataset.managerTab);filter();
  const instance={select,filter,dispose(){if(disposed)return;disposed=true;manager.removeEventListener('click',click);manager.removeEventListener('keydown',keydown);search?.removeEventListener('input',filter);status?.removeEventListener('change',filter);views.delete(manager);}};
  views.set(manager,instance);return instance;
 }
 function dispose() {for(const instance of [...views.values()])instance.dispose();}
 const exports={renderVMs,renderApps,mount,dispose,vmResourceSummary,safeUrl};
 if(typeof window!=='undefined')window.TitanManagers=exports;
 if(typeof module!=='undefined'&&module.exports)module.exports=exports;
})();
