'use strict';
(function(root,factory){const ui=factory();if(root)root.TitanMonitoring=ui;if(typeof module==='object')module.exports=ui;})(typeof window==='undefined'?null:window,function(){
 let current=null;
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const levels={critical:'Kritisch',error:'Fehler',warning:'Warnung',info:'Information'};
 const routes=new Set(['storage','resources','services','backups','updates','apps','vms','shares','monitoring','settings?section=network']);
 const labels={web:'Weboberfläche',agent:'Verwaltung',https:'HTTPS',docker:'Docker',samba:'SMB-Freigaben',zfs:'ZFS',vms:'Virtualisierung'};
 function sortedAlerts(alerts){const level={critical:4,error:3,warning:2,info:1};return [...alerts].sort((a,b)=>(b.active!==false)-(a.active!==false)||(level[b.severity]||0)-(level[a.severity]||0)||Number(b.last_seen||0)-Number(a.last_seen||0));}
 function matches(alert,state='active',level=''){return (!level||alert.severity===level)&&(state==='all'||state==='resolved'&&alert.active===false||state==='active'&&alert.active!==false||state==='unread'&&alert.active!==false&&!alert.acknowledged);}
 function render(data,settings,{date,button,pill}){
  const alerts=sortedAlerts(data.alerts||[]),services=Object.entries(data.services||{}).filter(([,s])=>s.relevant===true||s.relevant===undefined&&s.installed),open=alerts.filter(a=>a.active!==false&&!a.acknowledged).length;
  return `<div data-monitoring-center><div class="two-columns"><section class="panel"><h2>Aktive Systemkomponenten</h2>${services.map(([name,s])=>`<div class="list-row"><span class="row-main"><strong>${esc(labels[name]||name)}</strong><small>${esc(s.error||s.state||'')}</small></span>${pill(s.active?'Bereit':'Prüfen',s.active?'':'red')}</div>`).join('')||'<p>Keine Komponenten gemeldet.</p>'}</section><section class="panel"><h2>Laufwerkszustand</h2>${(data.disks||[]).map(d=>`<div class="list-row"><span class="row-main"><strong>${esc(d.name)}</strong><small>${esc(d.error||[String(d.health).toLowerCase()==='passed'?'SMART unauffällig':String(d.health).toLowerCase()==='failed'?'SMART-Fehler':'SMART nicht verfügbar',Number.isFinite(d.temperature)?d.temperature+' °C':''].filter(Boolean).join(' · '))}</small></span>${button('Details','smart',`data-disk="${esc(d.name)}"`,'small')}</div>`).join('')||'<p class="hint">Noch keine Laufwerksprüfung vorhanden.</p>'}</section></div><section class="panel"><div class="panel-heading"><h2>Meldungen und Verlauf</h2><span data-monitoring-count>${open} offene Meldungen</span></div><p class="hint">Letzte Systemprüfung: ${data.checked?date(data.checked):'Noch keine'}</p><div class="monitoring-controls"><label>Anzeigen<select data-alert-state><option value="active">Aktuelle Meldungen</option><option value="unread">Offen und unbestätigt</option><option value="all">Gesamter Verlauf</option><option value="resolved">Behobene Meldungen</option></select></label><label>Priorität<select data-alert-level><option value="">Alle Prioritäten</option>${Object.entries(levels).map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select></label></div><div data-alert-list>${alerts.map(a=>`<article class="monitoring-event ${Object.hasOwn(levels,a.severity)?a.severity:'info'} ${a.active===false?'resolved':''}" data-alert-id="${esc(a.id)}"><span class="monitoring-event-indicator" aria-hidden="true"></span><div><span class="notification-priority ${Object.hasOwn(levels,a.severity)?a.severity:'info'}">${levels[a.severity]||'Information'}</span><h3>${esc(a.title)}</h3><p>${esc(a.message||a.detail)}</p><small>${date(a.last_seen||a.first_seen||a.time)} · ${a.active===false?'Behoben'+(a.resolved_at?' am '+date(a.resolved_at):''):a.acknowledged?'Bestätigt':'Offen'}</small></div><div class="monitoring-event-actions">${routes.has(a.route)?`<a class="button small" href="#${esc(a.route)}">Bereich öffnen</a>`:''}${!a.acknowledged&&a.active!==false?button('Bestätigen','alert-ack',`data-id="${esc(a.id)}"`,'small'):''}</div></article>`).join('')}<p class="hint" data-alert-empty ${alerts.length?'hidden':''}>Keine passenden Meldungen.</p></div></section>${notificationForm(settings,data.delivery)}</div>`;
 }
 function notificationForm(settings={},delivery={}){
  return `<details class="panel"><summary>E-Mail-Benachrichtigungen</summary><form data-notification-form><label class="check-label"><input name="enabled" type="checkbox" ${settings.enabled?'checked':''}>Systemmeldungen zusätzlich per E-Mail senden</label><div class="form-grid"><label>SMTP-Server<input name="host" type="text" maxlength="253" value="${esc(settings.host||'')}" placeholder="smtp.example.org" autocomplete="off"></label><label>Port<input name="port" type="number" min="1" max="65535" required value="${Number(settings.port||587)}"></label></div><label>Verschlüsselung<select name="tls"><option value="starttls" ${settings.tls!=='tls'?'selected':''}>STARTTLS · meistens Port 587</option><option value="tls" ${settings.tls==='tls'?'selected':''}>TLS · meistens Port 465</option></select></label><div class="form-grid"><label>Benutzername<input name="username" type="text" maxlength="320" value="${esc(settings.username||'')}" autocomplete="off"></label><label>SMTP-Passwort<input name="password" type="password" maxlength="4096" value="" autocomplete="new-password" placeholder="${settings.password_set?'Gespeichert · leer lassen zum Behalten':'Optional'}"></label></div><label>Absenderadresse<input name="sender" type="email" maxlength="254" value="${esc(settings.sender||'')}"></label><label>Empfänger<input name="recipients" type="text" value="${esc((settings.recipients||[]).join(', '))}" placeholder="name@example.org, zweite@example.org"></label><label>Benachrichtigen ab<select name="minimum_severity">${['info','warning','error','critical'].map(key=>`<option value="${key}" ${(settings.minimum_severity||'warning')===key?'selected':''}>${levels[key]}</option>`).join('')}</select></label><p class="hint">Neue Meldungen werden zusammengefasst. Wiederholte Prüfungen senden dieselbe Meldung nicht erneut. Bei einer neuen Störung oder höherer Priorität wird erneut benachrichtigt.</p>${delivery?.error?`<p class="notice warning">${esc(delivery.error)}</p>`:''}<p role="status" aria-live="polite" data-notification-status></p><div class="form-actions wrap"><button type="submit" class="button primary">Speichern</button><button type="button" class="button" data-notification-test>Testnachricht senden</button></div></form></details>`;
 }
 function notificationSettings(form){const data=new FormData(form);return {enabled:data.has('enabled'),host:data.get('host').trim(),port:Number(data.get('port')),tls:data.get('tls'),username:data.get('username'),password:data.get('password'),sender:data.get('sender').trim(),recipients:data.get('recipients').split(/[,;\n]/).map(v=>v.trim()).filter(Boolean),minimum_severity:data.get('minimum_severity')};}
 function mount(main,ctx){
  dispose();const surface=main.querySelector('[data-monitoring-center]');if(!surface)return;let alive=true,busy=false;const form=surface.querySelector('[data-notification-form]'),state=surface.querySelector('[data-alert-state]'),level=surface.querySelector('[data-alert-level]'),index=new Map((ctx.data.alerts||[]).map(a=>[a.id,a]));
  function filter(){let count=0;surface.querySelectorAll('[data-alert-id]').forEach(node=>{node.hidden=!matches(index.get(node.dataset.alertId),state.value,level.value);if(!node.hidden)count++;});surface.querySelector('[data-alert-empty]').hidden=count!==0;}
  async function save(event){event.preventDefault();if(busy)return;busy=true;const button=form.querySelector('button[type=submit]'),status=form.querySelector('[data-notification-status]');button.disabled=true;try{await ctx.api('/api/notifications/settings',notificationSettings(form));if(alive){form.elements.password.value='';form.elements.password.placeholder='Gespeichert · leer lassen zum Behalten';status.textContent='Benachrichtigungen gespeichert.';}}catch(error){if(alive)status.textContent=error.message;}finally{busy=false;if(alive)button.disabled=false;}}
  async function test(event){if(!event.target.closest('[data-notification-test]')||busy)return;busy=true;const status=form.querySelector('[data-notification-status]');try{status.textContent='Testnachricht wird gesendet …';await ctx.action('notification_test',{});if(alive)status.textContent='Versand gestartet. Das Ergebnis erscheint bei der Aktivität.';}catch(error){if(alive)status.textContent=error.message;}finally{busy=false;}}
  state.addEventListener('change',filter);level.addEventListener('change',filter);form.addEventListener('submit',save);form.addEventListener('click',test);filter();current={destroy(){alive=false;state.removeEventListener('change',filter);level.removeEventListener('change',filter);form.removeEventListener('submit',save);form.removeEventListener('click',test);}};return current;
 }
 function dispose(){current?.destroy();current=null;}
 return {render,sortedAlerts,matches,notificationForm,notificationSettings,mount,dispose};
});
