'use strict';
// Own photo workspace. The file service remains the authority for originals.
(function(root,factory){const app=factory();if(typeof module==='object'&&module.exports)module.exports=app;if(root)root.TitanPhotos=app;})(typeof window==='undefined'?null:window,function(){
 const preferences=new Map();let current=null;
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const glyph={photo:'<rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8" cy="8" r="2"/><path d="m4 18 6-7 4 4 3-5 4 6"/>',heart:'<path d="M20 4a5 5 0 0 0-8 2 5 5 0 0 0-8-2c-5 5 3 11 8 16 5-5 13-11 8-16z"/>',album:'<rect x="3" y="4" width="17" height="17" rx="3"/><path d="M7 4V2m5 2V2m5 2V2M7 9h9m-9 5h6"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/>',folder:'<path d="M3 6h7l2 3h9v11H3z"/>'};
 const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${glyph[name]||glyph.photo}</svg>`;
 function state(owner=''){if(!preferences.has(owner))preferences.set(owner,{library:'',album:'',favorite:false,trash:false,search:'',offset:0});return preferences.get(owner);}
 function query(selection={}){const values={offset:String(selection.offset||0),limit:'80'};for(const key of ['library','album','search'])if(selection[key])values[key]=String(selection[key]);if(selection.favorite)values.favorite='1';if(selection.trash)values.trash='1';return '/api/photos?'+new URLSearchParams(values);}
 const preview=item=>'/api/photos/preview?'+new URLSearchParams({photo:item.id,v:item.revision||String(item.modified)});
 const original=item=>'/api/photos/original?'+new URLSearchParams({photo:item.id});
 function day(value){const date=new Date(Number(value)*1000);return Number.isFinite(date.getTime())?date.toLocaleDateString('de-DE',{day:'numeric',month:'long',year:'numeric'}):'Ohne Datum';}
 function grouped(items){const groups=[];for(const item of items){const label=day(item.taken);if(groups[groups.length-1]?.label!==label)groups.push({label,items:[]});groups[groups.length-1].items.push(item);}return groups;}
 function viewTitle(data,selection){if(selection.trash)return 'Papierkorb';if(selection.favorite)return 'Favoriten';if(selection.album)return data.albums.find(row=>row.id===selection.album)?.name||'Album';if(selection.library)return data.libraries.find(row=>row.id===selection.library)?.name||'Fotobibliothek';return 'Alle Fotos';}
 function button(label,cmd,attributes='',kind=''){return `<button type="button" class="button ${kind}" data-photo-command="${cmd}" ${attributes}>${label}</button>`;}
 function renderContent(data,selection){
  const navButton=(name,cmd,active,id='',symbol='photo')=>`<button type="button" class="photos-location ${active?'is-active':''}" data-photo-command="${cmd}" ${id?`data-id="${esc(id)}"`:''} ${active?'aria-current="page"':''}>${icon(symbol)}<span>${esc(name)}</span></button>`;
  const activeLibrary=data.libraries.find(row=>row.id===selection.library),uploadable=data.libraries.some(row=>row.available&&row.writable!==false);
  return `<aside class="photos-sidebar" aria-label="Fotoansichten">${navButton('Alle Fotos','all',!selection.library&&!selection.album&&!selection.favorite&&!selection.trash)}${navButton('Favoriten','favorites',selection.favorite,'','heart')}${navButton('Papierkorb','trash-view',selection.trash,'','trash')}<div class="photos-sidebar-heading"><strong>Bibliotheken</strong>${button('+','library-create','aria-label="Fotoordner hinzufügen"','small')}</div>${data.libraries.map(row=>navButton(row.name+(row.available?'':' · Nicht verfügbar'),'library',selection.library===row.id,row.id,'folder')).join('')}<div class="photos-sidebar-heading"><strong>Alben</strong>${button('+','album-create','aria-label="Album erstellen"','small')}</div>${data.albums.map(row=>navButton(row.name,'album',selection.album===row.id,row.id,'album')).join('')}<p class="photos-private-note">Deine Bibliotheken, Alben und Favoriten gehören zu deinem Titan-Konto. Dateirechte gelten auch hier.</p></aside>
   <section class="photos-main"><header class="photos-toolbar"><div><span class="eyebrow">FOTOS</span><h1>${esc(viewTitle(data,selection))}</h1><span class="hint">${Number(data.total).toLocaleString('de-DE')} Fotos</span></div><div class="photos-toolbar-actions">${button('Fotoordner hinzufügen','library-create','','small')}${button('↻','refresh','aria-label="Fotoansicht aktualisieren" title="Aktualisieren"','small')}${uploadable&&!selection.trash?button('Hochladen','upload','','primary'):''}${activeLibrary?button('Bibliothek verwalten','library-manage',`data-id="${esc(activeLibrary.id)}"`,'small'):''}${selection.album?button('Album verwalten','album-manage',`data-id="${esc(selection.album)}"`,'small'):''}</div></header>
   <form class="photos-search" data-photo-search><input name="search" type="search" value="${esc(selection.search)}" placeholder="Fotos nach Dateinamen suchen" aria-label="Fotos nach Dateinamen suchen" maxlength="200"><button class="button small" type="submit">Suchen</button></form>
   ${data.indexing?'<div class="photos-index-status" role="status"><span class="photos-index-dot" aria-hidden="true"></span><span>Fotoordner werden im Hintergrund eingelesen. Du kannst Titan weiter benutzen.</span><strong>'+data.libraries.filter(row=>['queued','scanning'].includes(row.state)).reduce((total,row)=>total+Number(row.indexed||0),0).toLocaleString('de-DE')+' Fotos</strong></div>':''}
   ${activeLibrary?.error?`<p class="notice" role="status">${esc(activeLibrary.error)}</p>`:''}
   <div class="photos-gallery-scroll" data-photo-gallery tabindex="0" aria-label="Fotogalerie">${data.items.length?grouped(data.items).map(group=>`<section class="photos-day"><h2>${esc(group.label)}</h2><div class="photos-grid">${group.items.map(item=>`<article class="photos-card"><button type="button" class="photos-image" data-photo-command="${selection.trash?'trash-details':'open'}" data-id="${esc(item.id)}" aria-label="${esc(item.name)} öffnen">${selection.trash||item.error?`<span class="photos-placeholder">${icon(selection.trash?'trash':'photo')}</span>`:`<img src="${esc(preview(item))}" alt="" loading="lazy" decoding="async" width="160" height="160">`}${item.favorite?'<span class="photos-favorite-mark" aria-label="Favorit">♥</span>':''}</button><div class="photos-card-caption"><strong title="${esc(item.name)}">${esc(item.name)}</strong><span>${esc(item.error?'Vorschau nicht verfügbar':item.library_name)}</span><button type="button" class="photos-card-menu" data-photo-command="${selection.trash?'trash-details':'open'}" data-id="${esc(item.id)}" aria-label="${esc(item.name)}: Aktionen">⋯</button></div></article>`).join('')}</div></section>`).join(''):`<div class="photos-empty">${icon('photo')}<h2>${data.libraries.length?'Hier sind noch keine Fotos.':'Deine Fotos bekommen ein Zuhause.'}</h2><p>${selection.trash?'Gelöschte Fotos aus dieser Anwendung kannst du hier wiederherstellen.':data.libraries.length?'Wähle einen anderen Bereich oder lies deinen Fotoordner erneut ein.':'Wähle einen vorhandenen Fotoordner im internen Speicher, in einem Pool oder einer Freigabe.'}</p>${!data.libraries.length?button('Fotoordner hinzufügen','library-create','','primary'):''}</div>`}</div>
   <footer class="photos-pagination"><span>${data.total?`${Number(data.offset)+1}–${Math.min(Number(data.offset)+data.items.length,Number(data.total))} von ${Number(data.total).toLocaleString('de-DE')}`:'0 Fotos'}</span><div>${button('← Zurück','previous',data.offset?'':'disabled','small')}${button('Weiter →','next',data.has_more?'':'disabled','small')}</div></footer></section>
   <dialog class="photos-lightbox" data-photo-lightbox aria-label="Foto ansehen"></dialog>
   <dialog class="photos-settings" data-photo-settings></dialog><input data-photo-upload type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple hidden>`;
 }
 function render(data,options={}){return `<div class="photos-workbench" data-photos-workbench>${renderContent(data,state(options.owner))}</div>`;}
 function dispose(){current?.destroy();current=null;}
 function mount(node,options={}){
  dispose();if(!node||!options.api)return null;
  const selection=state(options.owner),controller=new AbortController(),doc=node.ownerDocument;
  let data=options.data,alive=true,poll=null,request=0,busy=false,openId='',restoreFocus=null,uploadLibrary='';
  const find=selector=>node.querySelector(selector),listen=(target,type,callback)=>target?.addEventListener(type,callback,{signal:controller.signal});
  const lightbox=()=>find('[data-photo-lightbox]'),settings=()=>find('[data-photo-settings]');
  async function mutate(body){return options.api('/api/photos',body);}
  function startPoll(){if(poll)clearTimeout(poll);poll=null;if(alive)poll=setTimeout(()=>{if(doc.visibilityState==='hidden'||lightbox().open||settings().open){startPoll();return;}reload().catch(error=>options.toast?.(error.message,true));},data.indexing?4000:30000);}
  function draw(){window.TitanFolderPicker?.disposeWithin(node);node.innerHTML=renderContent(data,selection);startPoll();}
  async function reload(){const mine=++request,result=await options.api(query(selection));if(!alive||mine!==request)return;data=result;draw();}
  function setView(values){Object.assign(selection,{library:'',album:'',favorite:false,trash:false,offset:0},values);return reload();}
  const record=id=>data.items.find(row=>row.id===id);
  function showPhoto(id){
   const item=record(id);if(!item)return;openId=id;const modal=lightbox(),index=data.items.indexOf(item);
   const albumPicker=data.albums.length?`<label>Zu Album hinzufügen<select data-photo-album-target aria-label="Album auswählen"><option value="">Album auswählen …</option>${data.albums.map(row=>`<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('')}</select></label>`:'';
   modal.innerHTML=`<header><h2>${esc(item.name)}</h2>${button('×','viewer-close','aria-label="Fotoansicht schließen"','small')}</header><div class="photos-lightbox-image">${item.trashed?`<div class="photos-empty">${icon('trash')}<p>Das Original liegt im Papierkorb und kann wiederhergestellt werden.</p></div>`:`<img src="${esc(original(item)+'&preview=1')}" alt="${esc(item.name)}">`}</div><div class="photos-lightbox-details"><span>${esc(day(item.taken))}${item.width&&item.height?' · '+item.width+' × '+item.height:''} · ${esc(options.bytes?.(item.size)||String(item.size)+' B')}</span><span>${esc(item.library_name)}</span>${item.error?`<p class="hint">${esc(item.error)}</p>`:''}</div><footer>${item.trashed?button('Wiederherstellen','restore',`data-id="${esc(item.id)}"`,'primary'):`<a class="button small" href="${esc(original(item))}" download>Original herunterladen</a>${button(item.favorite?'♥ Favorit entfernen':'♡ Favorit','favorite',`data-id="${esc(item.id)}"`,'small')}${albumPicker}${selection.album?button('Aus Album entfernen','album-unlink',`data-id="${esc(item.id)}"`,'small'):''}${data.libraries.find(row=>row.id===item.library)?.writable===false?'':button('Papierkorb','trash',`data-id="${esc(item.id)}"`,'danger small')}`}<div class="photos-viewer-navigation">${button('←','photo-previous',index>0?'aria-label="Vorheriges Foto"':'aria-label="Vorheriges Foto" disabled','small')}${button('→','photo-next',index<data.items.length-1?'aria-label="Nächstes Foto"':'aria-label="Nächstes Foto" disabled','small')}</div></footer>`;
   if(!modal.open){restoreFocus=doc.activeElement;modal.showModal();}
  }
  function closeViewer(){lightbox().close();restoreFocus?.focus?.({preventScroll:true});openId='';}
  function showSettings(title,html,onSubmit){const modal=settings();modal.innerHTML=`<header><h2>${esc(title)}</h2>${button('×','settings-close','aria-label="Dialog schließen"','small')}</header>${html}`;modal.showModal();const form=modal.querySelector('form');if(form)listen(form,'submit',async event=>{event.preventDefault();const submit=form.querySelector('[type=submit]');submit.disabled=true;try{const result=await onSubmit(new FormData(form));if(!alive||result===false)return;window.TitanFolderPicker?.disposeWithin(modal);modal.close();await reload();}catch(error){options.toast?.(error.message,true);}finally{if(submit.isConnected)submit.disabled=false;}});return modal;}
  const formEnd=label=>`<div class="form-actions">${button('Abbrechen','settings-close')}<button type="submit" class="button primary">${esc(label)}</button></div></form>`;
  function createLibrary(){
   if(!data.sources.length){options.toast?.('Zuerst einen Speicherbereich oder eine Freigabe einrichten.',true);return;}
   const modal=showSettings('Fotoordner hinzufügen',`<form><label class="field">Name der Bibliothek<input name="name" required maxlength="80" placeholder="Zum Beispiel Familienfotos"></label><label class="field">Speicherbereich<select name="source" required>${data.sources.map(row=>`<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('')}</select></label><input type="hidden" name="share" value="${esc(data.sources[0].share)}">${window.TitanFolderPicker.render({pathField:'path',shareField:'share',initialPath:data.sources[0].path})}<p class="hint">Originale bleiben an ihrem Speicherort. Titan liest JPEG, PNG, WebP und GIF ein. Vorschaubilder werden mit begrenzter Last erstellt.</p>${formEnd('Bibliothek hinzufügen')}`,values=>mutate({action:'library_add',name:values.get('name'),source:values.get('source'),path:values.get('path')}));
   let picker=window.TitanFolderPicker.mount(modal,{api:options.api,pathField:'path',shareField:'share',initialPath:data.sources[0].path});
   listen(modal.querySelector('[name=source]'),'change',event=>{const source=data.sources.find(row=>row.id===event.target.value);if(!source)return;window.TitanFolderPicker.disposeWithin(modal);modal.querySelector('[name=share]').value=source.share;picker=window.TitanFolderPicker.mount(modal,{api:options.api,pathField:'path',shareField:'share',initialPath:source.path});});
  }
  async function libraryManage(id){const library=data.libraries.find(row=>row.id===id);if(!library)return;showSettings(library.name,`<p>${esc(library.available?'Der Fotoordner ist erreichbar.':'Fotoordner nicht erreichbar. Speicher und Rechte prüfen.')}</p><p class="hint">${esc(library.error||'Einlesen findet neue und geänderte Fotos. Deine Alben und Favoriten bleiben erhalten.')}</p><div class="photos-settings-actions">${button('Ordner erneut einlesen','scan',`data-id="${esc(id)}" ${library.available?'':'disabled'}`,'primary')}${button('Bibliothek entfernen','library-remove',`data-id="${esc(id)}"`,'danger')}</div><p class="hint">Bibliothek entfernen löscht nur den Index. Deine Originaldateien bleiben erhalten.</p>`);}
  async function uploadFiles(files){const library=data.libraries.find(row=>row.id===uploadLibrary&&row.available&&row.writable!==false);if(!library)throw new Error('Einen erreichbaren Fotoordner auswählen.');busy=true;try{for(const file of files){if(!/\.(jpe?g|png|webp|gif)$/i.test(file.name))throw new Error('Wähle JPEG, PNG, WebP oder GIF.');options.toast?.(`${file.name} wird hochgeladen …`);let offset=0;do{const bytes=new Uint8Array(await file.slice(offset,offset+1024*1024).arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await options.api('/api/photos/upload',{library:library.id,name:file.name,offset,data:btoa(binary)});offset=result.offset;}while(offset<file.size);}await mutate({action:'scan',library:library.id});options.toast?.('Fotos hochgeladen. Vorschaubilder werden erstellt.');await reload();}finally{busy=false;}}
  async function command(cmd,id){
   if(busy){options.toast?.('Bitte den laufenden Foto-Upload abwarten.');return;}
   if(cmd==='all')return setView({});if(cmd==='favorites')return setView({favorite:true});if(cmd==='trash-view')return setView({trash:true});if(cmd==='library')return setView({library:id});if(cmd==='album')return setView({album:id});
   if(cmd==='previous'||cmd==='next'){selection.offset=Math.max(0,selection.offset+(cmd==='next'?80:-80));return reload();}
   if(cmd==='refresh')return reload();if(cmd==='library-create')return createLibrary();if(cmd==='library-manage')return libraryManage(id);
   if(cmd==='settings-close'){window.TitanFolderPicker?.disposeWithin(settings());settings().close();return;}if(cmd==='viewer-close'){closeViewer();return reload();}
   if(cmd==='open'||cmd==='trash-details')return showPhoto(id);
   if(cmd==='photo-next'||cmd==='photo-previous'){const index=data.items.findIndex(row=>row.id===openId)+(cmd==='photo-next'?1:-1);if(data.items[index])showPhoto(data.items[index].id);return;}
   if(cmd==='album-create'){return showSettings('Album erstellen',`<form><label class="field">Albumname<input name="name" required maxlength="80" placeholder="Zum Beispiel Urlaub"></label><p class="hint">Ein Album gruppiert Fotos, ohne Originale zu verschieben.</p>${formEnd('Album erstellen')}`,values=>mutate({action:'album_create',name:values.get('name')}));}
   if(cmd==='album-manage'){const album=data.albums.find(row=>row.id===id);if(album)showSettings(album.name,`<p>Beim Entfernen des Albums bleiben alle Fotos erhalten.</p>${button('Album entfernen','album-remove',`data-id="${esc(id)}"`,'danger')}`);return;}
   if(cmd==='upload'){const libraries=data.libraries.filter(row=>row.available&&row.writable!==false);showSettings('Fotos hochladen',`<form><label class="field">Zielbibliothek<select name="library">${libraries.map(row=>`<option value="${esc(row.id)}" ${row.id===selection.library?'selected':''}>${esc(row.name)}</option>`).join('')}</select></label><p class="hint">Vorhandene Dateien werden nicht überschrieben. Die Dateirechte des Zielordners gelten.</p>${formEnd('Dateien auswählen')}`,async values=>{uploadLibrary=values.get('library');settings().close();find('[data-photo-upload]').click();return false;});return;}
   if(cmd==='favorite'){const item=record(id);await mutate({action:'favorite',photo:id,value:!Boolean(item.favorite)});item.favorite=!item.favorite;showPhoto(id);return;}
   if(cmd==='scan'){await mutate({action:'scan',library:id});settings().close();return reload();}
   if(cmd==='library-remove'||cmd==='album-remove'){if(!await options.confirm?.(cmd==='library-remove'?'Fotobibliothek entfernen? Deine Originaldateien bleiben erhalten.':'Album entfernen? Alle Fotos bleiben erhalten.'))return;await mutate(cmd==='library-remove'?{action:'library_remove',library:id}:{action:'album_remove',album:id});return setView({});}
   if(cmd==='trash'){if(!await options.confirm?.('Dieses Foto in den Papierkorb verschieben?'))return;await mutate({action:'trash',photo:id});closeViewer();return reload();}
   if(cmd==='restore'){await mutate({action:'restore',photo:id});closeViewer();return reload();}
   if(cmd==='album-unlink'){await mutate({action:'album_unlink',album:selection.album,photo:id});closeViewer();return reload();}
  }
  listen(node,'click',event=>{const target=event.target.closest?.('[data-photo-command]');if(!target||target.disabled)return;event.preventDefault();Promise.resolve(command(target.dataset.photoCommand,target.dataset.id)).catch(error=>options.toast?.(error.message,true));});
  listen(node,'submit',event=>{if(!event.target.matches('[data-photo-search]'))return;event.preventDefault();selection.search=String(new FormData(event.target).get('search')||'');selection.offset=0;reload().catch(error=>options.toast?.(error.message,true));});
  listen(node,'change',event=>{if(event.target.matches('[data-folder-picker-storage]')){const source=settings().querySelector('[name=source]');if(source&&data.sources.some(row=>row.id==='storage:'+event.target.value))source.value='storage:'+event.target.value;}if(event.target.matches('[data-photo-upload]')){const files=[...event.target.files];uploadFiles(files).catch(error=>options.toast?.(error.message,true));event.target.value='';}if(event.target.matches('[data-photo-album-target]')&&event.target.value){mutate({action:'album_add',album:event.target.value,photo:openId}).then(()=>options.toast?.('Foto zum Album hinzugefügt.')).catch(error=>options.toast?.(error.message,true));event.target.value='';}});
  listen(node,'keydown',event=>{if(!lightbox().open||event.target.matches('input,select,textarea'))return;if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();command(event.key==='ArrowRight'?'photo-next':'photo-previous').catch(error=>options.toast?.(error.message,true));}});
  startPoll();current={reload,destroy(){alive=false;request++;if(poll)clearTimeout(poll);controller.abort();window.TitanFolderPicker?.disposeWithin(node);for(const modal of node.querySelectorAll('dialog'))if(modal.open)modal.close();}};return current;
 }
 return {render,mount,dispose,query,grouped,state,preview,original};
});
