/* Password-confirmed TOTP enrollment and web-session management. */
(function(global){
 'use strict';
 const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 const date=value=>value?new Date(value*1000).toLocaleString('de-DE'):'Unbekannt';
 let mounted=null;
 const protectionModes=[['ip','IP-Sperre','Schützt den NAS-Zugang vor wiederholten Anmeldeversuchen derselben IP-Adresse.'],['account','Kontoschutz','Schützt ein Konto gegen Fehlversuche von derselben IP-Adresse. Andere Zugänge bleiben möglich.']];
 function remaining(seconds){const value=Math.max(0,Math.ceil(Number(seconds)||0));return value?value>=60?`${Math.ceil(value/60)} Min.`:`${value} Sek.`:'Abgelaufen';}
 function protectionBlocks(data){return `<div class="login-block-list" data-login-block-list>${data?.blocked_count>(data?.blocks||[]).length?`<p class="hint">${(data.blocks||[]).length} von ${escape(data.blocked_count)} aktiven Sperren. Nach dem Entsperren erneut aktualisieren, um weitere Zugriffe anzuzeigen.</p>`:''}${(data?.blocks||[]).map(item=>`<article class="login-block"><div><strong>${escape(item.address)}${item.username?' · '+escape(item.username):''}</strong><p>${escape(item.type==='account'?'Kontoschutz':'IP-Sperre')} · ${escape(item.reason)}</p><small>Bis ${date(item.expires)} · <span data-login-block-until="${escape(item.expires)}">${remaining(item.remaining_seconds)}</span></small></div><button type="button" class="button" data-login-unblock="${escape(item.id)}" aria-label="Sperre für ${escape(item.address)}${item.username?' und '+escape(item.username):''} aufheben">Entsperren</button></article>`).join('')||'<p class="hint">Keine aktiven Sperren.</p>'}</div>`;}
 function protectionPanel(data,error=''){
  if(error)return `<section class="login-protection" data-login-protection><h3>Anmeldeschutz</h3><p class="notice warning" role="alert">${escape(error)}</p><button type="button" class="button" data-login-retry>Status erneut laden</button></section>`;
  if(!data?.settings)return '';
  const settings=data.settings;
  return `<section class="login-protection" data-login-protection><h3>Anmeldeschutz</h3><p>Lege fest, wann fehlgeschlagene Passwort- oder Zwei-Faktor-Anmeldungen vorübergehend gesperrt werden.</p><p class="hint">${escape(data.scope_note||'Dieser Schutz gilt für Anmeldungen an der Titan-Weboberfläche.')}</p><form data-login-protection-form><div class="login-protection-modes">${protectionModes.map(([kind,title,description])=>{const config=settings[kind]||{};return `<fieldset data-login-mode="${kind}"><legend>${title}</legend><label class="login-protection-toggle"><input type="checkbox" name="${kind}_enabled" ${config.enabled?'checked':''}><span>${title} aktivieren</span></label><p class="hint">${description}</p><div class="login-protection-fields">${[['attempts','Fehlgeschlagene Versuche',100],['window_minutes','Innerhalb von (Minuten)',1440],['block_minutes','Sperrdauer (Minuten)',10080]].map(([key,label,max])=>`<label for="login-${kind}-${key}">${label}<input id="login-${kind}-${key}" name="${kind}_${key}" type="number" inputmode="numeric" min="1" max="${max}" required value="${escape(config[key])}" ${config.enabled?'':'disabled'}></label>`).join('')}</div></fieldset>`;}).join('')}</div><p class="hint">Beim Ausschalten werden Sperren und Fehlversuche dieses Schutzes gelöscht. Bestehende Sperren bleiben bei geänderten Grenzwerten bis zum Ablauf erhalten.</p><div class="form-actions"><button class="button primary" type="submit">Anmeldeschutz speichern</button><span class="hint" data-login-protection-status role="status" aria-live="polite"></span></div><p class="notice warning" data-login-protection-error role="alert" hidden></p></form><div class="login-block-heading"><h4>Gesperrte Zugriffe</h4><button type="button" class="button small" data-login-block-refresh>Sperren aktualisieren</button></div>${protectionBlocks(data)}<p class="hint">Sperren bleiben nach einem Neustart erhalten und enden automatisch nach der eingestellten Dauer.</p></section>`;
 }
 function dispose(){mounted?.dispose();mounted=null;}
 function mountProtection(center,data,options){
  const panel=center.querySelector('[data-login-protection]');if(!panel)return null;
  const listeners=[];let alive=true,timer=null,overview=data,revision=data?.revision;
  const listen=(node,type,fn)=>{if(!node)return;node.addEventListener(type,fn);listeners.push([node,type,fn]);};
  const error=panel.querySelector('[data-login-protection-error]'),status=panel.querySelector('[data-login-protection-status]');
  const fail=failure=>{if(!alive)return;if(error){error.hidden=false;error.textContent=failure.message;}options.toast?.(failure.message,true);};
  const countdown=()=>{if(!alive)return;for(const node of panel.querySelectorAll('[data-login-block-until]'))node.textContent=remaining(Number(node.dataset.loginBlockUntil)-Date.now()/1000);};
  const paintBlocks=value=>{if(!alive)return;overview=value;const list=panel.querySelector('[data-login-block-list]');if(list){const holder=center.ownerDocument.createElement('div');holder.innerHTML=protectionBlocks(value);list.replaceWith(holder.firstElementChild);}countdown();};
  listen(panel,'click',async event=>{const retry=event.target.closest?.('[data-login-retry]'),refresh=event.target.closest?.('[data-login-block-refresh]'),unblock=event.target.closest?.('[data-login-unblock]');if(!retry&&!refresh&&!unblock)return;event.preventDefault();const button=retry||refresh||unblock;if(button.disabled)return;if(unblock&&!(await options.confirm?.('Diese Anmeldesperre aufheben?')))return;if(!alive)return;button.disabled=true;try{const value=await options.api(unblock?'/api/security/login-protection/unblock':'/api/security/login-protection',unblock?{id:unblock.dataset.loginUnblock}:undefined);if(!alive)return;if(retry){await options.refresh?.(false);return;}paintBlocks(value);if(status)status.textContent=unblock?'Sperre aufgehoben.':'Sperren aktualisiert.';if(error)error.hidden=true;}catch(failure){fail(failure);}finally{if(alive){button.disabled=false;if(!retry)(unblock?panel.querySelector('[data-login-block-refresh]'):button)?.focus?.({preventScroll:true});}}});
  const form=panel.querySelector('[data-login-protection-form]');
  listen(form,'change',event=>{for(const[kind]of protectionModes){if(event.target.name!==kind+'_enabled')continue;const config=form.querySelector(`[data-login-mode="${kind}"]`);for(const input of config.querySelectorAll('input[type=number]'))input.disabled=!event.target.checked;}});
  listen(form,'submit',async event=>{event.preventDefault();const submit=form.querySelector('[type=submit]');if(submit.disabled)return;submit.disabled=true;if(error)error.hidden=true;if(status)status.textContent='Wird gespeichert …';const settings={schema:1};for(const[kind]of protectionModes){const previous=overview.settings[kind],enabled=form.elements[kind+'_enabled'].checked;settings[kind]={enabled};for(const key of ['attempts','window_minutes','block_minutes'])settings[kind][key]=Number(form.elements[kind+'_'+key].value||previous[key]);}try{const value=await options.api('/api/security/login-protection',{settings,expected_revision:revision});if(!alive)return;revision=value.revision;paintBlocks(value);if(status)status.textContent='Anmeldeschutz gespeichert.';options.saved?.(form);options.toast?.('Anmeldeschutz gespeichert.');}catch(failure){if(status)status.textContent='';fail(failure);}finally{if(alive){submit.disabled=false;submit.focus?.({preventScroll:true});}}});
  if(data?.settings){countdown();timer=setInterval(countdown,1000);}
  return {dispose(){if(!alive)return;alive=false;if(timer!==null)clearInterval(timer);for(const[node,type,fn]of listeners)node.removeEventListener(type,fn);listeners.length=0;}};
 }
 function render(data,options={}){
  return `<section class="security-center panel" data-security-center><header><h2>Sicherheitszentrum</h2>${options.admin?`<label><input type="checkbox" data-security-all ${data.all_users?'checked':''}> Alle Benutzer anzeigen</label>`:''}</header><div class="security-checks">${data.checks.map(check=>`<article class="security-check ${check.ok?'is-good':'is-open'}"><strong>${check.ok?'✓':'!'} ${escape(check.label)}</strong>${check.ok?'':`<p>${escape(check.action)}</p>`}</article>`).join('')}</div>${options.admin?protectionPanel(options.protection,options.protectionError):''}<section><h3>Zwei-Faktor-Anmeldung</h3><p>${data.two_factor?`Aktiv · ${data.recovery_remaining} Wiederherstellungscodes übrig.`:'Schütze deine Anmeldung zusätzlich mit einer Authenticator-App.'}</p><div class="identity-actions">${data.two_factor?'<button class="button" data-security-action="recovery">Neue Wiederherstellungscodes</button><button class="button danger" data-security-action="disable">Zwei-Faktor-Anmeldung deaktivieren</button>':'<button class="button primary" data-security-action="begin">Authenticator einrichten</button>'}</div><div data-security-enrollment></div></section><section><h3>Aktive Sitzungen</h3><div class="security-session-list">${data.sessions.map(session=>`<article class="security-session"><div><strong>${escape(session.username)}${session.current?' · Diese Sitzung':''}</strong><p>${escape(session.address||'Adresse unbekannt')} · ${escape(session.user_agent||'Browser unbekannt')}</p><small>Angemeldet: ${date(session.created)} · Zuletzt aktiv: ${date(session.last_seen)}</small></div><button class="button danger" data-security-revoke="${escape(session.id)}">Abmelden</button></article>`).join('')||'<p>Keine aktiven Sitzungen.</p>'}</div></section><section><h3>Anmeldeverlauf</h3><div class="security-events">${data.login_events.map(event=>`<article><strong>${event.success?'Angemeldet':'Abgelehnt'} · ${escape(event.username)}</strong><span>${date(event.time)} · ${escape(event.address)}</span></article>`).join('')||'<p>Noch keine Anmeldeereignisse.</p>'}</div></section></section>`;
 }
 function codesHtml(codes){return `<h3>Wiederherstellungscodes sichern</h3><p>Jeder Code kann einmal anstelle des Authenticator-Codes verwendet werden. Bewahre sie außerhalb des NAS auf.</p><pre class="security-recovery">${codes.map(escape).join('\n')}</pre><button class="button" type="button" data-security-download>Codes herunterladen</button>`;}
 function mount(root,data,options){
  dispose();
  const center=root.querySelector('[data-security-center]');if(!center)return;
  mounted=mountProtection(center,options.protection,options);
  const area=center.querySelector('[data-security-enrollment]');let enrollmentPassword='';
  const showCodes=codes=>{area.innerHTML=codesHtml(codes);area.querySelector('[data-security-download]').onclick=()=>{const url=URL.createObjectURL(new Blob(['Titan Wiederherstellungscodes\n\n'+codes.join('\n')+'\n'],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='titan-wiederherstellungscodes.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};};
  center.querySelector('[data-security-all]')?.addEventListener('change',event=>options.refresh?.(event.target.checked));
  for(const button of center.querySelectorAll('[data-security-revoke]'))button.onclick=async()=>{if(!(await options.confirm?.('Diese Sitzung abmelden?')))return;try{await options.api('/api/security/sessions/revoke',{id:button.dataset.securityRevoke});options.toast?.('Sitzung abgemeldet.');await options.refresh?.(data.all_users);}catch(failure){options.toast?.(failure.message,true);}};
  const formFor=action=>{area.innerHTML=`<form data-security-form><label>Aktuelles Passwort<input type="password" name="password" required autocomplete="current-password"></label>${action==='begin'?'':'<label>Authenticator- oder Wiederherstellungscode<input name="code" required autocomplete="one-time-code" maxlength="64"></label>'}<div class="form-actions"><button class="button primary" type="submit">${action==='begin'?'Einrichtung starten':action==='disable'?'Deaktivieren':'Codes erzeugen'}</button><button class="button" type="button" data-security-cancel>Abbrechen</button></div><p role="alert" data-security-error hidden></p></form>`;
   area.querySelector('[data-security-cancel]').onclick=()=>{enrollmentPassword='';area.innerHTML='';};area.querySelector('input').focus();
   area.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,fields=Object.fromEntries(new FormData(form)),error=form.querySelector('[data-security-error]'),submit=form.querySelector('[type=submit]');error.hidden=true;submit.disabled=true;
    try{if(action==='begin'){const setup=await options.api('/api/security/totp/begin',{password:fields.password});enrollmentPassword=fields.password;area.innerHTML=`<form data-security-confirm><p>Füge in deiner Authenticator-App ein Konto hinzu: Anbieter <strong>Titan</strong>, Benutzer <strong>${escape(options.username||'')}</strong>, zeitbasierter Code, Schlüssel:</p><code class="security-secret">${escape(setup.secret)}</code><p>Die Einrichtung ist zehn Minuten gültig. Gib jetzt den sechsstelligen Code der App ein.</p><label>Sicherheitscode<input name="code" required pattern="[0-9]{6}" inputmode="numeric" autocomplete="one-time-code" maxlength="6"></label><button class="button primary" type="submit">Aktivieren und Codes sichern</button><p role="alert" data-security-error hidden></p></form>`;
      area.querySelector('form').onsubmit=async confirm=>{confirm.preventDefault();const confirmForm=confirm.currentTarget,confirmError=confirmForm.querySelector('[data-security-error]'),confirmButton=confirmForm.querySelector('[type=submit]');confirmButton.disabled=true;try{const result=await options.api('/api/security/totp/confirm',{password:enrollmentPassword,code:new FormData(confirmForm).get('code')});enrollmentPassword='';showCodes(result.recovery_codes);options.toast?.('Zwei-Faktor-Anmeldung aktiviert. Wiederherstellungscodes jetzt sicher speichern.');}catch(failure){confirmError.textContent=failure.message;confirmError.hidden=false;confirmButton.disabled=false;}};
     }else{const result=await options.api(action==='disable'?'/api/security/totp/disable':'/api/security/recovery',fields);enrollmentPassword='';if(result.recovery_codes)showCodes(result.recovery_codes);else{area.innerHTML='<p>Zwei-Faktor-Anmeldung deaktiviert. Andere Sitzungen wurden abgemeldet.</p>';options.toast?.('Andere Sitzungen wurden abgemeldet.');}}
    }catch(failure){error.textContent=failure.message;error.hidden=false;submit.disabled=false;}
   };
  };
  for(const button of center.querySelectorAll('[data-security-action]'))button.onclick=()=>formFor(button.dataset.securityAction);
 }
 global.TitanSecurity={render,mount,dispose,protectionPanel,protectionBlocks,remaining,mountProtection};
})(window);
