'use strict';
// The server supplies each unit's allowed operations; command text never becomes HTML.
(() => {
 const labels={start:'Starten',stop:'Stoppen',restart:'Neustarten',reload:'Konfiguration neu laden','reset-failed':'Fehler zurücksetzen',enable:'Autostart aktivieren',disable:'Autostart deaktivieren'};
 let cleanup=null, search='',stateFilter='';
 function stateLabel(item){return {active:'Aktiv',inactive:'Gestoppt',failed:'Fehler',activating:'Startet',deactivating:'Stoppt',reloading:'Lädt neu'}[item.active]||item.active||'Unbekannt';}
 function controls(item,ctx,primary=false){const primaryCommand=['active','activating','reloading'].includes(item.active)?'stop':'start';return (item.allowed_actions||[]).filter(command=>(!primary||command===primaryCommand)&&labels[command]&&!(command==='start'&&item.active==='active')&&!(command==='stop'&&item.active==='inactive')&&!(command==='enable'&&item.enabled)&&!(command==='disable'&&!item.enabled)).map(command=>`<button type="button" class="button small" data-service-action="command" data-service="${ctx.esc(item.name)}" data-command="${command}">${labels[command]}</button>`).join('');}
 function render(data,ctx){
  const {esc,pill}=ctx;
  return `<section class="panel"><div class="panel-heading"><h2>Systemdienste <span class="service-count">${Number(data.total||0)}</span></h2><button type="button" class="button primary small" data-service-action="create">Neuer Dienst</button></div><div class="service-filter"><label class="field" for="service-search">Dienste suchen<input id="service-search" type="search" placeholder="Name, Beschreibung oder Status" value="${esc(search)}" autocomplete="off"></label><label class="field" for="service-state-filter">Zustand<select id="service-state-filter"><option value="">Alle Zustände</option><option value="active">Aktiv</option><option value="inactive">Gestoppt</option><option value="failed">Fehler</option></select></label><button type="button" class="button small" data-service-action="refresh">Aktualisieren</button></div><p class="hint">Aktiv zeigt den aktuellen Zustand. Autostart bestimmt, ob systemd einen Dienst beim Start des Servers aufruft. Manche Dienste starten bei Bedarf.</p>${data.counts?`<div class="service-summary">${pill(Number(data.counts.active)+' aktiv')}${pill(Number(data.counts.failed)+' mit Fehler',data.counts.failed?'red':'gray')}${pill(Number(data.counts.custom)+' eigene Dienste','gray')}</div>`:''}${data.truncated?'<p class="notice warning">Die Liste wurde begrenzt. Es werden die ersten 2.000 Dienste angezeigt.</p>':''}<div class="service-list">${(data.items||[]).map(item=>`<article class="service-card" data-service-row data-state="${esc(item.active)}" data-search="${esc([item.name,item.description,stateLabel(item)].join(' ').toLocaleLowerCase('de-DE'))}"><div class="service-title"><div><h3><button type="button" class="service-name" data-service-action="details" data-service="${esc(item.name)}">${esc(item.name)}</button></h3><p>${esc(item.description||'Systemdienst')}</p></div>${pill(stateLabel(item),item.active==='failed'?'red':item.active==='active'?'':'gray')}</div><div class="service-meta">${item.custom?pill('Eigener Dienst','purple'):''}<span>Autostart: ${esc(item.enabled?'An':item.unit_file_state==='static'?'Bei Bedarf':item.unit_file_state==='masked'?'Gesperrt':'Aus')}</span>${item.protected?'<span>Titan-Zugang geschützt</span>':''}</div><div class="service-buttons"><button type="button" class="button small" data-service-action="details" data-service="${esc(item.name)}">Details</button>${controls(item,ctx,true)}</div></article>`).join('')}</div><p id="service-no-results" class="empty" hidden>Keine passenden Dienste gefunden.</p></section>`;
 }
 function dispose(){cleanup?.();cleanup=null;}
 function mount(main,ctx,data){
  dispose(); let disposed=false;
  const dialogBody=document.querySelector('#dialog-body');
  const filter=()=>{let count=0;const words=search.toLocaleLowerCase('de-DE').trim().split(/\s+/).filter(Boolean);for(const row of main.querySelectorAll('[data-service-row]')){row.hidden=!words.every(word=>row.dataset.search.includes(word))||Boolean(stateFilter&&row.dataset.state!==stateFilter);if(!row.hidden)count++;}const empty=main.querySelector('#service-no-results');if(empty)empty.hidden=Boolean(count);const counter=main.querySelector('.service-count');if(counter)counter.textContent=count+' / '+Number(data.total||0);};
  const searchInput=main.querySelector('#service-search');
  const onSearch=event=>{search=event.target.value;filter();};searchInput?.addEventListener('input',onSearch);filter();
  const stateInput=main.querySelector('#service-state-filter'),onState=event=>{stateFilter=event.target.value;filter();};if(stateInput){stateInput.value=stateFilter;stateInput.addEventListener('change',onState);filter();}
  async function details(name){
   const info=await ctx.api('/api/service-details?service='+encodeURIComponent(name));if(disposed)return;
   const item=info.service, esc=ctx.esc;
   const fields=[['Zustand',stateLabel(item)],['Autostart',item.unit_file_state],['Linux-Benutzer',item.properties?.User||'root'],['Prozess-ID',item.properties?.MainPID||'—'],['Dienstdatei',item.properties?.FragmentPath||'—'],['Letztes Ergebnis',item.properties?.Result||'—']];
   if(item.metrics){const metrics=item.metrics,format=value=>value===null||value===undefined?'Nicht ermittelt':ctx.bytes?ctx.bytes(value):Number(value).toLocaleString('de-DE')+' B';fields.push(['Arbeitsspeicher',format(metrics.memory_bytes)],['CPU-Zeit',metrics.cpu_seconds===null||metrics.cpu_seconds===undefined?'Nicht ermittelt':Number(metrics.cpu_seconds).toLocaleString('de-DE',{maximumFractionDigits:1})+' s'],['Neustarts',metrics.restarts??'Nicht ermittelt'],['Prozesse / Threads',metrics.tasks??'Nicht ermittelt']);}
   const relationships=item.relationships?Object.entries(item.relationships).filter(([,values])=>Array.isArray(values)&&values.length).map(([name,values])=>`<div><dt>${esc(({triggered_by:'Gestartet durch',triggers:'Aktiviert',requires:'Benötigt',wants:'Verwendet',after:'Startet nach'})[name]||name)}</dt><dd>${values.map(esc).join(', ')}</dd></div>`).join(''):'';
   ctx.dialog(item.name,`<p class="subtitle">${esc(item.description||'Systemdienst')}</p><dl class="service-details">${fields.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>${relationships?`<details class="service-relationships"><summary>Abhängigkeiten und Auslöser</summary><dl class="service-details">${relationships}</dl></details>`:''}${item.protected_reason?`<p class="notice">${esc(item.protected_reason)}</p>`:''}<div class="service-buttons">${controls(item,ctx)}</div><div class="panel-heading"><h3>Letzte Protokolleinträge</h3><button type="button" class="button small" data-service-action="details" data-service="${esc(name)}">Protokoll aktualisieren</button></div>${info.logs_error?`<p class="notice warning">${esc(info.logs_error)}</p>`:''}<pre class="code service-log">${esc(info.logs||'Noch keine Protokolleinträge vorhanden.')}</pre>${info.logs_truncated?'<p class="hint">Ausgabe auf 64 KiB begrenzt.</p>':''}`);
  }
  async function create(){
   const locations=await ctx.api('/api/storage-locations');if(disposed)return;
   const programs=(locations.programs||[]).map(item=>[item.path,item.label+' · '+item.path]);
   ctx.dialog('Neuen Dienst anlegen',`<p class="subtitle">Ein dauerhaft laufendes Programm durch systemd verwalten.</p><form>${ctx.field('Name','name','text','','required pattern="[a-z][a-z0-9_-]{0,30}" maxlength="31"','Die Dienstdatei erhält den Namen titan-custom-NAME.service.')}${ctx.field('Beschreibung','description','text','','required maxlength="512"')}${ctx.selectField('Installiertes Programm','program',[...programs,['custom','Eigenes Programm · erweitert']],programs[0]?.[0]||'custom')}${ctx.field('Eigenes Programm','custom_program','text','','maxlength="4096"','Absoluter Pfad zu einem bereits installierten ausführbaren Programm.').replace('<label', '<label data-service-custom-program') .replace('<div class="field"','<div data-service-custom-program class="field"')}${ctx.field('Argumente','args','text','','maxlength="8192" placeholder="/srv/mein-dienst/server.py"','Argumente mit Leerzeichen in Anführungszeichen setzen. Umleitungen und Pipes sind hier keine Shellbefehle.')}${ctx.selectField('Linux-Benutzer','user',(data.users||[]).map(item=>[item.name,item.label||item.name]),'titan-files')}${ctx.locationField?ctx.locationField('Arbeitsverzeichnis','working_directory','',{hint:'Optional: Wähle einen vorhandenen Ordner. Der Dienstbenutzer benötigt dort Zugriff.'}):ctx.field('Arbeitsverzeichnis','working_directory','text','','maxlength="4096"')}<div class="checkbox-list"><label><input name="autostart" type="checkbox">Beim Serverstart starten</label><label><input name="start" type="checkbox">Jetzt starten</label></div><p class="hint">Das Programm läuft mit den Rechten des gewählten Linux-Benutzers. Wähle root nur, wenn der Dienst Administratorrechte braucht.</p>${ctx.formEnd('Dienst anlegen')}`,async form=>{
    const args=Object.fromEntries(form);if(args.program==='custom')args.program=args.custom_program||'';delete args.custom_program;args.autostart=form.has('autostart');args.start=form.has('start');await ctx.action('service_create',args);
   });
   const body=document.querySelector('#dialog-body'),program=body?.querySelector?.('[name=program]'),custom=body?.querySelector?.('[data-service-custom-program]');
   const sync=()=>{if(custom){custom.hidden=program?.value!=='custom';const input=custom.querySelector('input');input.disabled=custom.hidden;input.required=!custom.hidden;}};program?.addEventListener('change',sync);sync();
  }
  const onClick=async event=>{const target=event.target.closest?.('[data-service-action]');if(!target||disposed||target.dataset.pending==='true')return;const kind=target.dataset.serviceAction,opensDialog=['details','create'].includes(kind);target.dataset.pending='true';if(!opensDialog)target.disabled=true;try{if(kind==='details')await details(target.dataset.service);else if(kind==='create')await create();else if(kind==='refresh')await ctx.navigate();else if(kind==='command'){const command=target.dataset.command;if(!labels[command])return;await ctx.action('service_action',{service:target.dataset.service,command});}}catch(error){ctx.toast(error.message,true);}finally{target.disabled=false;delete target.dataset.pending;}};
  main.addEventListener('click',onClick);dialogBody?.addEventListener('click',onClick);
  cleanup=()=>{disposed=true;main.removeEventListener('click',onClick);dialogBody?.removeEventListener('click',onClick);searchInput?.removeEventListener('input',onSearch);stateInput?.removeEventListener('change',onState);};
 }
 window.TitanServices={render,mount,dispose,stateLabel};
})();
