'use strict';
(function(root,factory){const ui=factory();if(root)root.TitanTemplateFields=ui;if(typeof module==='object'&&module.exports)module.exports=ui;})(typeof window==='undefined'?null:window,function(){
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const listeners=new WeakMap();
 const key=option=>'option-'+option.key;
 function enabled(option,data){return option.optional!==true||data.get('enable-'+option.key)==='on';}
 function fields(app,hostname=''){
  return (app.install_schema||[]).map(option=>{
   const name=key(option),id='template-'+option.key,isOptional=option.optional===true,isBoolean=option.type==='boolean';
   const checked=isBoolean&&!isOptional?Boolean(option.display_default??option.default??option.enabled_by_default):option.enabled_by_default===true,attributes=`${option.required?'required':''} ${isOptional&&!checked?'disabled':''} ${option.controlled_by_web_port?'readonly aria-readonly="true"':''}`;
   let value=option.type==='password'?'':option.key==='nas_host'?hostname.replace(/^\[|\]$/g,''):option.display_default??option.default??option.suggested_default??'';
   const autoUrl=option.label==='APP_URL'&&hostname&&value==='';if(autoUrl){const host=hostname.includes(':')?'['+hostname.replace(/^\[|\]$/g,'')+']':hostname;value=(app.scheme||'http')+'://'+host+':'+Number(app.default_port||app.port);}
   let control;
   if(isBoolean)control='';
   else if(Array.isArray(option.choices))control=`<label class="field" for="${esc(id)}"><span>${esc(option.label)}</span><select id="${esc(id)}" name="${esc(name)}" ${attributes}>${option.choices.map(([v,label])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(label)}</option>`).join('')}</select></label>`;
   else control=`<label class="field" for="${esc(id)}"><span>${esc(option.label)}</span><input id="${esc(id)}" name="${esc(name)}" type="${['text','number','password','url','email'].includes(option.type)?option.type:'text'}" value="${esc(value)}" ${autoUrl?'data-template-auto-url="true"':''} ${attributes} ${option.min!==undefined?'min="'+Number(option.min)+'"':''} ${option.max!==undefined?'max="'+Number(option.max)+'"':''} ${option.min_length?'minlength="'+Number(option.min_length)+'"':''} ${option.max_length?'maxlength="'+Number(option.max_length)+'"':''} ${option.type==='password'?'autocomplete="new-password"':''} ${option.pattern?'pattern="'+esc(option.pattern)+'"':''}></label>`;
   if(isBoolean)control=`<label class="template-enable"><input type="checkbox" name="${isOptional?'enable-'+esc(option.key):esc(name)}" ${checked?'checked':''} value="${isOptional?'on':'true'}"><span>${esc(option.label)}</span></label>`;
   else if(isOptional)control=`<label class="template-enable"><input type="checkbox" name="enable-${esc(option.key)}" data-template-enable="${esc(option.key)}" ${checked?'checked':''}><span>${esc(option.label)} verwenden</span></label>`+control;
   return `<div class="template-option ${isOptional?'is-optional':''}" data-template-option="${esc(option.key)}">${control}${option.help?`<p class="hint">${esc(option.help)}</p>`:''}</div>`;
  }).join('');
 }
 function argumentsFor(app,data){const options={};for(const option of app.install_schema||[]){if(!enabled(option,data))continue;const value=option.controlled_by_web_port&&data.get('port')!==null?data.get('port'):data.get(key(option));if(option.type==='boolean'){if(option.optional)options[option.key]=true;else options[option.key]=value==='true';}else if(value!==null&&value!=='')options[option.key]=option.type==='number'?Number(value):String(value);}return options;}
 function bind(container,{app,hostname=''}={}){listeners.get(container)?.();const reflect=()=>{if(!app)return;const form=container.querySelector('form');if(!form)return;const data=new FormData(form);for(const option of app.install_schema||[]){if(!option.controlled_by_web_port)continue;const control=container.querySelector(`[name="${key(option)}"]`);if(control)control.value=data.get('port')||'';}const mapping=container.querySelector('[data-template-mapping]');if(mapping)mapping.innerHTML=mappings(app,data);const url=hostname&&container.querySelector('[data-template-auto-url]');if(url){const host=hostname.includes(':')?'['+hostname.replace(/^\[|\]$/g,'')+']':hostname;url.value=(app.scheme||'http')+'://'+host+':'+data.get('port');}};const handler=event=>{const control=event.target;if(control.matches?.('[data-template-enable]')){const holder=control.closest('[data-template-option]');for(const input of holder?.querySelectorAll('[name^="option-"]')||[])input.disabled=!control.checked;}if(event.type==='input'&&control.matches?.('[data-template-auto-url]'))control.removeAttribute('data-template-auto-url');reflect();};container?.addEventListener('change',handler);container?.addEventListener('input',handler);reflect();const dispose=()=>{container?.removeEventListener('change',handler);container?.removeEventListener('input',handler);};if(container)listeners.set(container,dispose);return dispose;}
 function mappings(app,data){const ports=app.port_bindings||[],storage=app.storage_bindings||[],options=data?argumentsFor(app,data):null,host=data?.get('network_mode')==='host';return `${ports.length?`<h4>Ports</h4><ul>${ports.map(port=>{const enabled=!options||!port.option||Object.hasOwn(options,port.option),primary=!port.option&&port.protocol!=='udp'&&Number(port.target)===Number(app.port),published=data&&primary?data.get('port'):options&&port.option?options[port.option]:port.published,target=data&&primary&&app.dynamic_web_port?data.get('port'):port.target;return `<li><strong>${host?'NAS-Port '+esc(target):esc(published??'Nicht aktiviert')+' → '+esc(target)+'/'+esc(port.protocol||'tcp')}</strong>${port.service?' · '+esc(port.service):''}${!enabled?' · nicht aktiviert':port.optional?' · optional':''}</li>`;}).join('')}</ul>`:''}${storage.length?`<h4>Datenordner</h4><ul>${storage.map(mount=>`<li><strong>${esc(mount.target)}</strong> · ${mount.readonly?'Nur Lesen':'Lesen und Schreiben'}${options&&mount.option&&!Object.hasOwn(options,mount.option)?' · nicht aktiviert':mount.optional?' · optional':''}</li>`).join('')}</ul><p class="hint">Titan richtet die aktiven Ordner im gewählten Speicher ein.</p>`:''}`;}
 function summary(app){if(!app.port_bindings?.length&&!app.storage_bindings?.length)return '';return `<details class="template-bindings"><summary>Ports und Datenordner der Vorlage</summary><div data-template-mapping>${mappings(app)}</div></details>`;}
 return {fields,argumentsFor,bind,summary,mappings};
});
