'use strict';
(function(root,factory){const ui=factory();if(root)root.TitanTemplateBrowser=ui;if(typeof module==='object'&&module.exports)module.exports=ui;})(typeof window==='undefined'?null:window,function(){
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function filter(apps,{query='',source='',sort='az'}={}){const words=query.toLocaleLowerCase('de-DE').trim().split(/\s+/).filter(Boolean);return apps.filter(app=>(!source||app.store_name===source)&&words.every(word=>[app.name,app.description,app.category,app.store_name].join(' ').toLocaleLowerCase('de-DE').includes(word))).sort((a,b)=>(sort==='za'?-1:1)*a.name.localeCompare(b.name,'de'));}
 function mount(container,{api,action,install,toast,artwork,state={}}={}){
  let alive=true,busy=false,apps=[],stores=[],presets=[],query=state.query||'',source=state.source||'',sort=state.sort||'az',error='',loading=true,epoch=0;
  function render(){if(!alive)return;const focused=container.ownerDocument.activeElement,focusKey=container.contains(focused)?['search','source','sort'].find(key=>focused?.matches?.('[data-template-'+key+']')):null,position=focused?.selectionStart;
   const rows=filter(apps,{query,source,sort}),sources=[...new Set(apps.map(app=>app.store_name).filter(Boolean))];
   container.innerHTML=`<section class="template-browser"><div class="template-intro"><h3>Docker-Vorlagen</h3><p>Wähle eine Vorlage. Speicher, Ports und Einstellungen prüfst du vor der Installation.</p></div><div class="template-search"><input type="search" data-template-search aria-label="Vorlagen suchen" placeholder="Name oder Zweck suchen …" value="${esc(query)}"><select data-template-source aria-label="Vorlagenquelle"><option value="">Alle Quellen</option>${sources.map(name=>`<option value="${esc(name)}" ${source===name?'selected':''}>${esc(name)}</option>`).join('')}</select><select data-template-sort aria-label="Vorlagen sortieren"><option value="az" ${sort==='az'?'selected':''}>Name A–Z</option><option value="za" ${sort==='za'?'selected':''}>Name Z–A</option></select></div><p class="template-status ${error?'is-error':''}" role="status">${esc(error|| (loading?'Vorlagen werden geladen …':busy?'Vorlagenquelle wird aktualisiert …':rows.length+' Vorlagen'))}</p><details class="template-sources"><summary>Vorlagenquellen verwalten</summary><div>${presets.map(preset=>{const record=stores.find(store=>store.id===preset.id||store.url===preset.url);return `<article><div><strong>${esc(preset.name)}</strong><small>${record?record.apps+' Vorlagen · '+(record.enabled?'Aktiv':'Ausgeblendet'):'Noch nicht geladen'}</small>${record?.skipped?.length?`<small>${record.skipped.length} nicht unterstützte Vorlagen wurden ausgelassen.</small>`:''}</div><div class="template-source-actions"><button type="button" class="button small" data-template-refresh="${esc(preset.id)}" ${busy?'disabled':''}>${record?'Aktualisieren':'Vorlagen laden'}</button>${record?`<button type="button" class="button small" data-template-toggle="${esc(record.id)}" ${busy?'disabled':''}>${record.enabled?'Ausblenden':'Einblenden'}</button>`:''}</div></article>`;}).join('')||'<p class="hint">Keine zusätzlichen Quellen verfügbar.</p>'}</div></details><div class="template-grid">${rows.map(app=>`<article class="template-card"><div class="template-card-heading">${artwork?.(app.id,app.image)||''}<div><h4>${esc(app.name)}</h4><small>${esc(app.store_name||'Docker-Vorlage')}</small></div></div><p>${esc(app.description)}</p><small class="template-validation">Vorlage geprüft · Einrichtung kann erforderlich sein</small><div class="template-card-footer"><small>${Number(app.containers||1)} ${Number(app.containers||1)===1?'Container':'Dienste'}${app.default_port||app.port?' · Port '+esc(app.default_port||app.port):''}</small><button class="button small primary" type="button" data-template-install="${esc(app.id)}" ${busy||app.deprecated||app.catalog_status==='preparation'?'disabled':''}>${app.catalog_status==='preparation'?'In Vorbereitung':'Einrichten'}</button></div></article>`).join('')}</div>${!rows.length&&!loading?'<div class="engine-empty-state"><strong>Keine passenden Vorlagen</strong><p>Ändere die Suche oder lade eine Vorlagenquelle.</p></div>':''}</section>`;
   if(focusKey){const input=container.querySelector('[data-template-'+focusKey+']');input?.focus();if(focusKey==='search'&&typeof position==='number')input?.setSelectionRange?.(position,position);}
  }
  async function refresh(){const request=++epoch;loading=true;render();try{const values=await Promise.all([api('/api/catalog'),api('/api/app-stores')]);if(!alive||request!==epoch)return;apps=values[0].apps||[];stores=values[1].stores||[];presets=values[1].presets||[];error=values[0].error||'';if(source&&!apps.some(app=>app.store_name===source))source='';}catch(exception){if(alive&&request===epoch)error=exception.message;}finally{if(alive&&request===epoch){loading=false;render();}}}
  async function click(event){const button=event.target.closest?.('[data-template-install],[data-template-refresh],[data-template-toggle]');if(!button||!container.contains(button)||busy)return;
   try{if(button.dataset.templateInstall){const app=apps.find(item=>item.id===button.dataset.templateInstall);if(!app||app.deprecated||app.catalog_status==='preparation')return;button.disabled=true;await install(app.id);return;}
    busy=true;error='';render();if(button.dataset.templateRefresh){const preset=presets.find(item=>item.id===button.dataset.templateRefresh);if(!preset)throw Error('Vorlagenquelle nicht gefunden.');const record=stores.find(store=>store.id===preset.id||store.url===preset.url);await action(record?'app_store_refresh':'app_store_add',record?{store:record.id}:{url:preset.url,trusted:true},{wait:true,onProgress:job=>{if(alive){const status=container.querySelector('.template-status');if(status)status.textContent=job.result?.message||'Vorlagen werden geprüft …';}}});}else{const record=stores.find(item=>item.id===button.dataset.templateToggle);if(!record)throw Error('Vorlagenquelle nicht gefunden.');await action('app_store_toggle',{store:record.id,enabled:!record.enabled},{wait:true});}await refresh();
   }catch(exception){if(alive){error=exception.message;toast?.(exception.message,true);}}finally{busy=false;if(alive)render();}
  }
  function input(event){const control=event.target;if(control.matches?.('[data-template-search]'))query=control.value;else if(control.matches?.('[data-template-source]'))source=control.value;else if(control.matches?.('[data-template-sort]'))sort=control.value;else return;Object.assign(state,{query,source,sort});render();}
  container.addEventListener('click',click);container.addEventListener('input',input);container.addEventListener('change',input);render();void refresh();
  return {refresh,destroy(){alive=false;epoch++;container.removeEventListener('click',click);container.removeEventListener('input',input);container.removeEventListener('change',input);}};
 }
 return {filter,mount};
});
