'use strict';
(() => {
 const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 function deployment(item,title,description){return `<article class="deployment-card"><span class="eyebrow">${esc(title)}</span><strong>${item?.version?'v'+esc(item.version):item?'Versionskennung fehlt':'Keine Version'}</strong><p>${esc(description)}</p>${item?.titan_version?`<span class="deployment-system-version">Titan v${esc(item.titan_version)} · Debian-Systemstand ${esc(item.system_revision??0)}</span>`:''}${item?`<code title="${esc(item.digest)}">${esc(item.digest)}</code><small>${esc(item.image)}</small>`:''}</article>`;}
 function rollbackChoices(data){
  const values=Array.isArray(data.rollback_options)?data.rollback_options:(data.rollback?[data.rollback]:[]);
  return values.filter(item=>item&&typeof item.digest==='string'&&/^sha256:[a-f0-9]{64}$/.test(item.digest));
 }
 function rollbackSecurity(choice={}){
  const raw=choice.titan_version||choice.release_metadata?.titan_version||choice.version||'',match=String(raw).match(/^v?(\d+)\.(\d+)\.(\d+)(?:[-+.]|$)/),parts=match?.slice(1,4).map(Number),appVersion=parts?.join('.')||null;
  return {appVersion,legacyTwoFactor:Boolean(parts&&parts[0]===0&&parts[1]<5),legacyProtections:Boolean(parts&&parts[0]===0&&(parts[1]<5||parts[1]===5&&parts[2]<3))};
 }
 const labels={all:'Verfügbare Updates',titan:'Titan',system:'System & Sicherheit'};
 const stages={alpha:'Alpha',beta:'Beta',stable:'Stable'};
 function offer(kind,update={},settings={},session={},system={}){
  const matching=update.channel===settings.channel&&(!update.selection_kind||update.selection_kind===kind),latest=matching?update.latest:null,error=matching?update.error:null,available=Boolean(matching&&latest&&update.available&&!system.reboot_required&&!system.reboot_scheduled),eligible=Boolean(update.signed&&!session.demo),summary=matching?update.security_summary:null,changes=matching&&Array.isArray(update.package_changes)?update.package_changes:[],installedTitan=system.booted?.titan_version||session.version||update.titan_version||'—',revision=system.booted?.system_revision??update.system_revision;
  const installed=kind==='all'?`Titan v${installedTitan}${Number.isInteger(revision)?' · Systemstand '+revision:''}`:kind==='system'?`Debian 13${Number.isInteger(revision)?' · Stand '+revision:''}`:'v'+installedTitan;
  const offered=!latest?'—':kind==='all'?`${update.latest_titan_version?'Titan v'+update.latest_titan_version:latest}${Number.isInteger(update.latest_system_revision)?' · Systemstand '+update.latest_system_revision:''}`:kind==='system'?Number.isInteger(update.latest_system_revision)?'Systemstand '+update.latest_system_revision:latest:update.latest_titan_version?'v'+update.latest_titan_version:latest;
  const checked=update.checked&&matching?new Date(update.checked*1000).toLocaleString('de-DE'):'Noch keine';
  return `<section id="update-offer-${kind}" class="panel update-stream" data-update-stream="${kind}"><div class="panel-heading"><h2>${labels[kind]}</h2><span class="pill ${error?'red':available?'purple':'gray'}">${error?'Prüfung fehlgeschlagen':available?'Update verfügbar':update.checked&&matching?'Aktuell':'Noch nicht geprüft'}</span></div><p class="hint">${kind==='all'?'Titan, Debian und Sicherheitskorrekturen gemeinsam prüfen. Ein geprüftes Update wird beim bestätigten Neustart aktiv.':kind==='system'?'Debian-Pakete, Kernel und Sicherheitskorrekturen. Deine Titan-Version bleibt erhalten.':'Oberfläche, NAS-Funktionen und Fehlerbehebungen.'}</p><dl class="update-stream-versions"><div><dt>Installiert</dt><dd>${esc(installed)}</dd>${kind==='titan'?`<small>${esc(stages[session.stage||update.titan_stage]||'Unbekannt')}</small>`:`<small>Titan v${esc(installedTitan)}</small>`}</div><div><dt>Verfügbarer Stand</dt><dd>${esc(offered)}</dd>${latest?`<small>${esc(latest)}</small>`:''}</div></dl>${latest?`<div class="update-kind-badges"><span class="pill purple">${esc(update.release_kind==='system'?'System & Sicherheit':update.release_kind==='titan'?'Titan':'Systemupdate')}</span></div>`:''}${error?`<div class="notice warning">${esc(error)}</div>`:''}${matching&&update.message?`<p class="hint">${esc(update.message)}</p>`:''}${summary?`<div class="update-package-summary"><strong>${esc(summary.security_packages||0)} ${summary.security_packages===1?'Sicherheitskorrektur':'Sicherheitskorrekturen'}</strong><span>${esc(summary.total_packages||0)} ${summary.total_packages===1?'Paketänderung':'Paketänderungen'} insgesamt</span></div>`:''}${changes.length?`<details class="update-package-changes"><summary>Paketänderungen ansehen${summary?.total_packages>changes.length?' · Vorschau':''}</summary><ul>${changes.map(item=>`<li><span><strong>${esc(item.name)}</strong>${item.security?'<span class="pill purple">Sicherheit</span>':''}</span><small>${esc(item.old_version||'Neu')} → ${esc(item.new_version)}</small></li>`).join('')}</ul></details>`:''}${matching&&update.notes?`<details class="update-release-notes"><summary>Änderungen dieser Freigabe</summary><pre class="code">${esc(update.notes)}</pre></details>`:''}<div class="form-actions update-stream-actions"><button type="button" class="button" data-action="update-check" data-update-kind="${kind}">Jetzt prüfen</button><button type="button" class="button primary" data-action="update-install" data-update-kind="${kind}" data-version="${esc(latest||'')}" data-update-eligible="${eligible}" data-update-available="${available}" ${!eligible||!available?'disabled':''}>${kind==='all'?'Update vorbereiten':kind==='system'?'Systemupdate vorbereiten':'Titan-Update vorbereiten'}</button></div><p class="hint">Letzte Prüfung: ${esc(checked)}</p></section>`;
 }
 function panel(data,error='',offer={}){
  if(error)return `<section class="panel"><h2>Systemversionen</h2><div class="notice warning">${esc(error)}</div><button class="button small" data-action="refresh">Status erneut laden</button></section>`;
  const choices=rollbackChoices(data);
  const next=data.next_boot||data.staged||(data.rollback_queued?data.rollback:data.booted),pending=data.reboot_required;
  return `<section class="panel system-deployments" ${offer.split?'data-update-split="true"':''}><div class="panel-heading"><h2>Systemversionen</h2><span class="pill ${pending?'purple':'gray'}">${data.reboot_scheduled?'Neustart geplant':pending?'Neustart erforderlich':'Aktuell aktiv'}</span></div><div class="update-action-bar">${offer.split?'':`<button class="button" data-action="update-check">1 · Jetzt prüfen</button><button class="button primary" data-action="update-install" data-version="${esc(offer.latest||'')}" data-update-eligible="${Boolean(offer.eligible)}" data-update-available="${Boolean(offer.available)}" ${!offer.eligible||!offer.available||offer.busy||pending||data.reboot_scheduled?'disabled':''}>2 · Update installieren</button>`}<button class="button ${pending?'primary':''}" data-action="system-reboot" ${!pending||data.reboot_scheduled?'disabled':''}>${offer.split?'Neu starten & aktivieren':'3 · Neu starten & aktivieren'}</button></div><div class="deployment-grid">${deployment(data.booted,'Jetzt gestartet','Diese Systemversion läuft gerade.')}${deployment(data.staged||(data.rollback_queued?data.rollback:null),'Beim nächsten Start',data.rollback_queued?'Die vorherige Version ist für den nächsten Start ausgewählt.':data.staged?'Das geprüfte Update ist vorbereitet.':'Aktuell kein Wechsel vorbereitet.')}${deployment(data.rollback,'Vorherige Version','Dateien und App-/VM-Daten werden beim Rollback nicht zurückgesetzt.')}</div>${pending?'<div class="notice warning">Der Versionswechsel erfolgt erst beim Neustart. Speichere offene Arbeiten und fahre laufende virtuelle Maschinen vorher herunter.</div>':''}<label class="field rollback-choice">Systemstand für Rollback<select id="rollback-version" ${!data.rollback_available||!choices.length||data.reboot_scheduled?'disabled':''}>${choices.length?choices.map(item=>`<option value="${esc(item.digest)}">${esc(item.version?'v'+item.version:'Vorheriger Stand')}${item.installed_at?' · '+esc(new Date(item.installed_at*1000).toLocaleString('de-DE')):''}${item.slot?' · Slot '+esc(item.slot):''}</option>`).join(''):'<option>Kein vorheriger Systemstand verfügbar</option>'}</select></label><div class="form-actions wrap"><button class="button" data-action="update-rollback" ${!data.rollback_available||!choices.length||data.reboot_scheduled?'disabled':''}>Ausgewählten Rollback vorbereiten</button><button class="button small" data-action="refresh">↻ Status aktualisieren</button></div>${data.rollback_reason?`<p class="hint">${esc(data.rollback_reason)}</p>`:''}<p class="hint">Rollback stellt auch den damaligen Sicherheitsstand wieder her. Neuere Schutzfunktionen und Sicherheitskorrekturen können dabei entfallen. Freigaben sowie App- und VM-Daten bleiben erhalten. Die aktuelle NAS-Konfiguration wird übernommen; Rollback ersetzt keine Datensicherung.</p><p class="hint" data-system-live-status role="status">Aktueller Systemstatus · wird bei geöffneter Seite regelmäßig aktualisiert.</p></section>`;
 }
 function progress(data){
  if(!data||data.status==='idle')return '';
  const phases={checking:'Update-Angebot und Signatur prüfen',backup:'NAS-Konfiguration sichern',download:'Systemimage herunterladen',verification:'Signatur und Systemimage prüfen',writing:'Inaktiven Systemslot schreiben',confirming:'Systemslot prüfen und Start vorbereiten',ready:'Bereit für den Neustart'};
  const titles={running:'Update läuft',completed:'Update vorbereitet',failed:'Update fehlgeschlagen',interrupted:'Update unterbrochen'};
  const measured=data.status==='running'&&data.phase==='download'&&Number.isFinite(data.received)&&data.total>0;
  const percent=measured?Math.min(100,Math.max(0,100*data.received/data.total)):null;
  return `<h2>${esc(titles[data.status]||'Systemupdate')}</h2><p><strong>${esc(phases[data.phase]||'Status wird ermittelt')}</strong> · ${esc(data.elapsed||0)} s</p>${measured?`<progress max="100" value="${percent}" aria-label="Systemimage herunterladen"></progress><p>${(data.received/1048576).toFixed(1)} / ${(data.total/1048576).toFixed(1)} MiB · ${Math.floor(percent)} %</p>`:''}${data.message?`<p class="notice warning">${esc(data.message)}</p>`:''}`;
 }
 let timer=null,disposed=true,pending=false,revision=0;
 function dispose(){disposed=true;revision++;if(timer!==null)clearInterval(timer);timer=null;}
 function mount(root,ctx){
  dispose();if(!root.querySelector('.system-deployments'))return;disposed=false;const mine=revision;const split=root.querySelector('.system-deployments')?.dataset?.updateSplit==='true';const offerButton=root.querySelector('[data-action=update-install]');const offer={latest:offerButton?.dataset?.version,eligible:offerButton?.dataset?.updateEligible==='true',available:offerButton?.dataset?.updateAvailable==='true',split};
  const refresh=async()=>{
   if(disposed||pending||document.hidden||document.querySelector('dialog[open]'))return;
   pending=true;
   try{const activity=await ctx.api('/api/updates/progress');if(disposed||mine!==revision)return;const activityNode=root.querySelector('#update-progress');if(activityNode){activityNode.innerHTML=progress(activity);activityNode.hidden=activity.status==='idle';}const data=await ctx.api('/api/updates/system');if(disposed||mine!==revision)return;const node=root.querySelector('.system-deployments');if(!node)return;const buttons=split?[...root.querySelectorAll('[data-action=update-install]')]:[root.querySelector('[data-action=update-install]')].filter(Boolean);for(const install of buttons){install.hidden=false;install.disabled=Boolean(install.dataset?.updateEligible!=='true'||install.dataset?.updateAvailable!=='true'||data.reboot_required||data.reboot_scheduled||activity.status==='running');}
    // Preserve the keyboard focus when the same controls remain available.
    const selected=node.querySelector?.('#rollback-version')?.value;
    const active=document.activeElement,selectFocused=active?.id==='rollback-version',action=node.contains(active)?active.dataset?.action:null;
    const holder=document.createElement('div');holder.innerHTML=panel(data,'',{...offer,busy:activity.status==='running'});node.replaceWith(holder.firstElementChild);
    const select=root.querySelector('#rollback-version');if(select&&Array.from(select.options).some(option=>option.value===selected))select.value=selected;if(selectFocused&&select&&!select.disabled)select.focus({preventScroll:true});
    if(action){const replacement=root.querySelector(`[data-action="${action}"]`);if(replacement&&!replacement.disabled)replacement.focus({preventScroll:true});}
   }catch(error){if(!disposed&&mine===revision){const status=root.querySelector('[data-system-live-status]');if(status)status.textContent='Status konnte nicht aktualisiert werden: '+error.message;}}
   finally{pending=false;}
  };
  refresh();timer=setInterval(refresh,3000);
 }
 window.TitanUpdates={panel,offer,mount,dispose,rollbackChoices,rollbackSecurity,progress};
})();
