'use strict';
(() => {
 const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 const states=new Map();
 function fields(){return `<div data-vm-source-picker><div class="field"><label for="vm-source-root">Images auf dem NAS</label><select id="vm-source-root" data-vm-source-root><option>Speicherbereiche werden geladen …</option></select></div><details><summary>Dateipfad eingeben · optional</summary><div class="field"><label for="vm-source-path">Image-Dateipfad auf dem NAS</label><input id="vm-source-path" data-vm-source-path placeholder="/var/srv/titan/images/meine-vm.qcow2" autocomplete="off"><small>QCOW2, RAW oder IMG. Die Quelle wird geprüft und in ein eigenes VM-Laufwerk kopiert.</small></div></details><div class="form-actions wrap"><button type="button" class="button small" data-vm-source-inspect>Image prüfen und auswählen</button><button type="button" class="button small" data-vm-source-browse>▱ Auf dem NAS auswählen</button></div><p class="hint" data-vm-source-status role="status" aria-live="polite"></p><div class="vm-source-browser" data-vm-source-browser hidden><div class="form-actions wrap"><button type="button" class="button small" data-vm-source-up>↑ Übergeordnet</button><code data-vm-source-current></code></div><div class="vm-source-entries" data-vm-source-entries></div><button type="button" class="button small" data-vm-source-next hidden>Weitere Einträge</button></div></div>`;}
 function disposeWithin(root){for(const [widget,state] of states)if(root===widget||root?.contains?.(widget)){state.dispose();states.delete(widget);}}
 function mount(form,options,ctx){
  const widget=form.querySelector('[data-vm-source-picker]');if(!widget)return;
  const q=selector=>widget.querySelector(selector),input=q('[data-vm-source-path]'),status=q('[data-vm-source-status]'),inspect=q('[data-vm-source-inspect]'),browse=q('[data-vm-source-browse]'),browser=q('[data-vm-source-browser]'),entries=q('[data-vm-source-entries]'),current=q('[data-vm-source-current]'),up=q('[data-vm-source-up]'),next=q('[data-vm-source-next]'),select=form.querySelector('[name="disk_image"]'),rootSelect=q('[data-vm-source-root]');
  let disposed=false,revision=0,path='',rootPath='',locations=[],offset=0;
  const inside=(value,root)=>Boolean(root&&root!=='/'&&(value===root||value.startsWith(root+'/')));
  const ready=ctx.api('/api/storage-locations').then(data=>{if(disposed)return;locations=(data.storage||data.resources||data.items||[]).filter(item=>item.path&&item.path!=='/'&&(!item.capabilities||item.capabilities.includes('files')));const chosen=locations.find(item=>item.available!==false&&item.id===data.default_storage)||locations.find(item=>item.available!==false);rootSelect.innerHTML=locations.map(item=>`<option value="${esc(item.id||item.path)}" ${item===chosen?'selected':''} ${item.available===false?'disabled':''}>${esc(item.id==='system'?'Interner Speicher':item.label)}${item.available===false?' · Nicht verfügbar':''}</option>`).join('')||'<option value="">Kein Speicher verfügbar</option>';rootPath=chosen?.path||'';path=rootPath;rootSelect.value=chosen?.id||chosen?.path||'';}).catch(error=>{if(!disposed)status.textContent='Speicherbereiche nicht erreichbar: '+error.message;});
  const clean=value=>'/'+String(value).split('/').filter(Boolean).join('/');
  async function choose(value){
   await ready;const absolute=String(value).trim();if(!absolute.startsWith('/'))throw new Error('Bitte einen absoluten NAS-Dateipfad angeben.');
   if(!locations.some(item=>item.available!==false&&inside(absolute,item.path)))throw new Error('Wähle ein Image in einem verfügbaren NAS-Speicherbereich.');
   const mine=++revision;inspect.disabled=true;status.textContent='Image wird geprüft …';
   try{const image=await ctx.api('/api/vm-image-info?'+new URLSearchParams({path:absolute}));if(disposed||mine!==revision)return;
    if(!['raw','qcow2'].includes(image.format)||!Number.isFinite(image.virtual_size)||image.virtual_size<=0)throw new Error('Der Server hat keine gültigen Image-Details geliefert.');
    options.disk_images=options.disk_images||[];const previous=options.disk_images.findIndex(item=>item.id===image.id);if(previous>=0)options.disk_images[previous]=image;else options.disk_images.push(image);
    select.innerHTML='<option value="">Image auswählen</option>'+options.disk_images.map(item=>`<option value="${esc(item.id)}">${esc(item.name)} · ${ctx.bytes(item.virtual_size)}</option>`).join('');select.value=image.id;input.value=image.path;
    select.dispatchEvent(new Event('change',{bubbles:true}));status.textContent=`${image.format.toUpperCase()} · ${ctx.bytes(image.virtual_size)} virtuelle Größe · Quelle bleibt erhalten.`;
   }catch(error){if(!disposed&&mine===revision){status.textContent=error.message;if(select.value.startsWith('/'))select.value='';}}
   finally{if(!disposed&&mine===revision)inspect.disabled=false;}
  }
  async function load(append=false){
   await ready;if(disposed||!rootPath)return;const mine=++revision;if(!append){offset=0;entries.innerHTML='';}browser.hidden=false;const resource=locations.find(item=>item.path===rootPath);current.textContent=(resource?.id==='system'?'Interner Speicher':resource?.label||'NAS-Dateien')+(path===rootPath?'':' / '+path.slice(rootPath.length+1));up.disabled=path===rootPath;status.textContent='Ordner wird geladen …';
   try{const data=await ctx.api('/api/files?'+new URLSearchParams({share:'@system',path:path.slice(1),offset:String(offset),limit:'200'}));if(disposed||mine!==revision)return;
    const items=(data.entries||[]).filter(item=>!item.symlink&&item.readable!==false&&(item.directory||/\.(qcow2|raw|img)$/i.test(item.name)));
    const html=items.map(item=>`<button type="button" class="location-folder" data-vm-source-entry="${esc(item.name)}" data-directory="${item.directory?'true':'false'}"><span>${item.directory?'▱':'▣'}</span>${esc(item.name)}<small>${item.directory?'Ordner':ctx.bytes(item.size)}</small></button>`).join('');
    if(append)entries.insertAdjacentHTML('beforeend',html);else entries.innerHTML=html;
    offset=Number(data.offset||0)+Number(data.limit||200);next.hidden=offset>=Number(data.total||0);status.textContent=items.length?'Ordner öffnen oder Image auswählen.':'Keine passenden Images in diesem Abschnitt.';
   }catch(error){if(!disposed&&mine===revision)status.textContent=error.message;}
  }
  const onInspect=()=>choose(input.value).catch(error=>{if(!disposed)status.textContent=error.message;}),onInput=()=>{revision++;inspect.disabled=false;status.textContent='Den geänderten Pfad vor der Erstellung prüfen.';if(select.value.startsWith('/'))select.value='';},onBrowse=async()=>{await ready;const value=input.value.trim(),candidate=value.startsWith('/')?clean(/\.(qcow2|raw|img)$/i.test(value)?value.split('/').slice(0,-1).join('/'):value):rootPath,resource=locations.filter(item=>item.available!==false&&inside(candidate,item.path)).sort((a,b)=>b.path.length-a.path.length)[0];if(resource){rootPath=resource.path;rootSelect.value=resource.id||resource.path;path=candidate;}else path=rootPath;return load();},onUp=()=>{if(path===rootPath)return;const parent=clean(path.split('/').slice(0,-1).join('/'));path=inside(parent,rootPath)?parent:rootPath;return load();},onNext=()=>load(true),onEntry=event=>{const target=event.target.closest('[data-vm-source-entry]');if(!target)return;const name=target.dataset.vmSourceEntry;if(!name||name==='.'||name==='..'||name.includes('/'))return;const full=clean(path+'/'+name);if(target.dataset.directory==='true'){path=full;load();}else{input.value=full;choose(full);}};
  const onRoot=()=>{const resource=locations.find(item=>(item.id||item.path)===rootSelect.value&&item.available!==false);rootPath=resource?.path||'';path=rootPath;input.value='';if(select.value.startsWith('/'))select.value='';if(!browser.hidden)load();};rootSelect.addEventListener('change',onRoot);
  inspect.addEventListener('click',onInspect);input.addEventListener('input',onInput);browse.addEventListener('click',onBrowse);up.addEventListener('click',onUp);next.addEventListener('click',onNext);entries.addEventListener('click',onEntry);
  states.set(widget,{dispose(){disposed=true;revision++;rootSelect.removeEventListener('change',onRoot);inspect.removeEventListener('click',onInspect);input.removeEventListener('input',onInput);browse.removeEventListener('click',onBrowse);up.removeEventListener('click',onUp);next.removeEventListener('click',onNext);entries.removeEventListener('click',onEntry);}});
 }
 window.TitanVMImages={fields,mount,disposeWithin};
})();
