'use strict';
// Each internal app keeps its own document, selection, forms and live connection.
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanWorkspace=ui;})(typeof window==='undefined'?null:window,function(){
 const clamp=(n,low,high)=>Math.max(low,Math.min(high,Number.isFinite(n)?n:low));
 function geometry(value={},bounds={width:1200,height:800},index=0){
  const width=clamp(Number(value.width)||Math.min(980,bounds.width*.88),Math.min(320,bounds.width),bounds.width),height=clamp(Number(value.height)||Math.min(680,bounds.height*.88),Math.min(240,bounds.height),bounds.height);
  return {width,height,x:clamp(Number.isFinite(value.x)?value.x:24+index*28,0,Math.max(0,bounds.width-width)),y:clamp(Number.isFinite(value.y)?value.y:24+index*28,0,Math.max(0,bounds.height-height))};
 }
 function preferences(value,allowed){
  const safe=value&&typeof value==='object'?value:{};
  const layouts={};for(const id of allowed)if(safe.layouts?.[id]&&typeof safe.layouts[id]==='object')layouts[id]={geometry:safe.layouts[id].geometry||{},maximized:safe.layouts[id].maximized===true};
  return {active:allowed.includes(safe.active)?safe.active:null,layouts,theme:['sky','dusk','forest'].includes(safe.theme)?safe.theme:'sky',pins:[...new Set(Array.isArray(safe.pins)?safe.pins:[])].filter(id=>allowed.includes(id)),windows:(Array.isArray(safe.windows)?safe.windows:[]).filter(item=>item&&allowed.includes(item.id)).filter((item,i,all)=>all.findIndex(row=>row.id===item.id)===i).slice(0,16).map(item=>({id:item.id,minimized:item.minimized===true,maximized:item.maximized===true,geometry:item.geometry||{}}))};
 }
 let current=null;
 function mount({doc=document,user,tools,icon,esc,api,toast,confirm,logout}={}){
  current?.destroy();const shell=doc.querySelector('#shell'),workspace=doc.querySelector('.workspace'),main=doc.querySelector('#main');
  const win=doc.defaultView,allowed=tools.map(t=>t[0]),titles=new Map(tools.map(t=>[t[0],t[1]]));
  const key='titan-desktop-v2:'+encodeURIComponent(user.name);let storage;try{storage=win.localStorage;}catch{}
  let saved;try{saved=JSON.parse(storage?.getItem(key)||'{}');}catch{}let prefs=preferences(saved,allowed),active=null,z=10,alive=true,gesture=null,pendingFrame=null;
  let shortcuts=null;let restoring=true;const frames=new Map();shell.dataset.desktop='true';shell.dataset.wallpaper=prefs.theme;
  const layer=doc.createElement('div');layer.className='desktop-window-layer';layer.setAttribute('aria-label','Geöffnete Anwendungen');workspace.append(layer);
  const tasks=doc.querySelector('#desktop-tasks');let observer=typeof win.ResizeObserver==='function'?new win.ResizeObserver(()=>resize()):null;observer?.observe(doc.querySelector('.topbar'));const menu=doc.createElement('dialog');menu.className='desktop-menu-dialog';menu.setAttribute('aria-label','Hauptmenü');doc.body.append(menu);
  const account=doc.createElement('div');account.className='desktop-account shortcut-context';account.hidden=true;account.setAttribute('role','menu');account.innerHTML=`<strong>${esc(user.name)}</strong><button role="menuitem" data-action="profile-menu">Persönlich</button>${user.role==='admin'?'<button role="menuitem" data-action="system-reboot">Neu starten</button><button role="menuitem" data-action="system-shutdown">Herunterfahren</button>':''}<button role="menuitem" data-action="logout">Abmelden</button>`;doc.body.append(account);
  function closeAccount(){account.hidden=true;doc.querySelector('#profile')?.setAttribute('aria-expanded','false');}
  function mobile(){return win.matchMedia('(max-width: 760px)').matches;}
  function bounds(){layer.style.top=doc.querySelector('.topbar').getBoundingClientRect().height+'px';return {width:layer.clientWidth||win.innerWidth||1200,height:layer.clientHeight||win.innerHeight||800};}
  function save(){if(restoring)return;prefs.active=active;for(const item of frames.values())prefs.layouts[item.id]={geometry:item.geometry,maximized:item.maximized};prefs.windows=[...frames.values()].map(item=>({id:item.id,minimized:item.minimized,maximized:item.maximized,geometry:item.geometry}));try{storage?.setItem(key,JSON.stringify(prefs));}catch{}}
  function place(item){const g=mobile()?item.geometry:geometry(item.geometry,bounds());item.node.classList.toggle('desktop-maximized',item.maximized);for(const [field,value]of Object.entries(g))item.node.style[field==='x'?'left':field==='y'?'top':field]=value+'px';item.node.hidden=item.minimized;item.node.querySelector('[data-frame-maximize]').setAttribute('aria-pressed',String(item.maximized));item.node.querySelector('[data-frame-maximize]').textContent=item.maximized?'Wiederherstellen':'Maximieren';}
  function taskbar(){tasks.innerHTML=[...new Set([...prefs.pins,...frames.keys()])].map(id=>{const item=frames.get(id);return `<button class="desktop-task ${item?'is-open':''} ${id===active&&!item?.minimized?'is-active':''}" data-desktop-task="${id}" aria-pressed="${id===active&&!item?.minimized}" title="${esc(titles.get(id))}${item?.minimized?' · minimiert':''}">${icon(id)}<span>${esc(titles.get(id))}</span></button>`;}).join('');tasks.querySelector('[aria-pressed="true"]')?.scrollIntoView?.({block:'nearest',inline:'nearest'});shell.dataset.activeApp=active||'';for(const item of frames.values())item.node.dataset.mobileActive=String(item.id===active&&!item.minimized);}
  function focus(id){const item=frames.get(id);if(!item)return;item.minimized=false;active=id;item.node.style.zIndex=String(++z);place(item);taskbar();save();}
  function desktop(){for(const item of frames.values()){item.minimized=true;place(item);}active=null;taskbar();save();win.history.replaceState(null,'','#dashboard');doc.querySelector('#show-desktop')?.focus();}
  function route(hash){let id=String(hash||'').replace(/^#/,'').split('?')[0];if(id==='dashboard'||!id){desktop();return;}if(id==='control')id='settings';if(id==='apps'){id='docker';hash='#docker?section=templates';}if(!allowed.includes(id))return;
   const params=new URLSearchParams(String(hash).split('?')[1]||''),app=params.get('app'),section=params.get('section');const appId=app&&/^[a-zA-Z0-9_-]{1,64}$/.test(app)?app:null;const suffix=appId?'?app='+encodeURIComponent(appId):section&&/^[a-z-]{1,40}$/.test(section)?'?section='+encodeURIComponent(section):'';
   menu.close();if(frames.has(id)){focus(id);if(section&&['settings','docker'].includes(id))frames.get(id).node.querySelector('iframe').contentWindow.postMessage({type:'titan-navigate',hash:'#settings'+suffix},win.location.origin);if(appId)frames.get(id).node.querySelector('iframe').contentWindow.postMessage({type:'titan-manage-app',id:appId},win.location.origin);return;}
   const old=prefs.windows.find(item=>item.id===id)||prefs.layouts[id];const area=bounds(),initialBounds=mobile()?{width:Math.max(1200,area.width),height:Math.max(800,area.height)}:area;const item={id,minimized:false,maximized:old?.maximized||false,geometry:geometry(old?.geometry,initialBounds,frames.size)};
   const node=doc.createElement('section');node.className='desktop-window';node.setAttribute('aria-label',titles.get(id));node.dataset.frame=id;
   node.innerHTML=`<header class="desktop-window-titlebar"><div class="desktop-window-caption">${icon(id)}<strong>${esc(titles.get(id))}</strong></div><div class="desktop-window-controls"><button data-frame-pin title="An Taskleiste anheften" aria-label="${esc(titles.get(id))}: Anheften" aria-pressed="${prefs.pins.includes(id)}">☆</button><button data-frame-minimize title="Minimieren" aria-label="${esc(titles.get(id))}: Minimieren">−</button><button data-frame-maximize aria-pressed="false">Maximieren</button><button data-frame-close title="Schließen" aria-label="${esc(titles.get(id))}: Schließen">×</button></div></header><iframe class="desktop-app-frame" title="${esc(titles.get(id))}" src="/?desktop-app=1#${id}${suffix}"></iframe><button class="desktop-window-resize" aria-label="Fenstergröße ändern: Pfeiltasten verwenden" title="Größe ändern" data-frame-resize>◢</button>`;
   item.node=node;frames.set(id,item);layer.append(node);place(item);focus(id);
   node.addEventListener('pointerdown',()=>{if(active!==id)focus(id);});
   node.querySelector('[data-frame-pin]').onclick=e=>{prefs.pins=prefs.pins.includes(id)?prefs.pins.filter(key=>key!==id):[...prefs.pins,id];e.currentTarget.setAttribute('aria-pressed',String(prefs.pins.includes(id)));taskbar();save();};
   node.querySelector('[data-frame-minimize]').onclick=()=>{item.minimized=true;active=null;place(item);taskbar();save();};
   node.querySelector('[data-frame-maximize]').onclick=()=>{item.maximized=!item.maximized;place(item);save();};
   node.querySelector('[data-frame-close]').onclick=async()=>{const child=node.querySelector('iframe').contentWindow;let dirty=false;try{dirty=child.titanHasUnsavedWork?.()===true;}catch{}if(dirty&&!await confirm('Offene Eingaben oder eine Konsolensitzung verwerfen und das Fenster schließen?'))return;node.remove();frames.delete(id);if(active===id)active=null;taskbar();save();};
   const bar=node.querySelector('header'),grip=node.querySelector('[data-frame-resize]');bar.setAttribute('tabindex','0');bar.setAttribute('aria-label',titles.get(id)+': Fenster mit Pfeiltasten verschieben');bar.addEventListener('keydown',e=>{if(e.target!==bar||item.maximized||win.matchMedia('(max-width:760px)').matches||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();item.geometry.x+=e.key==='ArrowRight'?24:e.key==='ArrowLeft'?-24:0;item.geometry.y+=e.key==='ArrowDown'?24:e.key==='ArrowUp'?-24:0;item.geometry=geometry(item.geometry,bounds());place(item);save();});
   function start(event,resize){if(gesture||mobile()||item.maximized||(!resize&&event.target.closest('button')))return;if(event.button!==0)return;event.preventDefault();focus(id);item.geometry=geometry(item.geometry,bounds());gesture={item,resize,startX:event.clientX,startY:event.clientY,geometry:{...item.geometry},target:event.currentTarget,id:event.pointerId};shell.classList.add('desktop-moving');try{event.currentTarget.setPointerCapture?.(event.pointerId);}catch{end();}}
   bar.addEventListener('pointerdown',e=>start(e,false));grip.addEventListener('pointerdown',e=>start(e,true));bar.addEventListener('lostpointercapture',end);grip.addEventListener('lostpointercapture',end);bar.addEventListener('dblclick',e=>{if(!e.target.closest('button'))node.querySelector('[data-frame-maximize]').click();});
   grip.addEventListener('keydown',e=>{if(item.maximized||mobile()||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();item.geometry.width+=e.key==='ArrowRight'?24:e.key==='ArrowLeft'?-24:0;item.geometry.height+=e.key==='ArrowDown'?24:e.key==='ArrowUp'?-24:0;item.geometry=geometry(item.geometry,bounds());place(item);save();});
   return item;
  }
  function menuCard(key,name,detail,glyph){return `<div class="desktop-menu-entry" data-search="${esc((name+' '+detail).toLowerCase())}"><button class="desktop-menu-app" data-menu-launch="${esc(key)}"><span class="desktop-app-icon" data-app="${esc(glyph)}">${key.startsWith('app:')?(win.TitanArtwork?.render(key.slice(4))||icon('apps')):(win.TitanArtwork?.tool(glyph)||icon(glyph))}</span><strong>${esc(name)}</strong></button><button class="desktop-add-shortcut" data-menu-add="${esc(key)}" ${!shortcuts||shortcuts.contains(key)?'disabled':''}>${shortcuts?.contains(key)?'Auf dem Desktop':'Zum Desktop hinzufügen'}</button></div>`;}
  async function openMenu(){closeAccount();menu.innerHTML=`<div class="desktop-menu-heading"><h2>Hauptmenü</h2><button class="button" data-menu-close>Schließen</button></div><label class="desktop-search">Anwendung suchen<input type="search" placeholder="Dateien, Docker, Einstellungen …" data-desktop-search></label><div class="desktop-menu-grid">${tools.filter(([id])=>!['users','shares','updates'].includes(id)).map(([id,name,detail])=>menuCard('tool:'+id,name,detail,id)).join('')}</div><p data-menu-empty hidden>Keine passende Anwendung gefunden.</p><section class="desktop-installed"><h3>Installierte Apps</h3><div data-installed-apps>Apps werden geladen …</div></section><details class="desktop-appearance"><summary>Desktop-Hintergrund</summary><div>${[['sky','Himmel'],['dusk','Abend'],['forest','Wald']].map(([id,label])=>`<button class="button" data-wallpaper="${id}" aria-pressed="${prefs.theme===id}">${label}</button>`).join('')}</div></details>`;menu.showModal();menu.querySelector('input').focus();
   if(user.role!=='admin'&&!user.permissions?.apps?.allowed){menu.querySelector('.desktop-installed').hidden=true;return;}
   await shortcuts?.refreshApps();if(!alive||!menu.open)return;
   menu.querySelector('[data-installed-apps]').innerHTML=(shortcuts?.entries()||[]).filter(([key])=>key.startsWith('app:')).map(([key,item])=>menuCard(key,item.name,item.detail,'apps')).join('')||'<p>Noch keine Apps installiert.</p>';search({target:menu.querySelector('[data-desktop-search]')});
  }
  function click(e){const target=e.target.closest('button,a');if(!target)return;
   if(target.id==='profile'){account.hidden=!account.hidden;target.setAttribute('aria-expanded',String(!account.hidden));if(!account.hidden)account.querySelector('button')?.focus();return;}
   if(!account.hidden)closeAccount();
   if(target.dataset.menuAdd){if(shortcuts?.add(target.dataset.menuAdd)){target.disabled=true;target.textContent='Auf dem Desktop';}return;}
   if(target.dataset.menuLaunch){const key=target.dataset.menuLaunch;menu.close();if(key.startsWith('app:'))shortcuts?.open(key);else route('#'+key.slice(5));return;}
   if(target.id==='main-menu'){e.preventDefault();void openMenu();return;}
   if(target.id==='show-desktop'||target.classList.contains('desktop-brand')){e.preventDefault();desktop();return;}
   if(target.dataset.desktopOpen){route('#'+target.dataset.desktopOpen+(target.dataset.appId?'?app='+encodeURIComponent(target.dataset.appId):''));win.history.replaceState(null,'','#'+target.dataset.desktopOpen);return;}
   if(target.dataset.desktopTask){const item=frames.get(target.dataset.desktopTask);if(item&&!item.minimized&&active===item.id){item.minimized=true;active=null;place(item);taskbar();save();}else {win.history.replaceState(null,'','#'+target.dataset.desktopTask);route('#'+target.dataset.desktopTask);}return;}
   if(target.hasAttribute('data-menu-close'))menu.close();
   if(target.dataset.wallpaper){prefs.theme=target.dataset.wallpaper;shell.dataset.wallpaper=prefs.theme;menu.querySelectorAll('[data-wallpaper]').forEach(b=>b.setAttribute('aria-pressed',String(b===target)));save();}
   if(target.matches('a[href^="#"]')&&!target.classList.contains('skip-link')&&!target.dataset.action){e.preventDefault();const hash=target.getAttribute('href');win.history.replaceState(null,'',hash);route(hash);}
  }
  function search(e){if(!e.target.matches('[data-desktop-search]'))return;const words=e.target.value.toLowerCase().trim().split(/\s+/);let count=0;menu.querySelectorAll('[data-search]').forEach(item=>{item.hidden=!words.every(word=>item.dataset.search.includes(word));if(!item.hidden)count++;});menu.querySelector('[data-menu-empty]').hidden=count>0;}
  function move(e){if(!gesture||e.pointerId!==gesture.id)return;const g=gesture,dx=e.clientX-g.startX,dy=e.clientY-g.startY;g.item.geometry={...g.geometry,...(g.resize?{width:g.geometry.width+dx,height:g.geometry.height+dy}:{x:g.geometry.x+dx,y:g.geometry.y+dy})};if(!win.requestAnimationFrame){place(g.item);return;}if(pendingFrame===null)pendingFrame=win.requestAnimationFrame(()=>{pendingFrame=null;if(gesture===g&&alive)place(g.item);});}
  function end(event){if(!gesture||event&&event.pointerId!==undefined&&event.pointerId!==gesture.id)return;const g=gesture;if(pendingFrame!==null){win.cancelAnimationFrame?.(pendingFrame);pendingFrame=null;}g.item.geometry=geometry(g.item.geometry,bounds());place(g.item);gesture=null;try{g.target.releasePointerCapture?.(g.id);}catch{}shell.classList.remove('desktop-moving');save();}
  function resize(){bounds();for(const item of frames.values())place(item);}
  function message(e){if(e.origin!==win.location.origin)return;const item=[...frames.values()].find(item=>item.node.querySelector('iframe').contentWindow===e.source);if(!item)return;if(e.data?.type==='titan-open'&&typeof e.data.hash==='string')route(e.data.hash);if(e.data?.type==='titan-focus'&&active!==item.id)focus(item.id);if(e.data?.type==='titan-logout')logout();if(e.data?.type==='titan-apps-changed')void shortcuts?.refreshApps();}
  function keys(e){if(e.key==='Escape'&&!account.hidden){closeAccount();doc.querySelector('#profile')?.focus();}if(e.key==='Escape'&&menu.open)menu.close();if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();void openMenu();}}
  doc.addEventListener('click',click,true);doc.addEventListener('input',search);doc.addEventListener('pointermove',move);doc.addEventListener('pointerup',end);doc.addEventListener('pointercancel',end);doc.addEventListener('keydown',keys);win.addEventListener('resize',resize);win.addEventListener('message',message);
  for(const old of prefs.windows.slice()){route('#'+old.id);const item=frames.get(old.id);item.minimized=old.minimized;place(item);}restoring=false;const resumed=prefs.active;active=null;if(resumed&&frames.has(resumed)&&!frames.get(resumed).minimized)focus(resumed);taskbar();
  current={route,desktop,openMenu,setShortcuts(value){shortcuts=value;},destroy(){alive=false;observer?.disconnect();end();for(const item of frames.values())item.node.remove();frames.clear();layer.remove();menu.remove();account.remove();tasks.innerHTML='';delete shell.dataset.desktop;doc.removeEventListener('click',click,true);doc.removeEventListener('input',search);doc.removeEventListener('pointermove',move);doc.removeEventListener('pointerup',end);doc.removeEventListener('pointercancel',end);doc.removeEventListener('keydown',keys);win.removeEventListener('resize',resize);win.removeEventListener('message',message);}};return current;
 }
 return {geometry,preferences,mount,dispose(){current?.destroy();current=null;}};
});
