[system]
compatible=titan-debian13-amd64-ab-v1
bootloader=grub
grubenv=/boot/titan/grubenv
data-directory=/var/lib/titan-system/rauc
bundle-formats=verity
activate-installed=false

[keyring]
path=/usr/share/titan/rauc-root.pem
check-purpose=codesign

[slot.rootfs.0]
device=/dev/disk/by-partlabel/TITAN-A
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/TITAN-B
type=ext4
bootname=B
