'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={window:{},URL,console,FormData,setInterval:()=>1,clearInterval(){},setTimeout};vm.createContext(context);vm.runInContext(fs.readFileSync('titan/web/app_networks.js','utf8'),context);
const ui=context.window.TitanNetworks,inventory={networks:[{name:'bridge',driver:'bridge',selectable:true},{name:'my-apps',driver:'bridge',selectable:true,static_ipv4:true,subnets:[{subnet:'172.30.50.0/24',gateway:'172.30.50.1'}]},{name:'unsafe<script>',driver:'bridge',selectable:true},{name:'overlay',driver:'overlay',selectable:false}]};
const markup=ui.installFields({id:'heimdall',port:80},inventory);assert(markup.includes('Optional'));assert(markup.includes('Host'));assert(markup.includes('network:my-apps'));assert(markup.includes('unsafe&lt;script&gt;'));assert(!markup.includes('network:overlay'));assert(markup.includes('data-network-create'));assert(markup.includes('hidden'));
assert.doesNotMatch(markup, /data-network-name[^>]*required/, 'Optional network creation must not block the app install form');
function createFor(values){const data=new FormData();for(const [key,value] of Object.entries(values))data.set(key,value);return JSON.parse(JSON.stringify(ui.createArguments(data)));}
assert.deepEqual(createFor({name:'my-apps'}),{name:'my-apps',internal:false});
assert.deepEqual(createFor({name:'my-apps',subnet:'172.30.0.0/24',gateway:'172.30.0.1',internal:'on'}),{name:'my-apps',subnet:'172.30.0.0/24',gateway:'172.30.0.1',internal:true});
assert.throws(()=>createFor({name:'$(id)'}));assert.throws(()=>createFor({name:'my-apps',gateway:'172.30.0.1'}),/Subnetz/);
const protectedNetworks={networks:[{name:'bridge',driver:'bridge',managed:false,deletion_reason:'Docker-Systemnetzwerk'},{name:'my-apps',driver:'bridge',managed:true,subnets:[{subnet:'172.30.0.0/24',gateway:'172.30.0.1'}],containers:[],used_by:[],removable:true},{name:'occupied',driver:'bridge',managed:true,containers:[],used_by:['stopped-app'],removable:false,deletion_reason:'Noch verwendet'}]};
const manager=ui.inventoryPanel(protectedNetworks,{selected:'my-apps'});assert.match(manager,/data-network-action="create"/);assert.match(manager,/Gateway 172\.30\.0\.1/);assert.match(manager,/data-name="occupied" disabled/);assert.match(manager,/Docker-Systemnetzwerk/);assert.doesNotMatch(manager,/data-action="app-network-remove"/);
assert.equal(ui.removable(protectedNetworks.networks[0]),false);assert.equal(ui.removable(protectedNetworks.networks[1]),true);assert.equal(ui.removable(protectedNetworks.networks[2]),false);
function argumentsFor(values){const data=new FormData();for(const [key,value] of Object.entries(values))data.set(key,value);return JSON.parse(JSON.stringify(ui.installArguments({},data)));}
assert.deepEqual(argumentsFor({}),{});assert.deepEqual(argumentsFor({network_mode:'default',network_ipv4:'bad'}),{});assert.deepEqual(argumentsFor({network_mode:'host',network_ipv4:'bad'}),{network:{mode:'host'}});assert.deepEqual(argumentsFor({network_mode:'bridge'}),{network:{mode:'bridge'}});assert.deepEqual(argumentsFor({network_mode:'network:my-apps',network_ipv4:'172.30.50.10'}),{network:{mode:'bridge',name:'my-apps',ipv4_address:'172.30.50.10'}});assert.throws(()=>argumentsFor({network_mode:'network:my-apps',network_ipv4:'999.2.3.4'}),/gültige/);assert.throws(()=>argumentsFor({network_mode:'injected'}),/auswählen/);
assert.equal(ui.safeUrl('javascript:alert(1)'), '');assert.equal(ui.safeUrl('https://user:pass@host/'),'');assert.equal(ui.connection({endpoints:[{scope:'loopback',url:'http://127.0.0.1:80/'},{scope:'lan',url:'http://192.168.1.8:8080/'}]}),'http://192.168.1.8:8080/');assert.equal(ui.summary({network_mode:'host'}),'Host-Netz · NAS-Adressen');assert.equal(ui.summary({networks:[{ipv4:'172.30.50.10',ipv6:'fd00::1'}]}),'172.30.50.10 · fd00::1');
const details=ui.details({network_mode:'bridge',networks:[{name:'bad<script>',driver:'bridge',ipv4:'172.30.50.10',gateway:'172.30.50.1'}],host_addresses:[{address:'192.168.1.8',interface:'eth0'}],endpoints:[{scope:'lan',url:'http://192.168.1.8:8080/'},{url:'javascript:alert(1)'}]});assert(details.includes('bad&lt;script&gt;'));assert(details.includes('172.30.50.10'));assert(details.includes('192.168.1.8'));assert(details.includes('Nicht ermittelt'));assert(!details.includes('javascript:'));
const callbacks={},nodes={};function node(key){return nodes[key]||=({value:'',disabled:false,hidden:false,readOnly:false,textContent:'',addEventListener(type,fn){callbacks[key+':'+type]=fn;},removeEventListener(){}});}
const form={querySelector:node},widget={querySelector:node,closest:()=>form},root={querySelector:()=>widget,contains:()=>true};node('[name="port"]').value='18080';node('[data-network-mode]').value='default';ui.mountInstall(root,{port:80},inventory,{api:async()=>{throw Error('No request expected');}});
node('[data-network-mode]').value='host';callbacks['[data-network-mode]:change']();assert.equal(node('[name="port"]').value,'80');assert(node('[name="port"]').readOnly);assert.equal(node('[name="port"]').min,'1');assert(node('[data-network-ip]').disabled);
node('[data-network-mode]').value='default';callbacks['[data-network-mode]:change']();assert.equal(node('[name="port"]').value,'18080');assert.equal(node('[name="port"]').min,'1024');
node('[data-network-mode]').value='network:my-apps';callbacks['[data-network-mode]:change']();assert.equal(node('[data-network-ip-field]').hidden,false);assert.equal(node('[data-network-ip]').disabled,false);assert(node('[data-network-description]').textContent.includes('172.30.50.0/24'));ui.disposeWithin(root);
node('[name="port"]').value='80';ui.mountInstall(root,{port:80,docker_template:true},inventory,{api:async()=>{throw Error('No request expected');}});assert.equal(node('[name="port"]').min,'1');node('[data-network-mode]').value='host';callbacks['[data-network-mode]:change']();node('[data-network-mode]').value='bridge';callbacks['[data-network-mode]:change']();assert.equal(node('[name="port"]').value,'80');assert.equal(node('[name="port"]').min,'1');assert(!node('[name="port"]').readOnly);ui.disposeWithin(root);
console.log('App network UI: optional defaults, host actual port, custom bridge/static-IP selection, observed addresses, safe links, escaping and disposal passed.');

assert.equal(ui.summary({state:'running',container:{state:'running',networks:[{ipv4:'172.30.50.10'}]}}),'172.30.50.10');assert.equal(ui.connection({container:{endpoints:[{scope:'lan',url:'http://192.168.1.8:8080/'}]}}),'http://192.168.1.8:8080/');
