'use strict';
const assert=require('node:assert/strict'),shortcuts=require('../titan/web/desktop_shortcuts.js'),widgets=require('../titan/web/desktop_widgets.js');
function element(doc){return {ownerDocument:doc,hidden:false,style:{},dataset:{},children:[],handlers:new Map(),classList:{add(){},remove(){}},setAttribute(){},hasAttribute(){return false;},addEventListener(type,fn){this.handlers.set(type,fn);},removeEventListener(type,fn){if(this.handlers.get(type)===fn)this.handlers.delete(type);},append(child){this.children.push(child);},contains(child){return this.children.includes(child);},remove(){},querySelector(){return null;},querySelectorAll(){return [];},close(){this.open=false;},showModal(){this.open=true;}};}
async function main(){
 const win={innerWidth:320,innerHeight:740,ResizeObserver:class{constructor(fn){this.callback=fn;resize=fn;}observe(){}disconnect(){}},open(){}};let resize;
 const doc={defaultView:win,hidden:false,activeElement:null,handlers:new Map(),createElement(){return element(doc);},addEventListener(type,fn){this.handlers.set(type,fn);},removeEventListener(type){this.handlers.delete(type);},elementFromPoint(){return null;}};doc.body=element(doc);
 const surface=element(doc);surface.clientWidth=304;surface.clientHeight=600;surface.scrollLeft=surface.scrollTop=0;surface.getBoundingClientRect=()=>({left:0,top:0});surface.setPointerCapture=()=>{};
 let cards=[];Object.defineProperty(surface,'innerHTML',{set(html){cards=[...html.matchAll(/data-shortcut="([^"]+)"/g)].map(match=>{const node=element(doc);node.dataset.shortcut=match[1];return node;});},get(){return '';}});surface.querySelectorAll=selector=>selector==='[data-shortcut]'?cards:[];surface.contains=node=>cards.includes(node);
 const tools=['files','docker','vms','photos','settings','storage'].map(id=>[id,id]);const desktop={ 'tool:files':{x:4,y:3},'tool:docker':{x:3,y:1},'tool:settings':{x:6,y:2} };let saved;
 const ui=await shortcuts.mount(surface,{tools,user:{role:'admin'},icon:()=>'',esc:String,api:async(path,value)=>{if(value){saved=structuredClone(value);return value;}return path==='/api/launcher-layout'?{version:2,items:tools.map(([id])=>'tool:'+id),positions:desktop,widgets:{visible:true,collapsed:false}}:{installed:[]};},toast(){},open(){},menu(){}});
 assert.deepEqual(cards.map(node=>[node.style.left,node.style.top]),[['0px','0px'],['108px','0px'],['0px','108px'],['108px','108px'],['0px','216px'],['108px','216px']]);
 win.innerWidth=390;surface.clientWidth=374;resize();assert.deepEqual(cards.map(node=>[node.style.left,node.style.top]),[['0px','0px'],['108px','0px'],['216px','0px'],['0px','108px'],['108px','108px'],['216px','108px']]);win.innerWidth=320;surface.clientWidth=304;resize();
 assert.equal(saved,undefined,'Responsive presentation alone must not persist desktop changes');
 // Drag Files onto the next cell via the actual pointer handlers, without grouping.
 const file=cards[0],target={closest:selector=>selector==='[data-shortcut]'?file:null};surface.handlers.get('pointerdown')({button:0,pointerId:1,clientX:20,clientY:20,target});doc.handlers.get('pointermove')({pointerId:1,clientX:150,clientY:20,preventDefault(){}});doc.handlers.get('pointerup')({pointerId:1,clientX:150,clientY:20,type:'pointerup'});await Promise.resolve();
 assert.deepEqual(saved.positions,desktop,'Touch reordering retains every persisted desktop coordinate');assert.deepEqual(saved.mobile_positions['tool:files'],{x:1,y:0});assert.deepEqual(saved.mobile_positions['tool:docker'],{x:0,y:0});
 win.innerWidth=1440;surface.clientWidth=1000;resize();const desktopFile=cards.find(node=>node.dataset.shortcut==='tool:files');assert.equal(desktopFile.style.left,'432px');assert.equal(desktopFile.style.top,'324px');ui.destroy();
 // Actual widget rendering defaults to collapsed mobile, expands on explicit
 // choice, and returns to its independent desktop setting after resize.
 const events=new Map(),widgetWin={innerWidth:320,setInterval:()=>1,clearInterval(){},addEventListener(type,fn){events.set(type,fn);},removeEventListener(type){events.delete(type);}};
 const widgetDoc={defaultView:widgetWin,hidden:false,activeElement:null,createElement(){return element(widgetDoc);},addEventListener(){},removeEventListener(){}};widgetDoc.body=element(widgetDoc);const toggle=element(widgetDoc);widgetDoc.querySelector=()=>toggle;let prefs,reads=0;
 const panel=widgets.mount({doc:widgetDoc,user:{role:'admin'},api:async()=>{reads++;return {cpu_percent:0,memory_total:8,memory_occupied:2};},esc:String,bytes:String,preferences:{visible:true,collapsed:false,items:['cpu','ram']},save:value=>prefs=value,open(){},jobs(){}});const box=widgetDoc.body.children[0];assert.match(box.innerHTML,/widget-content" hidden/);assert.equal(reads,0,'Collapsed mobile widget avoids polling hidden metrics');
 const collapse={hasAttribute:key=>key==='data-widget-collapse',dataset:{}};box.handlers.get('click')({target:{closest:()=>collapse}});await Promise.resolve();assert.equal(prefs.collapsed,false);assert.equal(prefs.collapsed_mobile,false);assert.doesNotMatch(box.innerHTML,/widget-content" hidden/);assert.equal(reads,1);
 widgetWin.innerWidth=1440;events.get('resize')();assert.doesNotMatch(box.innerHTML,/widget-content" hidden/);box.handlers.get('click')({target:{closest:()=>collapse}});assert.equal(prefs.collapsed,true);assert.equal(prefs.collapsed_mobile,false);widgetWin.innerWidth=320;events.get('resize')();assert.doesNotMatch(box.innerHTML,/widget-content" hidden/,'Explicit mobile expansion survives desktop collapse');panel.destroy();assert.equal(events.size,0);
 console.log('Actual mobile desktop packs row-major, persists touch positions independently, and preserves explicit widget choices across resize.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
