'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ui=require('../titan/web/docker_workbench.js');
assert.deepEqual(ui.containerStorageConfig('system'),{storage_id:'system'});assert.deepEqual(ui.containerStorageConfig('volume:photos'),{storage_id:'volume:photos'});assert.deepEqual(ui.containerStorageConfig('@docker-volume:photos'),{volume:'photos'});assert.deepEqual(ui.containerStorageConfig(''),{});assert.throws(()=>ui.containerStorageConfig('/etc'),/gültigen Speicher/);
assert.deepEqual(ui.parsePorts('8080:80\n8443:443/tcp\n5353:5353/udp'),[{published:8080,target:80,protocol:'tcp'},{published:8443,target:443,protocol:'tcp'},{published:5353,target:5353,protocol:'udp'}]);
assert.throws(()=>ui.parsePorts('$(id)'));assert.throws(()=>ui.parseEnv('SECRET=a\nSECRET=b'));
const env=ui.parseEnv('KEY=a=b\n__proto__=safe');assert.equal(env.KEY,'a=b');assert.equal(env.__proto__,'safe');assert.equal(Object.getPrototypeOf(env),Object.prototype);
assert.match(ui.ports({'80/tcp':[{'HostIp':'0.0.0.0','HostPort':'8080'}]}),/8080 → 80/);
assert.match(ui.metric({cpu_percent:0,memory_bytes:0},String),/RAM gesamt <strong>0/);
assert.match(ui.metric({},String),/RAM gesamt <strong>—/);
const live=require('../titan/web/vm_live.js');const render=vm=>live.render(vm,{bytes:v=>String(v),esc:String});
const stopped=render({state:'shut off',cpus:2,memory_mb:4096,metrics:{cpu_percent:97,memory_resident_bytes:9999999,memory_guest_used_bytes:9999999}});
assert.match(stopped,/CPU live[^]*?<strong>0 %/);assert.match(stopped,/RAM-Verbrauch auf dem NAS<\/small><strong>0<\/strong>/);assert(!stopped.includes('9999999'));assert(!stopped.includes('zugewiesen'));
assert.match(render({state:'running',cpus:2,memory_mb:4096,metrics:{memory_resident_bytes:12345,memory_guest_used_bytes:1}}),/strong>12345/);
console.log('Docker workbench parser and stopped VM resource regressions passed.');
const containers=[{id:'a',name:'Alpha',image:'nginx',state:'running',project:'web',health:'healthy',networks:[]},{id:'b',name:'Beta',image:'redis',state:'exited',project:'web',networks:[]},{id:'c',name:'Gamma',image:'busybox',state:'running',health:'unhealthy',networks:[]}];
assert.deepEqual(ui.filtered(containers,'web','all','za').map(c=>c.id),['b','a']);
assert.deepEqual(ui.filtered(containers,'','stopped').map(c=>c.id),['b']);
assert.deepEqual(ui.filtered(containers,'','unhealthy').map(c=>c.id),['c']);
assert.equal(ui.stacks(containers)[0][1].length,2);
assert.equal(ui.totals(containers,{a:{memory_bytes:100},b:{memory_bytes:999},c:{memory_bytes:50}}).memory,150);
assert.equal(ui.totals(containers,{a:{memory_bytes:100}}).memory,null);
assert.equal(ui.totals([containers[1]],{}).memory,0);
console.log('Docker filters, Compose grouping and actual RAM totals passed.');

const web={state:'running',managed_app:'syncthing',web_port:8384,ports:{'22000/tcp':[{HostPort:'22000',HostIp:'0.0.0.0'}],'8384/tcp':[{HostPort:'18084',HostIp:'0.0.0.0'}]}};
assert.equal(ui.webLink(web,'nas.local'),'http://nas.local:18084');
assert.equal(ui.webLink({...web,network_mode:'host',ports:{}},'nas.local'),'http://nas.local:8384');
assert.equal(ui.webLink({...web,network_mode:'host',ports:{},web_port:9090},'::1'),'http://[::1]:9090');
assert.equal(new URL(ui.webLink({...web,network_mode:'host',ports:{},web_port:9090},'[::1]')).href,'http://[::1]:9090/');
// Exercise the same hostname normalization used by the legacy app fallback.
const hostHelper=fs.readFileSync(require.resolve('../titan/web/app.js'),'utf8').match(/function appUrlHost[^]*?\n/)[0];
const fallbackHost={location:{hostname:'[2001:db8::1]'}};
vm.runInNewContext(hostHelper+';globalThis.appUrlHost=appUrlHost',fallbackHost);
assert.equal(new URL('http://'+fallbackHost.appUrlHost()+':8080').href,'http://[2001:db8::1]:8080/');
assert.equal(ui.webLink({...web,state:'exited'},'nas.local'),'');
assert.equal(ui.webLink({...web,ports:{'8384/tcp':[{HostPort:'8384',HostIp:'127.0.0.1'}]}},'nas.local'),'');
assert.equal(ui.webLink({...web,web_port:null},'nas.local'),'');
