'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const recipe={id:'s01-cloud',name:'Meine Cloud',docker_template:true,containers:1,port:80,default_port:8080,install_schema:[]};
const details={app:{state:'exited',port:8081,network:{mode:'bridge',name:'lan',ipv4_address:'172.30.0.2'}},services:[{state:'exited'}],settings:[{key:'name',label:'Name',type:'text',value:'Nutzer <script>',editable:true},{key:'peer',label:'Zusatzport',type:'number',optional:true,value:null,default:8888},{key:'media',label:'Medien',type:'boolean',optional:true,value:true},{key:'password',label:'Private',type:'password',value:'DO-NOT-SHOW'},{key:'generated',label:'Intern',type:'text',value:'INTERNAL',editable:false}]};
const root={};let body,rendered,submit,mountedNetwork,calls=[];
const sandbox={window:root,URLSearchParams,FormData:class {constructor(form){this.map=new Map(form?.values||[]);}get(key){return this.map.get(key)??null;}}};
vm.runInNewContext(fs.readFileSync('titan/web/template_fields.js','utf8'),sandbox);
root.TitanNetworks={installFields:()=>'<div data-network-install></div>',installArguments:(app,data)=>data.get('network_mode')==='bridge'?{network:{mode:'bridge'}}:{},mountInstall:(node,app)=>{mountedNetwork=app.default_network;}};
vm.runInNewContext(fs.readFileSync('titan/web/docker_editor.js','utf8'),sandbox);
const ui=root.TitanDockerEditor;
function context(){const handlers=new Map(),input={value:''};body={querySelector:selector=>selector==='form'?{values:[['port','8081']]}:selector==='[data-network-ip]'?input:null,addEventListener:(event,handler)=>handlers.set(event,handler),removeEventListener:(event,handler)=>{if(handlers.get(event)===handler)handlers.delete(event);}};return {api:async path=>path.startsWith('/api/app-details?')?details:{networks:[]},catalogApp:async()=>recipe,dialog:(title,html,handler)=>{rendered=html;submit=handler;},dialogBody:()=>body,action:async(operation,args,options)=>{calls.push({operation,args,options});return {ok:true,message:'Gespeichert'};},toast(){},input,handlers};}
(async()=>{
 const ctx=context();await ui.template(recipe.id,ctx);assert(rendered.includes('Nutzer &lt;script&gt;'));assert(!rendered.includes('DO-NOT-SHOW'));assert(!rendered.includes('INTERNAL'));assert.match(rendered,/name="option-peer"[^>]*disabled/);assert.match(rendered,/name="enable-media" checked/);assert.equal(mountedNetwork,'network:lan');assert.equal(ctx.input.value,'172.30.0.2');
 const data=new FormData();data.set('port','8090');data.set('option-name','Freunde');data.set('enable-media','on');data.set('network_mode','default');await submit(data);assert.equal(calls[0].operation,'app_settings');assert.equal(calls[0].options.wait,true);assert.equal(calls[0].args.port,8090);assert.equal(calls[0].args.network.mode,'default','Switching back to Standard explicitly replaces the previous custom network');assert.equal(calls[0].args.options.media,true);assert(!Object.hasOwn(calls[0].args.options,'password'));assert(!Object.hasOwn(calls[0].args.options,'peer'));
 details.services[0].state='running';rendered=null;await assert.rejects(ui.template(recipe.id,context()),/Alle Dienste/);assert.equal(rendered,null);details.services[0].state='exited';
 const options=ui.editableRecipe(recipe,[{key:'flag',type:'boolean',value:false,editable:true,enabled_by_default:true}]);assert.doesNotMatch(root.TitanTemplateFields.fields(options),/checked/,'A saved false boolean stays false');
 const auto=root.TitanTemplateFields.fields({port:80,default_port:8080,install_schema:[{key:'url',label:'APP_URL',type:'text',default:''}]},'2001:db8::1');assert.match(auto,/http:\/\/\[2001:db8::1\]:8080/);assert.match(auto,/data-template-auto-url/);
 const mapping=root.TitanTemplateFields.mappings({port:80,port_bindings:[{target:80,published:8080,protocol:'tcp'},{target:6881,published:6881,protocol:'udp',option:'peer',optional:true}],install_schema:[{key:'peer',type:'number',optional:true}]},data);assert(mapping.includes('8090 → 80/tcp'));assert(mapping.includes('nicht aktiviert'));
 console.log('Docker editors: real template settings form, safe public fields, optional values, active-service rejection, saved defaults, explicit network reset and live port summary passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
