'use strict';
const assert=require('node:assert/strict');
const ui=require('../titan/web/file_places.js');
const storage={data:new Map(),getItem(k){return this.data.get(k)||null;},setItem(k,v){this.data.set(k,v);}};
global.localStorage=storage;
ui.toggle('alice',{share:'docs',path:'',label:'Dokumente'});
assert.equal(ui.load('alice')[0].path,'');
assert.equal(ui.load('bob').length,0);
assert(ui.render({owner:'alice',shares:[{name:'docs'}]}).includes('Dokumente'));
assert(!ui.render({owner:'alice',shares:[{name:'docs',blocked:true}]}).includes('Dokumente'));
assert(!ui.render({owner:'alice',shares:[]}).includes('Dokumente'));
for(const path of ['/etc','a/../b','a\0b'])assert.equal(ui.valid({share:'docs',path}),false);
assert.deepEqual(ui.load('alice',{getItem(){throw Error('blocked');}}),[]);
let click;const attrs={};const favorite={setAttribute(k,v){attrs[k]=v;},addEventListener(name,fn){click=fn;}};
const area={outerHTML:''};const browser={querySelector(selector){return selector==='[data-fb-favorite]'?favorite:area;}};
const ctx={owner:'alice',share:'docs',path:'Fotos',shares:[{name:'docs'}]};
const cleanup=ui.mount(browser,ctx);
assert(area.outerHTML.includes('Dokumente'));
click();assert.equal(attrs['aria-pressed'],'true');assert(area.outerHTML.includes('Fotos'));
assert.equal(ui.load('alice').length,2);
click();assert.equal(attrs['aria-pressed'],'false');assert.equal(ui.load('alice').length,1);
ui.toggle('alice',{share:'@system',path:'etc',label:'Old System'});ui.toggle('alice',{share:'@system',path:'var/srv/titan/Fotos',label:'NAS Fotos'});const safe=ui.render({owner:'alice',shares:[{name:'@system'}],storage:[{path:'/var/srv/titan',available:true}]});assert(!safe.includes('Old System'));assert(safe.includes('NAS Fotos'));assert(ui.load('alice').some(item=>item.label==='Old System'),'Unavailable legacy favorites are hidden, not erased');cleanup();delete global.localStorage;
console.log('File places: per-user favorites, root folders, live accessible shares and mount persistence passed');
