'use strict';
const assert=require('node:assert/strict');
const picker=require('../titan/web/file_folder_picker.js');
class Node{
 constructor(attrs={}){this.attributes={...attrs};this.dataset={};for(const[key,value]of Object.entries(attrs))if(key.startsWith('data-'))this.dataset[key.slice(5).replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase())]=value;this.children=[];this.listeners=new Map();this.value=attrs.value||'';this.innerHTML='';this.textContent='';}
 append(...nodes){nodes.forEach(node=>{node.parentElement=this;node.ownerDocument=this.ownerDocument;this.children.push(node);});}
 matches(selector){const matches=[...selector.matchAll(/\[([^=\]]+)(?:="([^"]*)")?\]/g)];return matches.length?matches.every(([,name,value])=>name in this.attributes&&(value===undefined||this.attributes[name]===value)):selector==='form'&&this.attributes.tag==='form';}
 querySelector(selector){for(const child of this.children){if(child.matches(selector))return child;const found=child.querySelector(selector);if(found)return found;}return null;}
 closest(selector){return this.matches(selector)?this:this.parentElement?.closest(selector)||null;}
 contains(node){return node===this||this.children.some(child=>child.contains(node));}
 addEventListener(type,fn,options={}){const list=this.listeners.get(type)||new Set();list.add(fn);this.listeners.set(type,list);options.signal?.addEventListener('abort',()=>{list.delete(fn);if(!list.size)this.listeners.delete(type);},{once:true});}
 dispatch(type,options={}){const event={type,target:this,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},stopImmediatePropagation(){this.stopped=true;},...options};for(const listener of [...(this.listeners.get(type)||[])]){listener(event);if(event.stopped)break;}return event;}
}
function fixture(api,options={}){
 const scope=new Node(),form=new Node({tag:'form'});scope.ownerDocument={};scope.append(form);const share=new Node({name:'destination_share',value:options.share||'destination'}),name=new Node({name:'destination_name',value:'Bericht-Kopie.txt'}),node=new Node({'data-folder-picker':'','data-path-field':'destination','data-share-field':'destination_share','data-leaf-field':options.leafField?'destination_name':'','data-initial-path':'archive'}),hidden=new Node({name:'destination'});form.append(share,name,node);node.append(hidden);
 const children={};for(const label of ['status','list','breadcrumbs','current','pages','storage','storage-field']){children[label]=new Node({['data-folder-picker-'+label]:''});node.append(children[label]);}
 const instance=picker.mount(scope,{api,initialPath:'archive',...options});return{scope,form,share,name,node,hidden,children,instance,turn:()=>new Promise(resolve=>setImmediate(resolve)),submit:()=>scope.dispatch('submit',{target:form})};
}
(async()=>{
 assert.equal(picker.normalize('archive//2026/'),'archive/2026');assert.equal(picker.normalize(''),'');assert.throws(()=>picker.normalize('/etc'));assert.throws(()=>picker.normalize('../escape'));assert.throws(()=>picker.leaf('../bad'));assert.throws(()=>picker.leaf(''));assert.equal(picker.leaf('<&>.txt'),'<&>.txt');
 const rendered=picker.render({initialPath:'folder/<name>',leafField:'destination_name'});assert.match(rendered,/type="hidden" name="destination"/);assert.match(rendered,/folder\/&lt;name&gt;/);assert(!rendered.includes('type="text"'));assert.throws(()=>picker.render({initialPath:'../escape'}));
 const requests=[],f=fixture(async url=>{requests.push(url);return{entries:[{name:'2026',directory:true},{name:'<images>',directory:true},{name:'link',directory:true,symlink:true},{name:'file.txt',directory:false},{name:'../evil',directory:true}],has_more:true};});await f.turn();assert(f.instance.valid());assert.equal(f.hidden.value,'archive');assert.match(f.children.list.innerHTML,/archive\/2026/);assert.match(f.children.list.innerHTML,/&lt;images&gt;/);assert(!f.children.list.innerHTML.includes('../evil'));assert(!f.children.list.innerHTML.includes('link'));assert(!f.children.list.innerHTML.includes('file.txt'));assert.match(f.children.pages.innerHTML,/data-folder-picker-offset="200"/);
 await f.instance.load('archive/2026');assert.equal(f.hidden.value,'archive/2026');assert.match(requests.at(-1),/path=archive%2F2026/);assert(!f.submit().defaultPrevented);f.share.value='other';f.share.dispatch('change');await f.turn();assert.equal(f.hidden.value,'');assert.match(requests.at(-1),/share=other&path=&offset=0/);
 await f.instance.load('archive',200);assert.match(requests.at(-1),/offset=200/);assert.match(f.children.pages.innerHTML,/data-folder-picker-offset="0"/);await f.instance.load('../escape');assert(!f.instance.valid());assert.match(f.children.status.textContent,/relativer Zielordner/);assert(f.submit().defaultPrevented);
 const single=fixture(async()=>({entries:[],has_more:false}),{leafField:'destination_name'});await single.turn();assert.equal(single.hidden.value,'archive/Bericht-Kopie.txt');single.name.value='Neu.json';single.name.dispatch('input');assert.equal(single.hidden.value,'archive/Neu.json');single.name.value='../danger';assert(single.submit().defaultPrevented);assert.equal(single.hidden.value,'');assert.match(single.children.status.textContent,/Zielname/);
 // A loading/unavailable destination cannot trigger the original mutation.
 let finish;const waiting=fixture(()=>new Promise(resolve=>finish=resolve));assert(waiting.submit().defaultPrevented);finish({entries:[]});await waiting.turn();assert(waiting.instance.valid());const failed=fixture(async()=>{throw new Error('Freigabe nicht eingehängt');});await failed.turn();assert(!failed.instance.valid());assert(failed.submit().defaultPrevented);assert(!failed.children.list.innerHTML);
 // Slow results for the previous share cannot replace a newer destination.
 let oldReply;const race=fixture(url=>url.includes('share=destination')?new Promise(resolve=>oldReply=resolve):Promise.resolve({entries:[{name:'new',directory:true}]}));race.share.value='other';race.share.dispatch('change');await race.turn();oldReply({entries:[{name:'old',directory:true}]});await race.turn();assert.match(race.children.list.innerHTML,/>new<\/span>/);assert(!race.children.list.innerHTML.includes('>old</span>'));
 // System paths use the canonical relative path returned by the API.
 const system=fixture(async url=>url==='/api/storage-locations'?{default_storage:'system',storage:[{id:'system',label:'Interner Speicher',path:'/var/srv/titan',available:true,capabilities:['files']}]}:{entries:[],path:'var/srv/titan/documents'});system.share.value='@system';system.share.dispatch('change');await system.turn();assert.equal(system.hidden.value,'var/srv/titan/documents');assert.equal(system.children.current.textContent,'Interner Speicher / documents');assert(!system.children.breadcrumbs.innerHTML.includes('data-folder-picker-path=""'));await system.instance.load('etc');assert.equal(system.hidden.value,'var/srv/titan/documents');
 for(const state of ['offline','full','missing']){
  const internal={id:'system',label:'Interner Speicher',path:'/var/srv/titan',available:true,capabilities:['files']},target={id:'volume:chosen',label:'Gewähltes Laufwerk',path:'/srv/chosen',available:state!=='offline',status:state,capabilities:['files']},catalog={default_storage:target.id,storage:state==='missing'?[internal]:[internal,target]},calls=[];
  const unavailable=fixture(async url=>{calls.push(url);return url==='/api/storage-locations'?catalog:{entries:[],path:new URL(url,'http://fixture').searchParams.get('path')};},{share:'@system',initialPath:''});await unavailable.turn();
  assert.equal(unavailable.children.storage.value,target.id);assert.match(unavailable.children.storage.innerHTML,/value="volume:chosen" selected disabled/);assert(!unavailable.children.storage.innerHTML.includes('value="system" selected'));assert.equal(unavailable.instance.valid(),false);assert.match(unavailable.children.status.textContent,/Wähle ausdrücklich einen anderen Zielbereich/);assert(!calls.some(url=>url.startsWith('/api/files')));assert(unavailable.submit().defaultPrevented);
  unavailable.children.storage.value='system';unavailable.children.storage.dispatch('change');await unavailable.turn();assert(unavailable.instance.valid());assert.equal(unavailable.hidden.value,'var/srv/titan');assert(!unavailable.submit().defaultPrevented);picker.disposeWithin(unavailable.scope);
 }
 assert([...requests].every(url=>url.startsWith('/api/files?')));picker.disposeWithin(system.scope);assert.equal(system.scope.listeners.size,0);assert.equal(system.node.listeners.size,0);assert.equal(system.share.listeners.size,0);picker.disposeWithin(race.scope);picker.disposeWithin(f.scope);picker.disposeWithin(single.scope);picker.disposeWithin(waiting.scope);picker.disposeWithin(failed.scope);
 console.log('Folder picker: existing-share browsing, pagination, escaped directory names, target names, no-overwrite handoff, loading/error guards, canonical paths and stale-response/disposal checks passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
