'use strict';
const assert=require('node:assert/strict');
const explorer=require('../titan/web/file_browser.js');
const selection=require('../titan/web/files_controls.js');
class Event{constructor(type,options={}){this.type=type;this.bubbles=options.bubbles;this.defaultPrevented=false;}preventDefault(){this.defaultPrevented=true;}stopPropagation(){this.stopped=true;}}
const camel=value=>value.replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase());
function textResponse(text,headers={}){const data=Buffer.from(text);return{ok:true,status:200,headers:{get:name=>headers[name]??null},arrayBuffer:async()=>data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength)};}
class Element{
 constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attributes={...attrs};this.dataset={};this.children=[];this.events=new Map();this.value=attrs.value||'';this.hidden=false;this.disabled=false;this.checked=false;this.textContent='';this._html='';this.classes=new Set((attrs.class||'').split(' ').filter(Boolean));this.classList={toggle:(name,on)=>on?this.classes.add(name):this.classes.delete(name)};for(const [key,value]of Object.entries(attrs))if(key.startsWith('data-'))this.dataset[camel(key.slice(5))]=value;}
 append(...nodes){for(const node of nodes){if(node.parentElement)node.parentElement.children=node.parentElement.children.filter(item=>item!==node);node.parentElement=this;const adopt=n=>{n.ownerDocument=this.ownerDocument;n.children.forEach(adopt);};adopt(node);this.children.push(node);}}
 matches(selector){if(selector.includes(','))return selector.split(',').some(value=>this.matches(value.trim()));if(selector.startsWith('.'))return this.classes.has(selector.slice(1));if(selector.startsWith('#'))return this.attributes.id===selector.slice(1);const tag=selector.match(/^[a-z]+/i)?.[0];if(tag&&this.tagName!==tag.toUpperCase())return false;const attrs=[...selector.matchAll(/\[([^=\]]+)(?:="([^"]*)")?\]/g)];if(attrs.length)return attrs.every(([,name,value])=>name==='hidden'?this.hidden:name in this.attributes&&(value===undefined||this.attributes[name]===value));return Boolean(tag);}
 querySelectorAll(selector){return this.children.flatMap(node=>[...(node.matches(selector)?[node]:[]),...node.querySelectorAll(selector)]);}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 closest(selector){return this.matches(selector)?this:this.parentElement?.closest(selector)||null;}
 contains(node){return node===this||this.children.some(child=>child.contains(node));}
 setAttribute(name,value){this.attributes[name]=value;}
 getAttribute(name){return this.attributes[name]??null;}
 get innerHTML(){return this._html;}
 set innerHTML(value){this._html=value;if(this.classes.has('fb-inspector')){const node=new Element('div',{'data-fb-preview':''});this.children=[];this.append(node);}}
 focus(){this.ownerDocument.activeElement=this;}
 addEventListener(type,listener,options={}){const set=this.events.get(type)||new Set();set.add(listener);this.events.set(type,set);options.signal?.addEventListener('abort',()=>this.removeEventListener(type,listener),{once:true});}
 removeEventListener(type,listener){const set=this.events.get(type);set?.delete(listener);if(!set?.size)this.events.delete(type);}
 dispatchEvent(event){if(!event.target)event.target=this;for(const listener of [...(this.events.get(event.type)||[])])listener(event);if(event.bubbles&&!event.stopped)this.parentElement?.dispatchEvent(event);return !event.defaultPrevented;}
 dispatch(type,details={}){const event=Object.assign(new Event(type,{bubbles:true}),details);this.dispatchEvent(event);return event;}
}
function fixture(entries,extra={}){
 const doc=new Element('document');doc.ownerDocument=doc;doc.defaultView={Event,getSelection:()=>({toString:()=>''})};const main=new Element('main'),browser=new Element('section',{'data-file-browser':''}),tbody=new Element('tbody'),inspector=new Element('aside',{class:'fb-inspector'});doc.append(main);main.append(browser);browser.append(tbody,inspector);
 const count=new Element('span',{'data-file-selection-count':''}),bar=new Element('div',{'data-file-selection-bar':''}),all=new Element('input',{'data-file-select-all':''}),search=new Element('input',{id:'fb-search'}),sort=new Element('select',{'data-fb-sort':''});browser.append(count,bar,all,search,sort);
 const batch=new Element('button',{'data-file-batch':'clear'});bar.append(batch);
 const rows=entries.map((entry,index)=>{const row=new Element('tr',{'data-fb-index':String(index),class:'fb-entry'}),cell=new Element('td'),name=new Element('span');cell.append(name);row.append(cell);if(entry.readable!==false&&!entry.symlink&&entry.mutable!==false){const box=new Element('input',{'data-file-select':'',value:String(index)});row.append(box);}const button=new Element('button',{'data-fb-open':String(index)});row.append(button);if(explorer.canEdit(entry,{writable:true,share:extra.share||'source',...extra}))row.append(new Element('button',{'data-fb-edit':String(index)}));tbody.append(row);return row;});
 const views=['list','grid'].map(value=>new Element('button',{'data-fb-view':value}));browser.append(...views);const place=new Element('button',{'data-fb-share':'destination','data-fb-path':'archive'});browser.append(place);
 const actions=[],locations=[],dialogs=[],requests=[];const ctx={entries,share:'source',path:'folder',writable:true,admin:true,targets:[{name:'source',label:'Quelle'}],actions:Object.fromEntries(['folder-open','file-preview','file-edit','file-up','file-rename','file-delete'].map(action=>[action,target=>actions.push({action,...target.dataset})])),toast(){},dialog:(title,html)=>dialogs.push({title,html}),openLocation:(share,path)=>locations.push({share,path}),fileUrl:(path,preview)=>'/api/file?'+new URLSearchParams({share:'source',path,preview:String(Boolean(preview))}),fetch:async(url,options)=>{requests.push({url,options});return textResponse('<script>unsafe()</script> & bounded');},...extra};
 selection.mount(main,ctx);const instance=explorer.mount(main,ctx);return{doc,main,browser,rows,tbody,inspector,count,all,search,sort,views,place,ctx,actions,locations,dialogs,requests,instance,key:(key,more={})=>doc.dispatch('keydown',{target:doc.activeElement||main,key,...more}),click:index=>rows[index].children[0].dispatch('click'),turn:()=>new Promise(resolve=>setImmediate(resolve))};
}
const entry=(name,extra={})=>({name,directory:false,readable:true,mutable:true,size:30,modified:1234567890,...extra});
(async()=>{
 const entries=[entry('z.txt'),entry('Archive',{directory:true}),entry('Foto.png'),entry('locked',{mutable:false,readable:false})];
 const html=explorer.render({share:'source',path:'folder',writable:true,admin:false,shares:[{name:'source',label:'Quelle'}],targets:[{name:'source'}],entries,data:{total:4,offset:0,limit:200},search:'<script>',breadcrumbs:'<nav>Pfad</nav>'});
 assert.match(html,/data-file-browser/);assert.match(html,/id="share-select"/);assert.match(html,/id="file-search-form"/);assert.match(html,/id="file-upload"/);assert.match(html,/data-file-select value="0"/);assert(!html.includes('Systemordner'));assert(!html.includes('Systempfad'));assert(!html.includes('value="<script>"'));assert.match(html,/&lt;script&gt;/);assert(!html.includes('class="file-row"'));
 const admin=explorer.render({share:'@system',path:'var/srv/titan',storage:[{id:'system',label:'Interner Speicher',path:'/var/srv/titan',available:true,free_bytes:1024},{id:'volume:offline',label:'Archive',path:'/srv/archive',available:false}],storageRoot:{id:'system',label:'Interner Speicher',path:'/var/srv/titan'},writable:true,admin:true,shares:[{name:'@system',label:'System /'}],targets:[],entries:[entry('<bad>.txt',{mutable:false})],data:{total:1}});assert.match(admin,/Speicherbereiche/);assert(!admin.includes('System /'));assert(!admin.includes('data-fb-path="etc"'));assert(!admin.includes('data-fb-path="home"'));assert(admin.includes('value="@storage:volume:offline"  disabled'));assert(admin.includes('data-action="file-up" aria-label="Übergeordneten Ordner öffnen" disabled'));assert.match(admin,/id="system-path-form"/);assert.match(admin,/&lt;bad&gt;\.txt/);assert(!admin.includes('data-file-select value="0"'));assert(!admin.includes('data-action="trash-view"'));
 assert.deepEqual(explorer.sortedIndices(entries,'name'),[1,2,3,0]);assert.deepEqual(explorer.sortedIndices([entry('b',{size:1}),entry('a',{size:8}),entry('folder',{directory:true,size:0})],'size'),[2,1,0]);assert.equal(explorer.kind(entry('movie.mp4')),'media');assert.equal(explorer.type(entry('link',{symlink:true})),'Symbolischer Link');
 const f=fixture(entries);assert.deepEqual(f.tbody.children.map(row=>Number(row.dataset.fbIndex)),[1,2,3,0]);
 f.click(0);await f.turn();assert(f.rows[0].querySelector('[data-file-select]').checked);assert.equal(f.count.textContent,'1 ausgewählt');assert.match(f.inspector.innerHTML,/z\.txt/);assert.match(f.inspector.querySelector('[data-fb-preview]').innerHTML,/&lt;script&gt;unsafe/);assert.equal(f.requests[0].options.headers.Range,'bytes=0-8191');assert.equal(f.actions.length,0);
 f.rows[2].children[0].dispatch('click',{ctrlKey:true});await f.turn();assert.equal(f.count.textContent,'2 ausgewählt');assert.match(f.inspector.querySelector('[data-fb-preview]').innerHTML,/<img src="\/api\/file\?/);assert(f.rows[0].classes.has('selected'));assert(f.rows[2].classes.has('selected'));
 f.key('a',{ctrlKey:true});assert.equal(f.count.textContent,'3 ausgewählt');assert(f.rows[1].classes.has('selected'));f.key('Escape');assert.equal(f.count.textContent,'0 ausgewählt');assert(!f.rows[0].classes.has('selected'));
 f.instance.select(1);f.key('Enter');assert.deepEqual(f.actions.at(-1),{action:'folder-open',path:'folder/Archive',index:'1',share:'source'});f.key('ArrowDown');await f.turn();assert.equal(f.doc.activeElement,f.rows[2]);f.key('Enter');assert.equal(f.actions.at(-1).action,'file-preview');assert.equal(f.actions.at(-1).path,'folder/Foto.png');
 f.key('Home');assert.equal(f.doc.activeElement,f.rows[1]);f.key('End');assert.equal(f.doc.activeElement,f.rows[0]);f.key('ArrowUp');assert.equal(f.doc.activeElement,f.rows[3]);f.key('Enter');assert(!f.actions.some(item=>item.path==='folder/locked'));
 f.key('f',{ctrlKey:true});assert.equal(f.doc.activeElement,f.search);const countBefore=f.actions.length;assert(!f.key('Enter').defaultPrevented);assert.equal(f.actions.length,countBefore);f.doc.activeElement=f.main;f.key('ArrowUp',{altKey:true});assert.equal(f.actions.at(-1).action,'file-up');
 f.place.dispatch('click');assert.deepEqual(f.locations.at(-1),{share:'destination',path:'archive'});f.views[1].dispatch('click');assert.equal(f.browser.dataset.view,'grid');assert.equal(f.views[1].attributes['aria-pressed'],'true');f.views[0].dispatch('click');assert.equal(f.browser.dataset.view,'list');
 explorer.render({share:'source',path:'A',shares:[],entries:[]});explorer.render({share:'source',path:'B',shares:[],entries:[]});f.instance.moveHistory(-1);assert.deepEqual(f.locations.at(-1),{share:'source',path:'A'});explorer.render({share:'source',path:'A',shares:[],entries:[]});f.instance.moveHistory(1);assert.deepEqual(f.locations.at(-1),{share:'source',path:'B'});explorer.render({share:'source',path:'B',shares:[],entries:[]});
 const otherAccount=explorer.render({owner:'other-user',share:'source',path:'',shares:[],entries:[]});assert.match(otherAccount,/data-fb-history="-1" aria-label="Vorheriger Ordner" disabled/);
 f.sort.value='name-desc';f.sort.dispatch('change');assert.deepEqual(f.tbody.children.map(row=>Number(row.dataset.fbIndex)),[1,0,3,2]);f.rows[0].children[0].dispatch('dblclick');assert.equal(f.actions.at(-1).path,'folder/z.txt');const beforeMenu=f.actions.length;f.rows[0].dispatch('contextmenu');assert.equal(f.actions.length,beforeMenu);assert.match(f.dialogs.at(-1).html,/data-action="file-rename"/);assert.match(f.dialogs.at(-1).html,/data-action="file-delete"/);
 // Existing system deletion still uses its exact-path confirmation action.
 const sys=fixture([entry('allowed'),entry('blocked',{mutable:false})],{share:'@system'});sys.instance.select(0);sys.key('F2');assert.equal(sys.actions.at(-1).action,'file-rename');sys.key('Delete');assert.equal(sys.actions.at(-1).action,'file-delete');assert.equal(sys.actions.at(-1).path,'folder/allowed');sys.instance.select(1);sys.rows[1].dispatch('contextmenu');assert(!sys.dialogs.at(-1).html.includes('file-delete'));assert(!sys.dialogs.at(-1).html.includes('file-edit'));
 const notices=[],missing=fixture([],{api:async()=>{throw new Error('Ordner nicht vorhanden');},toast:message=>notices.push(message)});missing.place.dispatch('click');await missing.turn();assert.equal(missing.locations.length,0);assert.equal(notices[0],'Ordner nicht vorhanden');
 // A slow previous preview must not overwrite the latest selection.
 let release;const race=fixture([entry('first.txt'),entry('second.png')],{fetch:async()=>({ok:true,arrayBuffer:()=>new Promise(resolve=>release=resolve)})});race.instance.select(0);await race.turn();race.instance.select(1);release(Buffer.from('stale previous file'));await race.turn();assert.match(race.inspector.querySelector('[data-fb-preview]').innerHTML,/<img/);assert(!race.inspector.innerHTML.includes('stale previous file'));
 // Editing is offered directly for any suffix and extensionless text, with server permissions respected.
 const arbitrary=[entry('settings.registry'),entry('.custom'),entry('no-extension'),entry('text.png'),entry('locked.cfg',{editable:false}),entry('large.custom',{size:1048577}),entry('folder',{directory:true}),entry('share-link',{symlink:true,editable:true})];
 const arbitraryHtml=explorer.render({share:'source',path:'config',writable:true,shares:[],entries:arbitrary});
 for(const index of [0,1,2,3])assert(arbitraryHtml.includes(`data-fb-edit="${index}"`));
 for(const index of [4,5,6,7])assert(!arbitraryHtml.includes(`data-fb-edit="${index}"`));
 assert(arbitraryHtml.includes('F4: bearbeiten'));assert(arbitraryHtml.includes('settings.registry bearbeiten'));
 const edit=fixture(arbitrary);edit.rows[0].querySelector('[data-fb-edit]').dispatch('click');assert.deepEqual(edit.actions.at(-1),{action:'file-edit',share:'source',path:'folder/settings.registry',index:'0'});
 edit.instance.select(0);await edit.turn();assert.match(edit.inspector.querySelector('[data-fb-preview]').innerHTML,/&lt;script&gt;unsafe/);assert.equal(edit.requests.at(-1).options.headers.Range,'bytes=0-8191');assert.match(edit.inspector.innerHTML,/jede Dateiendung/);
 const editCount=edit.actions.length;edit.key('F4');assert.equal(edit.actions.length,editCount+1);assert.equal(edit.actions.at(-1).action,'file-edit');
 edit.instance.select(4);assert(!edit.key('F4').defaultPrevented);assert.equal(edit.actions.length,editCount+1);assert(!edit.inspector.innerHTML.includes('data-action="file-edit"'));
 edit.instance.select(5);assert.match(edit.inspector.innerHTML,/zu groß/);assert(!edit.key('F4').defaultPrevented);assert.equal(edit.actions.length,editCount+1);
 const readOnly=fixture([entry('custom.suffix')],{writable:false});readOnly.instance.select(0);assert(!readOnly.inspector.innerHTML.includes('data-action="file-edit"'));assert(!readOnly.rows[0].querySelector('[data-fb-edit]'));assert(!readOnly.key('F4').defaultPrevented);
 const symlinkEdit=fixture([entry('target-link',{symlink:true,mutable:false,editable:true})],{share:'@system'});symlinkEdit.instance.select(0);assert.match(symlinkEdit.inspector.innerHTML,/data-action="file-edit"/);symlinkEdit.key('F4');assert.equal(symlinkEdit.actions.at(-1).share,'@system');assert.equal(symlinkEdit.actions.at(-1).action,'file-edit');
 // Text decoding is based on bytes, preserving UTF-8 and rejecting binary/replacement text.
 assert.deepEqual(await explorer.readTextPreview(textResponse('Grüße 🐧 <unsafe>')),{text:'Grüße 🐧 <unsafe>',truncated:false});
 assert.deepEqual(await explorer.readTextPreview({ok:false,status:416}),{text:'',truncated:false});
 await assert.rejects(explorer.readTextPreview(textResponse(Buffer.from([0xff,0xfe,0x61]))),/UTF-8/);
 await assert.rejects(explorer.readTextPreview(textResponse(Buffer.from('zip\0binary'))),/Binärdatei/);
 await assert.rejects(explorer.readTextPreview({ok:false,status:403}),/nicht verfügbar/);
 // A valid multibyte character split by the preview boundary does not turn a text file into a binary error.
 const boundary=Buffer.concat([Buffer.from('a'.repeat(8191)),Buffer.from('€ suffix')]);
 const limited=await explorer.readTextPreview(textResponse(boundary,{'Content-Range':'bytes 0-8191/8200'}));assert.equal(limited.text,'a'.repeat(8191));assert.equal(limited.truncated,true);
 let reads=0,cancelled=false,released=false;const streamed=await explorer.readTextPreview({ok:true,status:200,headers:{get:()=>null},body:{getReader:()=>({read:async()=>{reads++;return {done:false,value:Buffer.from('b'.repeat(9000))};},cancel:async()=>{cancelled=true;},releaseLock:()=>{released=true;}})}});assert.equal(reads,1);assert(cancelled&&released);assert.equal(streamed.text.length,8192);assert(streamed.truncated);
 // Dialogs retain their own keyboard handling; disposal cancels listeners/fetch.
 const modal=new Element('dialog',{open:''});symlinkEdit.doc.append(modal);assert(!symlinkEdit.key('ArrowDown').defaultPrevented);modal.attributes={};const eventCount=symlinkEdit.doc.events.size;assert(eventCount>0);explorer.dispose();selection.dispose();assert.equal(symlinkEdit.doc.events.size,0);assert.equal(symlinkEdit.browser.events.size,0);
 console.log('Explorer render, direct extension-independent editing, permissions, UTF-8/binary detection, bounded streaming, sidebar, sorting, list/grid, selection, keyboard, context, stale-response and disposal checks passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
