'use strict';
const assert=require('node:assert/strict'),types=require('../titan/web/file_types.js'),artwork=require('../titan/web/app_artwork.js'),desktop=require('../titan/web/desktop_shortcuts.js');
for(const extension of ['docx','xlsx','odt','ods']){const selected=types.filename('Dokument',extension);assert.equal(selected.name,'Dokument.'+extension);assert.equal(selected.document,true);assert.equal(types.filename('Dokument.'+extension.toUpperCase(),extension).name,'Dokument.'+extension.toUpperCase());}
assert.deepEqual(types.filename('Programm','py'),{name:'Programm.py',extension:'py',document:false});assert.equal(types.filename('Datei','custom','docx').document,true);assert.equal(types.filename('README','').name,'README');
for(const name of ['', '.', '..', '../escape', 'a/b','a\\b','bad\0name','🐧'.repeat(70)])assert.throws(()=>types.filename(name,'txt'));
for(const ext of ['../bad','<script>','a/b','a'.repeat(33)])assert.throws(()=>types.filename('file','custom',ext));
assert.equal(types.info('docx').symbol,'W');assert.equal(types.info('xlsx').symbol,'X');assert.equal(types.info('xls').category,'sheet');assert.equal(types.info('doc').category,'word');assert.equal(types.info('pptx').category,'slide');assert.equal(types.info('py').label,'Python');
assert(!types.icon('<img src=x onerror=alert(1)>').includes('<img'));assert.match(types.fields(),/Word-Dokument/);assert.match(types.fields(),/Excel-Tabelle/);
assert.equal(artwork.source('titan-nextcloud-office'),'/app-icons/nextcloud.svg');assert.equal(artwork.source('titan-immich'),'/app-icons/immich.svg');assert.equal(artwork.source('__proto__'),'/app-icons/container.svg');assert.equal(artwork.tool('bad/path'),'');assert.match(artwork.tool('docker'),/titan-docker.svg/);
const allowed=['tool:files','tool:docker','tool:apps'];assert(desktop.normalize({},allowed).items.includes('tool:docker'));assert(desktop.normalize({version:2,items:['tool:files']},allowed).items.includes('tool:docker'));assert(!desktop.normalize({version:2,docker_added:true,items:['tool:files']},allowed).items.includes('tool:docker'),'A deliberately removed Docker shortcut stays removed');assert.deepEqual(desktop.normalize({version:2,items:[]},allowed).items,[]);assert.equal(desktop.normalize({icon_size:'javascript:x'},allowed).icon_size,'medium');
console.log('File creation types, valid Office routing, understandable symbols, path/UTF-8 bounds, icon aliases and Docker desktop migration verified.');
