'use strict';
const assert=require('node:assert/strict'),ui=require('../titan/web/desktop_shortcuts.js');
const allowed=['tool:files','tool:settings','tool:apps','tool:storage','tool:vms'];
assert.equal(ui.normalize({},allowed).items.length,4);
assert.deepEqual(ui.normalize({version:2,items:[]},allowed).items,[],'An intentionally empty desktop remains empty');
const legacy=ui.normalize({items:['tool:files','tool:files','javascript:x','tool:root','app:demo'],hidden:['tool:files']},allowed);
assert.deepEqual(legacy.items,['app:demo']);
const grouped=ui.group(['tool:files','tool:vms'],'tool:files','tool:vms');assert.equal(grouped.length,1);assert.deepEqual(grouped[0].items,['tool:vms','tool:files']);
assert.deepEqual(ui.remove(grouped,'tool:files')[0].items,['tool:vms']);assert.equal(grouped[0].items.length,2,'Removing a shortcut must not mutate previous state');
const arranged=ui.place(['a','b','c'],{a:{x:20,y:30},b:{x:20,y:30}},2,2);assert.equal(new Set(Object.values(arranged).map(p=>p.x+','+p.y)).size,3);assert(Object.values(arranged).every(p=>p.x<2));
assert.equal(ui.safeUrl('javascript:alert(1)'), '');assert.equal(ui.safeUrl('https://user:pass@nas/'),'');assert.equal(ui.safeUrl('http://nas:8096'),'http://nas:8096/');
const reloaded=ui.normalize({version:2,items:grouped,positions:{[grouped[0].id]:{x:4,y:2}},widgets:{visible:false,collapsed:true,items:['ram']}},allowed);assert.equal(reloaded.positions[grouped[0].id].x,4);assert.equal(reloaded.widgets.visible,false);
console.log('Desktop shortcuts: defaults, empty persistence, migration, folders, removal, collision-free mobile placement and safe app URLs passed.');
