'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function node(){const listeners={};return {listeners,value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,open:false,dataset:{},isConnected:true,focus(){this.focused=true;},setAttribute(key,value){this[key]=value;},addEventListener:(type,fn)=>listeners[type]=fn,removeEventListener:(type,fn)=>{if(listeners[type]===fn)delete listeners[type];},insertAdjacentHTML(where,html){this.innerHTML+=html;},get children(){return this.innerHTML.includes('data-location-folder')?[{}]:[];}};}
function widget(purpose,value){const w=node(),children=new Map();w.dataset.purpose=purpose;for(const name of ['root','value','browser','entries','up','current','status','next'])children.set('[data-location-'+name+']',node());children.get('[data-location-value]').value=value;w.querySelector=selector=>children.get(selector);return {w,get:name=>children.get('[data-location-'+name+']')};}
const context={window:{},URLSearchParams,console};vm.createContext(context);vm.runInContext(fs.readFileSync('titan/web/location_controls.js','utf8'),context);const UI=context.window.TitanLocations;
(async()=>{
 assert(UI.field('Ziel <script>','target','/media/<data>',{purpose:'backup',required:true}).includes('&lt;script&gt;'));assert(UI.field('Ziel','target','',{required:true}).includes('data-location-root required'));assert(UI.within('/data/photos','/data'));assert(!UI.within('/database','/data'));assert.equal(UI.clean('/var//media/'),'/var/media');
 const a=widget('backup','/var/media/usb/Archiv'),b=widget('directory',''),widgets=[a.w,b.w],root={querySelectorAll:()=>widgets,contains:element=>widgets.includes(element)},calls=[];
 const items=[{path:'/',label:'System',backup_eligible:false},{path:'/var/media/usb',label:'USB <data>',backup_eligible:true}];let response={entries:[{name:'Fotos <script>',directory:true},{name:'secret',directory:true,readable:false},{name:'link',directory:true,symlink:true},{name:'a.txt',directory:false}],offset:0,limit:200,total:350};
 const ctx={api:async url=>{calls.push(url);return url==='/api/storage-locations'?{items}:response;}};
 await UI.mount(root,ctx);assert.equal(a.get('root').value,'/var/media/usb');assert.equal(a.get('value').value,'/var/media/usb/Archiv');assert(!a.get('root').innerHTML.includes('>System'));assert(a.get('root').innerHTML.includes('&lt;data&gt;'));assert(!b.get('root').innerHTML.includes('>System'));assert(!b.get('root').innerHTML.includes('value="/"'));assert.equal(b.get('value').value,'/var/media/usb');
 a.get('browser').open=true;await a.get('browser').listeners.toggle();assert(calls.at(-1).includes('path=var%2Fmedia%2Fusb%2FArchiv'));assert(a.get('entries').innerHTML.includes('Fotos &lt;script&gt;'));assert(!a.get('entries').innerHTML.includes('secret'));assert(!a.get('entries').innerHTML.includes('link'));assert(!a.get('entries').innerHTML.includes('a.txt'));assert(!a.get('next').hidden);
 await a.get('next').listeners.click();assert(calls.at(-1).includes('offset=200'));
 const folder={dataset:{locationFolder:'Fotos <script>'}};response={entries:[],total:0,limit:200};a.get('entries').listeners.click({target:{closest:()=>folder}});await new Promise(resolve=>setImmediate(resolve));assert.equal(a.get('value').value,'/var/media/usb/Archiv/Fotos <script>');assert(a.get('root').focused);assert.equal(a.get('current')['aria-live'],'polite');assert(a.get('status').textContent.includes('Keine weiteren'));
 a.get('up').listeners.click();await new Promise(resolve=>setImmediate(resolve));assert.equal(a.get('value').value,'/var/media/usb/Archiv');
 a.get('root').value='/var/media/usb';a.get('root').listeners.change();assert.equal(a.get('value').value,'/var/media/usb');assert(a.get('up').disabled);
 let finish;ctx.api=()=>new Promise(resolve=>finish=resolve);const pending=a.get('browser').listeners.toggle();const before=a.get('entries').innerHTML;UI.disposeWithin(root);finish({entries:[{name:'too-late',directory:true}],total:1});await pending;assert.equal(a.get('entries').innerHTML,before);assert(!a.get('root').listeners.change);assert(!b.get('entries').listeners.click);
 const missing=widget('backup','/missing'),emptyRoot={querySelectorAll:()=>[missing.w]};await UI.mount(emptyRoot,{api:async()=>({items:[]})});assert(missing.get('status').textContent.includes('Kein geeignetes externes Laufwerk'));assert.equal(missing.get('root').value,'');
 const catalog={default_storage:'volume:photos',storage:[{id:'system',label:'System',kind:'internal',path:'/var/srv/titan',available:true,free_bytes:10*1024**3,capabilities:['files','apps','shares','vms']},{id:'volume:photos',label:'Fotos <privat>',kind:'volume',path:'/srv/photos',available:true,free_bytes:20*1024**3,capabilities:['files','apps','shares','vms','backups']},{id:'pool:archive',label:'Archiv',kind:'pool',path:'/srv/archive',available:false,status:'offline',free_bytes:0,capabilities:['files','apps','shares','vms','backups']}],items:[{path:'/',label:'System /',backup_eligible:true},{id:'usb',path:'/media/usb',label:'USB',backup_eligible:true}]};
 assert.equal(UI.preferred(catalog,'apps').id,'volume:photos');assert.equal(UI.rootFor(catalog,'/srv/photos/folder').id,'volume:photos');assert.equal(UI.rootFor(catalog,'/srv/photos-other'),undefined);assert.equal(UI.resources(catalog,'files').map(item=>item.id).join(','),'system,volume:photos,pool:archive');assert.equal(UI.resources(catalog,'backup').map(item=>item.path).join(','),'/srv/photos/backups,/srv/archive/backups,/media/usb');assert(!UI.resources(catalog,'backup').some(item=>item.id==='system'));assert.equal(UI.resources(catalog,'backup')[1].available,false);const full={storage:[{id:'volume:full',kind:'volume',path:'/srv/full',available:true,status:'full',free_bytes:0,capabilities:['files','apps','backups'],backup_eligible:false}]};assert.equal(UI.resources(full,'files')[0].available,true);assert.equal(UI.resources(full,'apps')[0].available,false);assert.equal(UI.resources(full,'backup')[0].available,false);
 const choice=UI.selectField('Nutzdaten','storage_id',catalog,'apps');assert(choice.includes('value="volume:photos" selected'));assert(choice.includes('20 GiB frei'));assert(choice.includes('Fotos &lt;privat&gt;'));assert(choice.includes('value="pool:archive"  disabled'));assert(UI.selectField('Nutzdaten','storage_id',catalog,'apps','pool:archive').includes('value="pool:archive" selected disabled'));assert(UI.selectField('Nutzdaten','storage_id',catalog,'apps','volume:missing').includes('Bisheriger Speicher · Nicht verfügbar'));assert.equal(UI.label({label:'Fotos',status:'full',available:false,free_bytes:0}),'Fotos · Voll');assert.equal(UI.label({label:'Archiv',status:'offline',available:false,free_bytes:0}),'Archiv · Nicht verfügbar');
 // A configured destination remains selected when absent/offline/full. The
 // presence of a usable internal disk must never redirect a new allocation.
 for(const [id,extra] of [['pool:archive',{}],['volume:photos',{status:'full',free_bytes:0}],['volume:missing',{}]]){
  const unavailable={...catalog,default_storage:id,storage:catalog.storage.map(item=>item.id===id?{...item,...extra}:item)};
  const selected=UI.preferred(unavailable,'apps');assert.equal(selected.id,id);assert.equal(selected.available,false);
  const html=UI.selectField('Daten','storage_id',unavailable,'apps');assert.match(html,new RegExp('value="'+id+'" selected disabled'));assert(!html.includes('value="system" selected'));
  const pending=widget('apps',''),requests=[],pendingRoot={querySelectorAll:()=>[pending.w],contains:()=>true};await UI.mount(pendingRoot,{api:async url=>{requests.push(url);return unavailable;}});
  assert(pending.get('browser').hidden);assert.equal(pending.get('value').value,'');assert.match(pending.get('status').textContent,/Standardspeicher.*nicht verfügbar/);assert.equal(pending.get('root').value,selected.path||'@missing:'+id);pending.get('browser').open=true;await pending.get('browser').listeners.toggle();assert.deepEqual(requests,['/api/storage-locations']);
  pending.get('root').value='/var/srv/titan';pending.get('root').listeners.change();assert.equal(pending.get('value').value,'/var/srv/titan');UI.disposeWithin(pendingRoot);
 }
 const missingOnly=UI.selectField('Daten','storage_id',{default_storage:'volume:gone',storage:[]},'apps');assert.equal((missingOnly.match(/ selected/g)||[]).length,1);assert(missingOnly.includes('value="volume:gone" selected disabled'));
 const productionShape={...catalog,items:[...catalog.storage.map(item=>({...item,backup_eligible:item.id!=='system'})),{id:'external:usb',path:'/media/usb',label:'USB',backup_eligible:true}]};const backupRoots=UI.resources(productionShape,'backups').map(item=>item.path);assert.equal(backupRoots.join(','),'/srv/photos/backups,/srv/archive/backups,/media/usb');assert(!backupRoots.includes('/srv/photos'));assert(!backupRoots.includes('/srv/archive'));assert(!backupRoots.includes('/var/srv/titan'));
 const defaults=widget('apps',''),offline=widget('directory','/srv/archive/old'),bounded=widget('backup','/srv/photos/backups/2026'),catalogRoot={querySelectorAll:()=>[defaults.w,offline.w,bounded.w],contains:()=>true};const boundedCalls=[];await UI.mount(catalogRoot,{api:async url=>{boundedCalls.push(url);return url==='/api/storage-locations'?catalog:{entries:[],total:0};}});assert.equal(defaults.get('value').value,'/srv/photos');assert.equal(offline.get('root').value,'/srv/archive');assert(offline.get('browser').hidden);assert(offline.get('status').textContent.includes('nicht verfügbar'));bounded.get('up').listeners.click();await new Promise(resolve=>setImmediate(resolve));assert.equal(bounded.get('value').value,'/srv/photos/backups');assert(bounded.get('up').disabled);bounded.get('up').listeners.click();assert.equal(bounded.get('value').value,'/srv/photos/backups');assert(!boundedCalls.some(url=>url.includes('path=srv%2Fphotos&')));UI.disposeWithin(catalogRoot);
 console.log('Location UI: eligible roots, preserved selected subfolders, escaped names, safe folders, pagination, navigation boundaries and disposed async response passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
