'use strict';
const assert=require('node:assert/strict');
const packages=require('../titan/web/package_center.js');
const vms=require('../titan/web/vm_extensions.js');
const live=require('../titan/web/vm_live.js');
const services=[{id:'app',name:'Immich',image:'image:v1',state:'running',health:'healthy',ready:true,depends_on:['database']},{id:'database',name:'PostgreSQL',image:'db:v1',state:'running',health:'unhealthy',ready:false}];
const data={app:{id:'titan-immich',name:'Immich'},services,phase:'attention',running_services:2,ready:false,warnings:['<script>alert(1)</script>'],settings:[],login:{instructions:'Eigene Anmeldung erstellen'},update:{available:true,message:'Sicherung vor Update'},port:2283};
const overview=packages.render(data,null);
assert.match(overview,/PostgreSQL/);
assert.match(overview,/1 \/ 2 Dienste bereit/);
assert.match(overview,/&lt;script&gt;/);
assert.doesNotMatch(overview,/<script>/);
assert.match(overview,/data-package-command="repair"/);
const settings=packages.render(data,null,'settings');
assert.match(settings,/type="submit" disabled/);
assert.doesNotMatch(settings,/office_secret|database_password/);
const profiles=packages.render({...data,settings:[{key:'resource_profile',label:'RAM-Profil',editable:true,type:'text',value:'balanced',choices:[['balanced','Ausgewogen'],['performance','Mehr Parallelität']]},{key:'office_mode',label:'Office',editable:true,type:'text',value:'disabled',choices:[['disabled','Ohne Office'],['enabled','Office mitinstallieren']]}]},null,'settings');
assert.match(profiles,/<select name="resource_profile" required>/);assert.match(profiles,/<option value="balanced" selected>Ausgewogen/);assert.match(profiles,/<select name="office_mode" required>/);assert.doesNotMatch(profiles,/<input name="resource_profile"/);
const logs=packages.render(data,null,'logs');
assert.match(logs,/<option value="database">PostgreSQL/);
const vm={id:'a',name:'Test',cpus:2,memory_mb:2048,firmware:'uefi',cpu_ids:[0,1]},extensions={state:'shut off',guest_agent:{configured:false,connected:false,message:'Installieren'},disks:[{target:'vda',disk:'/vm.qcow2',boot:true,virtual_size:10,allocated_bytes:2}],networks:[],snapshots:[{id:'s-abc',name:'<unsafe>',created:1,disk_count:1}],snapshot_note:'Alle Laufwerke',external_backup_available:true};
const bytes=value=>value+' B';
 const destinations=[{id:'system',label:'Interner Speicher',available:true},{id:'pool:offline',label:'Archiv',available:false},{id:'volume:full',label:'Voll',available:true,status:'full'}];
 for(const id of ['pool:offline','volume:full','volume:missing']){const field=vms.storageField({storage:destinations,default_storage:id});assert.match(field,new RegExp('value="'+id+'" selected disabled'));assert(!field.includes('value="system" selected'));}
assert.match(vms.render(vm,extensions,'console',{bytes}),/sobald die VM läuft/);
const active=vms.render(vm,{...extensions,state:'running'},'hardware',{bytes});
assert.match(active,/data-vmx-command="disk-add" disabled/);
assert.match(active,/data-vmx-command="guest-shutdown" disabled/);
const backup=vms.render(vm,extensions,'backups',{bytes});
assert.match(backup,/&lt;unsafe&gt;/);
assert.doesNotMatch(backup,/<unsafe>/);
assert.match(backup,/data-vmx-command="snapshot-restore"/);
const stoppedLive=live.render({...vm,state:'shut off',virtual_size:32,disk_count:2,disk_total_capacity_bytes:48,metrics:{cpu_percent:99,memory_resident_bytes:999,disk_allocated_bytes:4,disk_read_bps:128,disk_write_bps:64,network_rx_bps:1,network_tx_bps:2}},{bytes,esc:value=>String(value)});
assert.match(stoppedLive,/48 B Kapazität · 2 Laufwerke/);
assert.doesNotMatch(stoppedLive,/32 B Kapazität|128 B\/s|64 B\/s|99 %|999 B/);
assert.equal((stoppedLive.match(/0 B\/s/g)||[]).length,4,'Stopped VM never renders stale I/O');
async function managerLifecycle(){
 const js=require('node:vm'),fs=require('node:fs'),listeners=[];
 const body={querySelector:()=>null,contains:()=>true,addEventListener:(type,listener,options)=>listeners.push({type,listener,signal:options.signal})};
 const modal={open:true,close(){this.open=false;},addEventListener(){}};
 const browser={document:{getElementById:id=>id==='dialog-body'?body:modal,hidden:false}};
 const sandbox={window:browser,AbortController,URLSearchParams,Date,setInterval,clearInterval};
 js.runInNewContext(fs.readFileSync(require.resolve('../titan/web/package_center.js'),'utf8'),sandbox);
 js.runInNewContext(fs.readFileSync(require.resolve('../titan/web/vm_extensions.js'),'utf8'),sandbox);
 const dialog=()=>{browser.TitanPackageCenter.dispose();browser.TitanVMExtensions.dispose();modal.open=true;};
 const api=async path=>path.startsWith('/api/package-details')?{...data,installed:true}:path.startsWith('/api/app-details')?null:path.startsWith('/api/vm-options')?{storage:[{id:'system',label:'Systemlaufwerk'}]}:extensions;
 await browser.TitanPackageCenter.open('titan-immich',{api,dialog,action:async()=>{},askYesNo:async()=>false});
 assert.equal(listeners.at(-1).signal.aborted,false,'New package handlers survive shared dialog disposal');
 const packageSignal=listeners.at(-1).signal;
 await browser.TitanVMExtensions.open(vm,{api,dialog,action:async()=>{},askYesNo:async()=>false,bytes},'console');
 assert.equal(packageSignal.aborted,true,'Changing manager releases old listeners');
 assert.equal(listeners.at(-1).signal.aborted,false,'New VM handlers survive shared dialog disposal');
 const vmSignal=listeners.at(-1).signal;
 browser.TitanVMExtensions.dispose();
 assert.equal(vmSignal.aborted,true,'Closing manager releases its listeners');
}
managerLifecycle().then(()=>console.log('Package and VM state, escaping and dialog lifecycle checks passed.')).catch(error=>{console.error(error);process.exitCode=1;});
