'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function node(){const listeners={};return {listeners,dataset:{},hidden:false,addEventListener:(type,fn)=>listeners[type]=fn,removeEventListener:(type,fn)=>{if(listeners[type]===fn)delete listeners[type];}};}
const main=node(),dialogNode=node(),search=node(),noResults=node(),rows=[node(),node()];
rows[0].dataset.search='docker.service container aktiv';rows[1].dataset.search='ssh.service remote gestoppt';
main.querySelector=selector=>selector==='#service-search'?search:selector==='#service-no-results'?noResults:null;
main.querySelectorAll=()=>rows;
const context={window:{},document:{querySelector:()=>dialogNode},console};vm.createContext(context);vm.runInContext(fs.readFileSync('titan/web/services_controls.js','utf8'),context);const moduleUI=context.window.TitanServices;
const sample={items:[{name:'docker.service',description:'Containers <script>',active:'active',enabled:true,unit_file_state:'enabled',allowed_actions:['start','stop','restart','enable','disable']},{name:'titan-agent.service',description:'Titan',active:'active',enabled:true,protected:true,allowed_actions:['start','enable']}],users:[{name:'titan-files',label:'Dateibenutzer'},{name:'root',label:'root'}],total:2};
const calls=[],dialogs=[],errors=[];
const ctx={esc,pill:(text)=>`<span>${esc(text)}</span>`,field:(label,name,type,value,attrs,hint)=>`<label>${label}<input name="${name}" ${attrs}></label><small>${hint||''}</small>`,selectField:(label,name,options,value)=>`<select name="${name}" data-default="${value}">${options.map(([key,text])=>`<option>${esc(key)} ${esc(text)}</option>`).join('')}</select>`,formEnd:()=>'</form>',dialog:(title,html,submit)=>dialogs.push({title,html,submit}),toast:(message)=>errors.push(message),action:async(op,args)=>calls.push({op,args}),navigate:async()=>calls.push({navigate:true}),api:async(path)=>{calls.push({path});return {service:{...sample.items[0],name:'ssh@lab.service',properties:{User:'<root>',MainPID:'12',FragmentPath:'/etc/test',Result:'exit-code'}},logs:'<script>alert(1)</script>',logs_error:'<bad>',logs_truncated:true};}};
const click=async(kind,service,command)=>{const target={dataset:{serviceAction:kind,service,command},disabled:false};await main.listeners.click({target:{closest:()=>target}});assert.equal(target.disabled,false);};
(async()=>{
 const html=moduleUI.render(sample,ctx);assert(html.includes('&lt;script&gt;'));assert(!html.includes('Containers <script>'));assert(html.includes('Autostart: An'));assert(html.includes('data-command="stop"'));assert(!html.includes('data-command="start"'));assert(!html.includes('data-command="enable"'));assert(html.includes('Titan-Zugang geschützt'));assert(!html.includes('data-command="restart"'));assert(!html.includes('data-command="disable"'));
 moduleUI.mount(main,ctx,sample);search.listeners.input({target:{value:' ssh '}});assert(rows[0].hidden);assert(!rows[1].hidden);assert(noResults.hidden);search.listeners.input({target:{value:'nothing'}});assert(!noResults.hidden);
 await click('details','ssh@lab.service');assert.equal(calls.at(-1).path,'/api/service-details?service=ssh%40lab.service');assert(dialogs.at(-1).html.includes('&lt;script&gt;'));assert(dialogs.at(-1).html.includes('&lt;root&gt;'));assert(dialogs.at(-1).html.includes('64 KiB'));assert(dialogs.at(-1).html.includes('data-command="restart"'));assert(dialogs.at(-1).html.includes('data-command="disable"'));
 await click('command','docker.service','restart');assert.equal(calls.at(-1).op,'service_action');assert.equal(calls.at(-1).args.service,'docker.service');assert.equal(calls.at(-1).args.command,'restart');const count=calls.length;await click('command','docker.service','shell');assert.equal(calls.length,count);
 await click('create');assert(dialogs.at(-1).html.includes('titan-custom-NAME.service'));assert(dialogs.at(-1).html.includes('data-default="titan-files"'));assert(dialogs.at(-1).html.includes('name="autostart"'));assert(dialogs.at(-1).html.includes('name="start"'));
 const form=new Map([['name','worker'],['description','My Worker'],['program','/usr/bin/python3'],['args','/srv/worker.py'],['user','titan-files'],['working_directory','/srv'],['start','on']]);await dialogs.at(-1).submit(form);assert.equal(calls.at(-1).op,'service_create');assert.equal(calls.at(-1).args.start,true);assert.equal(calls.at(-1).args.autostart,false);assert.equal(calls.at(-1).args.program,'/usr/bin/python3');
 ctx.api=async()=>{throw Error('Protokoll nicht verfügbar');};await click('details','unknown.service');assert.equal(errors.at(-1),'Protokoll nicht verfügbar');
 moduleUI.dispose();assert(!main.listeners.click);assert(!dialogNode.listeners.click);assert(!search.listeners.input);
 // Background jobs must not re-render and disconnect an active terminal.
 const app=fs.readFileSync('titan/web/app.js','utf8');assert(app.includes("if(page!=='terminal'"));assert(app.includes("window.TitanTerminal?.dispose()"));assert(app.includes("['services','Dienste']"));assert(app.includes("['terminal','Terminal']"));
 console.log('Services UI: escaped inventory/logs, search, allowed controls, captured names, create flags, failure and disposal passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
