'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('titan/web/app.js','utf8'),start=source.indexOf('function permissionsFields('),end=source.indexOf('function bindPage()',start),context={FormData,esc:value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))};vm.createContext(context);vm.runInContext(source.slice(start,end),context);
const html=context.permissionsFields({web:[{name:'zeus',system_user:'titan-files'}],system:[{name:'titan-files',enabled:true},{name:'alice',enabled:true},{name:'bob',enabled:false}]},['alice'],['titan-files']);assert(html.includes('Zugriff pro Benutzer'));assert(html.includes('Kein Zugriff'));assert(html.includes('Nur Lesen'));assert(html.includes('Lesen und Schreiben'));assert(html.includes('Titan-Apps'));assert(html.includes('App-Dateizugriff: <code>titan-files</code>'));assert(html.includes('kein SMB-Login'));assert(html.includes('Konto gesperrt'));assert(!html.includes('type="checkbox"'));
const data=new FormData();data.set('permission-titan-files','write');data.set('permission-alice','read');data.set('permission-bob','none');const result=JSON.parse(JSON.stringify(context.readPermissions(data)));assert.deepEqual(result,{readers:['alice'],writers:['titan-files']});data.set('permission-bob','bogus');assert.throws(()=>context.readPermissions(data),/Ungültige/);data.set('permission-bob','none');data.set('permission-titan-files','none');data.set('permission-alice','none');assert.throws(()=>context.readPermissions(data),/mindestens/);
console.log('Share permissions UI: one access choice per account, SMB identity labels, no-access exclusion and malformed/empty selection validation passed.');
const connection=context.shareAccessLinks({name:'Familie',readers:['alice'],writers:['zeus']},{service_active:true,host_addresses:[{family:4,scope:'lan',address:'192.168.10.18',interface:'eth0'},{family:4,scope:'loopback',address:'127.0.0.1'},{family:6,scope:'lan',address:'fe80::1'}]},{web:[],system:[],service_user:'titan-files'});assert(connection.includes('\\\\192.168.10.18\\Familie'));assert(connection.includes('smb://192.168.10.18/Familie'));assert(!connection.includes('127.0.0.1'));assert(!connection.includes('fe80::1'));assert(connection.includes('share-copy-link'));
const legacy=context.shareAccessLinks({name:'privat',readers:[],writers:['titan-files']},{service_active:false,host_addresses:[]},{web:[{name:'zeus',system_user:'titan-files'}],service_user:'titan-files'});assert(legacy.includes('eigenes SMB-Konto'));assert(legacy.includes('SMB-Dienst läuft derzeit nicht'));assert(legacy.includes('Keine LAN-IPv4-Adresse'));
console.log('Share links UI: actual LAN IPv4, exact Windows and Mac/Linux share links, copy controls and legacy first-admin migration notice passed.');

const noAccess=new FormData();noAccess.set('permission-alice','none');assert.deepEqual(JSON.parse(JSON.stringify(context.readPermissions(noAccess,true))),{readers:[],writers:[]});
const serviceOnly=context.shareAccessLinks({name:'apps',readers:[],writers:['titan-files']},{host_addresses:[]},{web:[],service_user:'titan-files',system:[{name:'titan-files',smb_ready:false}]});assert(serviceOnly.includes('SMB-Anmeldung mit Schreibzugriff: <strong>Keine</strong>'));assert(serviceOnly.includes('keinen SMB-Login'));
