'use strict';
const assert=require('node:assert/strict');
const ui=require('../titan/web/storage_view.js');
const GiB=1024**3;
const fixture={disks:[{name:'/dev/sda',type:'disk',model:'System SSD',size:64*GiB,children:[{name:'/dev/sda4',size:60*GiB,fstype:'xfs',mountpoints:['/var']}]},{name:'/dev/sdb',type:'disk',model:'Archive disk',size:200*GiB}],volumes:[{name:'photos',filesystem:'ext4',mounted:true,total:100*GiB,used:20*GiB,free:80*GiB,disk:'/dev/sdb',mountpoint:'/srv/photos'},{name:'disconnected',filesystem:'xfs',mounted:false,total:0,used:0,free:0,disk:'/dev/sdc'}],pools:[{name:'tank',health:'ONLINE',size:1000*GiB,used:300*GiB,free:700*GiB}],datasets:[{name:'tank',used:300*GiB,available:700*GiB},{name:'tank/documents',used:50*GiB,available:700*GiB,mountpoint:'/tank/documents'}],existing_filesystems:[{name:'/dev/sda4',fstype:'xfs',size:60*GiB},{name:'/dev/sdb',fstype:'ext4',size:100*GiB}],status:'pool tank ONLINE'};
const system={data:{disk:'/dev/sda',partition:'/dev/sda4',filesystem:'xfs',filesystem_size:60*GiB,filesystem_used:10*GiB,filesystem_available:50*GiB}};
const health={disks:[{name:'/dev/sda',health:'passed',temperature:35},{name:'/dev/sdb',health:'unknown',temperature:null}],alerts:[{key:'volume:disconnected',active:true,title:'Volume fehlt',detail:'Volume nicht verbunden'},{key:'service:docker',active:true,title:'Docker',detail:'Irrelevant here'}]};
const state=ui.summary(fixture,system,health);
assert.equal(state.activeDataCount,2);assert.equal(state.driveCount,2);assert.equal(state.problems,1);assert.equal(state.alerts.length,1);
assert.deepEqual(state.records.map(r=>r.key),['system','volume:photos','pool:tank']);
assert.equal(state.records.reduce((total,r)=>total+r.total,0),1160*GiB,'datasets share pool space and disconnected areas do not invent active capacity');
const html=ui.render(fixture,[{name:'tank/documents@test',created:1000,used:1}],system,{health,systemPanel:()=>'<section data-system-disk-panel>Original system extension controls</section>'});
for(const token of ['data-action="volume-mount" data-name="disconnected"','data-storage-area="volume:disconnected"','data-storage-area-detail="volume:disconnected"','data-storage-pane="overview"','data-storage-pane="areas"','data-storage-pane="disks"','data-storage-pane="health"','data-storage-open-area="volume:photos"','data-storage-open-disk="/dev/sda"','Original system extension controls','data-storage-mobile-area','data-storage-mobile-disk','data-schedule-target="/dev/sda"','data-storage-area-detail="pool:tank"','data-dataset="tank/documents"','data-pool="tank"','data-storage-command="restore"','data-storage-command="remove-snapshot"','Nicht eingehängt · keine Messwerte'])assert(html.includes(token),token);
assert(html.includes('class="storage-manager-content"'));assert(!html.includes('class="storage-content"'));
assert(html.includes('data-storage-pane="settings"'));assert(html.includes('data-storage-preferences'));assert(!html.includes('Weitere erkannte Dateisysteme'),'system partition and managed disk should not be counted as extra areas');
assert(!html.includes('Irrelevant here'));assert(!html.includes('NaN'));assert(!html.includes('max="0"'));assert(!html.includes('ZFS-Speicherbereiche</h2>'),'datasets are nested in their actual pool');
const malicious=ui.render({volumes:[{name:'<img onerror="x">',filesystem:'<script>',mounted:true,total:NaN,used:Infinity,free:null}],pools:[{name:'<svg>',health:'<script>',size:null}],datasets:[],disks:[]},[],{error:'<script>'},{health:{alerts:[{active:true,key:'space:system',title:'<img>',detail:'<script>'}]}});
assert(!malicious.includes('<script>'));assert(!malicious.includes('<img'));assert(!malicious.includes('<svg>'));assert(malicious.includes('&lt;script&gt;'));assert(!malicious.includes('NaN'));assert(!malicious.includes('Infinity'));
const empty=ui.render({},[],{},{});assert(empty.includes('Noch keine verlässlichen Kapazitätswerte'));assert(empty.includes('data-storage-command="schedule" disabled'));assert(!empty.includes('ZFS-Prüfstatus'));
 const resourceChoices=[{id:'system',kind:'internal',label:'Interner Speicher',available:true,capabilities:['apps']},{id:'pool:offline',kind:'pool',label:'Archiv',available:false,capabilities:['apps']},{id:'volume:full',kind:'volume',label:'Volles Laufwerk',available:true,status:'full',capabilities:['apps']},{id:'external:backup',kind:'external',label:'USB-Sicherung',available:true,capabilities:['files','backups']}];
 for(const id of ['pool:offline','volume:full','volume:gone']){const settings=ui.render({},[],{},{locations:{default_storage:id,storage:resourceChoices}}),select=settings.match(/<select id="storage-default"[^>]*>([^]*?)<\/select>/)[1];assert.match(select,new RegExp('value="'+id+'" (?:disabled selected|selected disabled)'));assert(!select.includes('value="system" selected'));assert(!select.includes('external:backup'));}
 const noDisks=ui.render({},[],{},{locations:{default_storage:'volume:gone',storage:[]}});assert.match(noDisks,/value="volume:gone" disabled selected/);assert.match(noDisks,/<button type="submit" class="button primary" disabled>Standard speichern/);
const smartInfo=ui.smartDetails({smart_status:{passed:true},temperature:{current:35},model_name:'Drive <script>',power_on_time:{hours:120},power_cycle_count:4},'/dev/sda');assert(smartInfo.includes('35 °C'));assert(smartInfo.includes('120 Stunden'));assert(smartInfo.includes('unauffälligen Zustand'));assert(!smartInfo.includes('<script>'));assert(!ui.smartDetails({},'/dev/sda').includes('unauffälligen Zustand'));assert(ui.smartDetails({smart_status:{passed:false}},'/dev/sda').includes('Laufwerksproblem'));
class Node {
 constructor(dataset={}){this.dataset=dataset;this.nodes={};this.lists={};this.events=new Map();this.attributes={};this.hidden=false;this.disabled=false;this.scrollTop=99;this.classList={toggle:(key,value)=>{this.attributes['class:'+key]=value;}};}
 querySelector(key){return this.nodes[key]||null;}querySelectorAll(key){return this.lists[key]||[];}contains(){return true;}closest(){return this;}
 matches(selector){return selector===this.selector;}setAttribute(key,value){this.attributes[key]=value;}addEventListener(name,fn){this.events.set(name,fn);}removeEventListener(name,fn){if(this.events.get(name)===fn)this.events.delete(name);}
 focus(){this.focused=true;}async dispatch(name,event){return this.events.get(name)?.(event);}
}
function mountFixture(){
 const main=new Node(),surface=new Node(),content=new Node(),title=new Node(),areaPicker=new Node(),diskPicker=new Node();
 main.nodes['[data-storage-workspace]']=surface;surface.nodes={'.storage-manager-content':content,'[data-storage-title]':title,'[data-storage-mobile-area]':areaPicker,'[data-storage-mobile-disk]':diskPicker};
 surface.lists={'[data-storage-tab]':['overview','areas','disks','health','settings'].map(storageTab=>new Node({storageTab})),'[data-storage-pane]':['overview','areas','disks','health','settings'].map(storagePane=>new Node({storagePane})),'[data-storage-area]':['system','volume:photos','pool:tank'].map(storageArea=>new Node({storageArea})),'[data-storage-area-detail]':['system','volume:photos','pool:tank'].map(storageAreaDetail=>new Node({storageAreaDetail})),'[data-storage-disk]':['/dev/sda','/dev/sdb'].map(storageDisk=>new Node({storageDisk})),'[data-storage-disk-detail]':['/dev/sda','/dev/sdb'].map(storageDiskDetail=>new Node({storageDiskDetail}))};
 const preferences=new Node(),select=new Node(),submit=new Node(),message=new Node();select.value='volume:photos';preferences.elements={default_storage:select};preferences.nodes={'[type=submit]':submit,'[data-storage-preferences-status]':message};surface.nodes['[data-storage-preferences]']=preferences;const calls=[],reads=[],dialogs=[],errors=[],questions=[];let answer=true;
 const ctx={locations:{default_storage:'system',storage:[{id:'system',available:true,capabilities:['apps']},{id:'volume:photos',available:true,capabilities:['apps']},{id:'pool:offline',available:false,capabilities:['apps']}]},api:async url=>{reads.push(url);return {smart_status:{passed:true},temperature:{current:38}};},storage:fixture,maintenance:{jobs:[],runs:{}},action:async(name,args)=>calls.push({name,args}),toast:(...args)=>errors.push(args),askYesNo:async question=>{questions.push(question);return answer;},dialog:(...args)=>dialogs.push(args)};
 const mounted=ui.mount(main,ctx);return {main,surface,content,title,areaPicker,diskPicker,preferences,select,submit,message,calls,reads,dialogs,questions,errors,mounted,setAnswer:value=>answer=value};
}
(async()=>{
 const f=mountFixture();assert.equal(f.title.textContent,'Übersicht');assert.equal(f.areaPicker.value,'system');assert.equal(f.diskPicker.value,'/dev/sda');
 await f.surface.dispatch('click',{target:new Node({storageOpenArea:'pool:tank'})});assert.equal(f.title.textContent,'Speicherbereiche');assert.equal(f.areaPicker.value,'pool:tank');assert.equal(f.content.scrollTop,0);assert.equal(f.surface.lists['[data-storage-pane]'].find(p=>p.dataset.storagePane==='areas').hidden,false);assert.equal(f.surface.lists['[data-storage-area-detail]'].find(p=>p.dataset.storageAreaDetail==='pool:tank').hidden,false);assert.equal(f.surface.lists['[data-storage-area-detail]'].filter(p=>!p.hidden).length,1);
 await f.surface.dispatch('click',{target:new Node({storageOpenDisk:'/dev/sdb'})});assert.equal(f.title.textContent,'HDD / SSD');assert.equal(f.diskPicker.value,'/dev/sdb');assert.equal(f.surface.lists['[data-storage-disk-detail]'].filter(p=>!p.hidden).length,1);
 f.areaPicker.selector='[data-storage-mobile-area]';f.areaPicker.value='volume:photos';await f.surface.dispatch('change',{target:f.areaPicker});assert.equal(f.surface.lists['[data-storage-area]'][1].attributes['aria-pressed'],'true');
 f.diskPicker.selector='[data-storage-mobile-disk]';f.diskPicker.value='/dev/sda';await f.surface.dispatch('change',{target:f.diskPicker});assert.equal(f.surface.lists['[data-storage-disk]'][0].attributes['aria-pressed'],'true');
 let prevented=false;const last=f.surface.lists['[data-storage-tab]'][4];await f.surface.dispatch('keydown',{target:last,key:'ArrowDown',preventDefault(){prevented=true;}});assert(prevented);assert.equal(f.title.textContent,'Übersicht');assert(f.surface.lists['[data-storage-tab]'][0].focused);assert.equal(f.surface.lists['[data-storage-tab]'].filter(b=>b.attributes.tabindex==='0').length,1);
 f.mounted.selectArea('removed-area');assert.equal(f.areaPicker.value,'system');f.mounted.selectDisk('removed-disk');assert.equal(f.diskPicker.value,'/dev/sda');
 const smartButton=new Node({storageCommand:'smart',disk:'/dev/sdb'});await f.surface.dispatch('click',{target:smartButton});const [title,form,submit]=f.dialogs.at(-1);assert.equal(title,'SMART-Selbsttest');assert(form.includes('/dev/sdb'));await submit(new Map([['test','long']]));assert.deepEqual(f.calls.at(-1),{name:'smart_test',args:{disk:'/dev/sdb',test:'long'}});
 f.setAnswer(false);await f.surface.dispatch('click',{target:new Node({storageCommand:'remove-snapshot',snapshot:'tank/documents@test'})});assert.equal(f.calls.length,1);f.setAnswer(true);await f.surface.dispatch('click',{target:new Node({storageCommand:'remove-snapshot',snapshot:'tank/documents@test'})});assert.deepEqual(f.calls.at(-1),{name:'snapshot_remove',args:{snapshot:'tank/documents@test',confirmed:true}});assert(f.questions.at(-1).includes('endgültig löschen'));
 const disabled=new Node({storageCommand:'smart',disk:'/dev/sda'});disabled.disabled=true;await f.surface.dispatch('click',{target:disabled});assert.equal(f.dialogs.length,1);
 await f.surface.dispatch('click',{target:new Node({storageCommand:'inspect-smart',disk:'/dev/sdb'})});assert.equal(f.reads.at(-1),'/api/smart?disk=%2Fdev%2Fsdb');assert.equal(f.dialogs.at(-1)[0],'Laufwerkszustand');assert(f.dialogs.at(-1)[1].includes('38 °C'));
 const originalFormData=global.FormData;global.FormData=class{constructor(form){this.form=form;}get(name){return this.form.elements[name].value;}};try{f.mounted.selectTab('settings');assert.equal(f.title.textContent,'Einstellungen');const previous=f.calls.length;await f.preferences.dispatch('submit',{preventDefault(){}});assert.deepEqual(f.calls.at(-1),{name:'storage_preferences_save',args:{default_storage:'volume:photos'}});assert.equal(f.calls.length,previous+1);f.select.value='pool:offline';await f.preferences.dispatch('submit',{preventDefault(){}});assert.equal(f.calls.length,previous+1);assert(f.message.textContent.includes('verfügbaren'));assert(!f.submit.disabled);}finally{global.FormData=originalFormData;}f.mounted.selectTab('overview');
 ui.dispose();assert.equal(f.surface.events.size,0);const restored=mountFixture();assert.equal(restored.title.textContent,'Übersicht');assert.equal(restored.diskPicker.value,'/dev/sda');ui.dispose();
 console.log('Storage Manager workspace: active capacity accounting, selected area/drive navigation, mobile selectors, keyboard tabs, original actions, confirmation and disposal passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
