'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const fields={},browser={},sandbox={module:{exports:fields}};
vm.runInNewContext(fs.readFileSync('titan/web/template_fields.js','utf8'),sandbox);const formUI=sandbox.module.exports;
sandbox.module={exports:browser};vm.runInNewContext(fs.readFileSync('titan/web/template_browser.js','utf8'),sandbox);const catalogUI=sandbox.module.exports;
const schema={install_schema:[{key:'required',label:'Titre <script>',type:'text',required:true,default:'ready'},{key:'peer',label:'Peer-Port',type:'number',default:51413,optional:true},{key:'key',label:'Schlüssel',type:'password',default:'NEVER-SHOW'},{key:'media',label:'Medienordner',type:'boolean',optional:true},{key:'timezone',label:'Zeitzone',type:'text',default:'Europe/Berlin',optional:true,enabled_by_default:true}]};
const html=formUI.fields(schema);assert(html.includes('Titre &lt;script&gt;'));assert(!html.includes('NEVER-SHOW'));assert.match(html,/name="option-peer"[^>]*disabled/);assert.match(html,/data-template-enable="timezone" checked/);assert(!html.includes('type="boolean"'));
const data=new FormData();data.set('option-required','ready');data.set('option-peer','51413');data.set('option-timezone','Europe/Berlin');data.set('enable-timezone','on');data.set('option-key','private');
let options=formUI.argumentsFor(schema,data);assert.equal(options.required,'ready');assert.equal(options.timezone,'Europe/Berlin');assert.equal(options.key,'private');assert(!Object.hasOwn(options,'peer'));assert(!Object.hasOwn(options,'media'));
data.set('enable-peer','on');data.set('enable-media','on');options=formUI.argumentsFor(schema,data);assert.equal(options.peer,51413);assert.equal(options.media,true);
const summary=formUI.summary({port_bindings:[{published:8080,target:80,protocol:'tcp',service:'web'}],storage_bindings:[{target:'/config',readonly:false},{target:'/movies',optional:true,readonly:true}]});assert(summary.includes('8080 → 80/tcp'));assert(summary.includes('Nur Lesen'));assert(summary.includes('optional'));
let bindCount=0;const listeners=new Map(),holder={querySelectorAll:()=>[{set disabled(value){bindCount++;this.value=value;}}]},container={addEventListener:(type,fn)=>listeners.set(type,fn),removeEventListener:(type,fn)=>{if(listeners.get(type)===fn)listeners.delete(type);}};
formUI.bind(container);const dispose=formUI.bind(container);listeners.get('change')({target:{matches:()=>true,closest:()=>holder,checked:true}});assert.equal(bindCount,1,'Reopening a reused dialog does not duplicate bindings');dispose();assert.equal(listeners.size,0);
const apps=[{id:'z',name:'Zulu',description:'Medien',store_name:'Big Bear'},{id:'a',name:'Alpha',description:'Dateien',store_name:'LinuxServer.io'},{id:'b',name:'Beta',description:'Medien',store_name:'LinuxServer.io'}];
assert.deepEqual(Array.from(catalogUI.filter(apps,{query:'medien',source:'LinuxServer.io'}),app=>app.id),['b']);assert.deepEqual(Array.from(catalogUI.filter(apps,{sort:'za'}),app=>app.id),['z','b','a']);
function fixture(){const handlers=new Map(),scope={innerHTML:'',ownerDocument:{activeElement:null},contains:()=>true,querySelector:()=>null,addEventListener:(name,fn)=>handlers.set(name,fn),removeEventListener:(name,fn)=>{if(handlers.get(name)===fn)handlers.delete(name);}};const click=async dataset=>handlers.get('click')({target:{closest:()=>({dataset})}});return{scope,handlers,click};}
(async()=>{
 const f=fixture();let installs=0;const calls=[],catalog={apps},source={stores:[],presets:[{id:'bigbear',name:'Big Bear',url:'https://github.com/bigbeartechworld/big-bear-dockge'}]};const ctx={api:async path=>path==='/api/catalog'?catalog:source,install:async id=>{assert.equal(id,'a');installs++;},action:async(operation,args,opts)=>{calls.push({operation,args,wait:opts.wait});source.stores=[{id:'bigbear',url:source.presets[0].url,name:'Big Bear',enabled:true,apps:3,skipped:[]}];return{ok:true};},toast(){}};
 const ui=catalogUI.mount(f.scope,ctx);for(let i=0;i<6;i++)await Promise.resolve();assert(f.scope.innerHTML.includes('Alpha'));await f.click({templateInstall:'a'});assert.equal(installs,1);await f.click({templateRefresh:'bigbear'});assert.equal(calls[0].operation,'app_store_add');assert.equal(calls[0].args.trusted,true);assert.equal(calls[0].wait,true);await f.click({templateToggle:'bigbear'});assert.equal(calls[1].operation,'app_store_toggle');assert.equal(calls[1].args.enabled,false);ui.destroy();assert.equal(f.handlers.size,0);
 const stale=fixture();let reply;const old=catalogUI.mount(stale.scope,{...ctx,api:path=>path==='/api/catalog'?new Promise(resolve=>reply=resolve):Promise.resolve(source)});const initial=stale.scope.innerHTML;old.destroy();reply(catalog);for(let i=0;i<6;i++)await Promise.resolve();assert.equal(stale.scope.innerHTML,initial,'Disposed lookup cannot write the next application');
 console.log('Docker templates: source load/toggle, sorting/search, schema escaping, omitted optional defaults, selected boolean mounts, mapping summary and lifecycle cleanup passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
