'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const nodes=new Map();
const node=selector=>{
 if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',hidden:false,style:{},classList:{remove(){},toggle(){}},addEventListener(){},append(){},setAttribute(){},showModal(){},close(){}});
 return nodes.get(selector);
};
const context=vm.createContext({document:{querySelector:node,querySelectorAll:()=>[],addEventListener(){},createElement:()=>({remove(){}})},window:{addEventListener(){},getSelection:()=>({toString:()=>''})},location:{hostname:'nas',hash:'#users'},setTimeout:()=>0,setInterval:()=>0,clearInterval(){},fetch(){throw Error('Unexpected request');},URLSearchParams,FormData,AbortController,Uint8Array,console});
const source=fs.readFileSync('titan/web/app.js','utf8').replace(/boot\(\)\.catch\(error=>toast\(error.message,true\)\);\s*$/,'');
vm.runInContext(fs.readFileSync('titan/web/user_manager.js','utf8'),context);
vm.runInContext(source,context);
const evaluate=expression=>vm.runInContext(expression,context);
(async()=>{
 evaluate("session={user:{name:'admin',role:'admin',csrf:'synthetic-csrf',system_user:'titan-files'}};");
 const users=[{name:'admin',role:'admin',enabled:true,system_user:'titan-files'},{name:'reader',role:'user',enabled:true,system_user:'reader'}];
 context.fetch=async path=>({ok:true,json:async()=>path==='/api/managed-shares'?[]:({web:users,system:[{name:'reader',enabled:true},{name:'deleted',removed:true}],service_user:'titan-files'})});
 const html=await evaluate('pages.users()');
 assert.match(html,/data-action="user-remove" data-name="admin" disabled/);
 assert.match(html,/data-um-select="reader"/);
 assert.equal(context.window.TitanUsers.protectedAccount(users[1],users,'admin'),false);
 assert(!html.includes('deleted'));
 context.target={dataset:{name:'admin'}};
 assert.throws(()=>evaluate("actions['user-remove'](target)"),/eigenes Konto/);
 let captured;
 context.dialog=(title,body,submit)=>{captured={title,body,submit};};
 context.target={dataset:{name:'reader'}};
 evaluate("actions['user-remove'](target)");
 assert.equal(captured.title,'Benutzer löschen');
 assert(captured.body.includes('Ordner und Dateien bleiben erhalten.'));
 assert(!captured.body.includes('name="confirmation"'));
 assert(captured.body.includes('>Ja</button>')&&captured.body.includes('>Nein</button>'));
 const requests=[];
 context.fetch=async(url,options)=>{requests.push({url,...options});return {ok:true,json:async()=>({job:'delete-reader'})};};
 await captured.submit(new Map());
 assert.equal(requests.length,1);
 assert.equal(requests[0].url,'/api/users/remove');
 assert.deepEqual(JSON.parse(requests[0].body),{name:'reader',confirmation:true});
 assert.equal(requests[0].headers['X-CSRF-Token'],'synthetic-csrf');
 assert(evaluate("watched.has('delete-reader')"));
 assert.equal(evaluate("actionNames.user_remove"),'Benutzer löschen');
 console.log('User deletion UI: protected accounts, retained data, click confirmation, CSRF and job tracking passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
