'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={window:{},URLSearchParams,Event,console};vm.createContext(context);vm.runInContext(fs.readFileSync('titan/web/vm_image_picker.js','utf8'),context);
const ui=context.window.TitanVMImages;assert(ui.fields().includes('Image-Dateipfad'));assert(ui.fields().includes('QCOW2, RAW oder IMG'));
const callbacks={},nodes={};function node(key){return nodes[key]||=({value:'',disabled:false,hidden:false,innerHTML:'',textContent:'',addEventListener(name,fn){callbacks[key+':'+name]=fn;},removeEventListener(name){delete callbacks[key+':'+name];},dispatchEvent(event){this.lastEvent=event.type;},insertAdjacentHTML(_,value){this.innerHTML+=value;}});}
const widget={querySelector:node},form={querySelector:selector=>selector==='[data-vm-source-picker]'?widget:node(selector),contains:()=>true},options={disk_images:[]};let fail=false,pending;
const requests=[];ui.mount(form,options,{bytes:value=>String(value),api:async url=>{requests.push(url);if(url==='/api/storage-locations')return {default_storage:'system',storage:[{id:'system',label:'Interner Speicher',path:'/var/srv/titan',available:true,capabilities:['files']},{id:'volume:offline',label:'Archive',path:'/srv/archive',available:false,capabilities:['files']}]};if(pending)return pending;if(fail)throw Error('Image ist ungültig.');if(url.startsWith('/api/files?'))return {entries:[{name:'ordner',directory:true},{name:'guest.qcow2',size:20},{name:'notes.txt',size:1},{name:'alias.img',symlink:true}],offset:0,limit:200,total:4};return {id:'/var/srv/titan/guest.qcow2',path:'/var/srv/titan/guest.qcow2',name:'guest.qcow2',format:'qcow2',virtual_size:8*1024**3,min_disk_gb:8,source_retained:true};}});
(async()=>{node('[data-vm-source-path]').value='relative.qcow2';await callbacks['[data-vm-source-inspect]:click']();assert(node('[data-vm-source-status]').textContent.includes('absoluten'));assert.equal(requests.filter(url=>url.startsWith('/api/vm-image-info')).length,0);
node('[data-vm-source-path]').value='/var/srv/titan/guest.qcow2';await callbacks['[data-vm-source-inspect]:click']();assert.equal(options.disk_images.length,1);assert.equal(node('[name="disk_image"]').value,'/var/srv/titan/guest.qcow2');assert.equal(node('[name="disk_image"]').lastEvent,'change');assert(node('[data-vm-source-status]').textContent.includes('Quelle bleibt erhalten'));
node('[data-vm-source-path]').value='/var/srv/titan/other.img';callbacks['[data-vm-source-path]:input']();assert.equal(node('[name="disk_image"]').value,'');fail=true;await callbacks['[data-vm-source-inspect]:click']();assert(node('[data-vm-source-status]').textContent.includes('ungültig'));fail=false;
await callbacks['[data-vm-source-browse]:click']();assert(requests.at(-1).includes('share=%40system'));assert(node('[data-vm-source-up]').disabled);await callbacks['[data-vm-source-up]:click']();assert(!requests.some(url=>url.includes('path=&')));assert(node('[data-vm-source-root]').innerHTML.includes('Nicht verfügbar'));assert(!node('[data-vm-source-current]').textContent.startsWith('/var'));assert(node('[data-vm-source-entries]').innerHTML.includes('guest.qcow2'));assert(!node('[data-vm-source-entries]').innerHTML.includes('notes.txt'));assert(!node('[data-vm-source-entries]').innerHTML.includes('alias.img'));
let resolve;pending=new Promise(r=>resolve=r);node('[data-vm-source-path]').value='/var/srv/titan/slow.img';const late=callbacks['[data-vm-source-inspect]:click']();ui.disposeWithin(form);resolve({id:'/var/srv/titan/slow.img',path:'/var/srv/titan/slow.img',name:'slow.img',format:'raw',virtual_size:1024});await late;assert(!options.disk_images.some(item=>item.id==='/var/srv/titan/slow.img'));assert.equal(callbacks['[data-vm-source-inspect]:click'],undefined);
console.log('VM image picker UI: absolute path validation, inspected source selection, source changes invalidate selection, filtered NAS browser and closed-dialog race passed.');})().catch(error=>{console.error(error);process.exitCode=1;});
